export default {
    topic: 'Algorithms and Data Structures',
    title: 'Algorithms and Data Structures',
    shortNamePrefix: 'ADS',
    description: 'A comprehensive course on algorithm design and analysis, covering sorting, searching, graph algorithms, dynamic programming, and fundamental data structures. Students learn to analyze time and space complexity using Big-O notation and implement efficient solutions to computational problems.',
    lectures: [
        { title: 'Asymptotic Analysis and Big-O Notation', description: 'Understanding time and space complexity through asymptotic analysis.', units: [
            { type: 'text', name: 'Big-O, Big-Omega, and Big-Theta', content: 'Big-O describes the upper bound of an algorithm\'s growth rate. Big-Omega describes the lower bound. Big-Theta describes the tight bound. For example, binary search is O(log n), Omega(1), and Theta(log n) in the average case.' },
            { type: 'text', name: 'Common Complexity Classes', content: 'O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n) linearithmic, O(n^2) quadratic, O(2^n) exponential, O(n!) factorial. Knowing these helps compare algorithms and choose the most efficient one for a given problem size.' },
            { type: 'online', name: 'Algorithm Complexity Cheat Sheet', description: 'Visual reference of time and space complexities for common algorithms and data structures.' },
            { type: 'text', name: 'Amortized Analysis', content: 'Amortized analysis averages the cost of operations over a sequence. Dynamic array resizing costs O(n) occasionally but O(1) amortized per insertion. The banker\'s and physicist\'s methods are formal amortized analysis techniques.' },
            { type: 'attachment', name: 'Complexity Analysis Worksheet' },
        ]},
        { title: 'Sorting Algorithms', description: 'Comparison-based and non-comparison sorting algorithms with complexity analysis.', units: [
            { type: 'text', name: 'QuickSort and MergeSort', content: 'QuickSort uses divide-and-conquer with a pivot, achieving O(n log n) average but O(n^2) worst case. MergeSort guarantees O(n log n) but requires O(n) extra space. Both are recursive and widely used in practice.' },
            { type: 'text', name: 'HeapSort and Radix Sort', content: 'HeapSort uses a binary heap for O(n log n) in-place sorting. Radix Sort is non-comparison-based, sorting digit by digit in O(d*n) time where d is the number of digits. Counting Sort and Bucket Sort are other non-comparison alternatives.' },
            { type: 'online', name: 'Sorting Algorithm Visualizations', description: 'Interactive visualizations of sorting algorithms showing step-by-step comparisons and swaps.' },
            { type: 'text', name: 'Lower Bound for Comparison Sorting', content: 'Any comparison-based sorting algorithm must make at least O(n log n) comparisons in the worst case. This is proven using the decision tree model where each leaf represents a permutation and the tree has n! leaves.' },
            { type: 'attachment', name: 'Sorting Algorithm Comparison Table' },
        ]},
        { title: 'Binary Search Trees', description: 'BST operations, balancing, and self-balancing tree variants.', units: [
            { type: 'text', name: 'BST Operations', content: 'Binary Search Trees maintain the invariant that left children are smaller and right children are larger. Search, insert, and delete operations are O(h) where h is the tree height. In the worst case (skewed tree), h = n.' },
            { type: 'text', name: 'AVL Trees and Red-Black Trees', content: 'AVL trees maintain a balance factor of at most 1 between subtrees using rotations. Red-Black trees use color properties and rotations for O(log n) guaranteed operations. Java\'s TreeMap uses a Red-Black tree internally.' },
            { type: 'online', name: 'BST Visualization Tool', description: 'Interactive tool for inserting, deleting, and searching elements in various balanced BST implementations.' },
            { type: 'text', name: 'B-Trees and B+ Trees', content: 'B-Trees are multi-way search trees optimized for disk access. B+ Trees store all data in leaves linked in a list, enabling efficient range queries. They are used in database indexes and file systems.' },
            { type: 'attachment', name: 'Tree Rotation Reference' },
        ]},
        { title: 'Hash Tables and Hashing', description: 'Hash function design, collision resolution, and hash table implementations.', units: [
            { type: 'text', name: 'Hash Functions and Collision Resolution', content: 'Good hash functions distribute keys uniformly. Collision resolution methods include chaining (linked lists at each bucket) and open addressing (linear probing, quadratic probing, double hashing). Load factor affects performance.' },
            { type: 'text', name: 'Universal and Perfect Hashing', content: 'Universal hashing selects hash functions randomly from a family to minimize worst-case collisions. Perfect hashing achieves O(1) worst-case lookup for static sets. Cuckoo hashing uses two hash functions for O(1) lookup.' },
            { type: 'online', name: 'Hash Table Internals', description: 'Deep dive into how hash tables work internally in Java HashMap, Python dictionaries, and C++ unordered_map.' },
            { type: 'text', name: 'Bloom Filters', content: 'Bloom filters are probabilistic data structures for set membership testing. They may return false positives but never false negatives. Used in caches, spell checkers, and network routers for space-efficient approximate membership queries.' },
            { type: 'attachment', name: 'Hashing Problems Set' },
        ]},
        { title: 'Graph Algorithms I: Traversal', description: 'BFS, DFS, and their applications in graph problems.', units: [
            { type: 'text', name: 'Breadth-First Search', content: 'BFS explores vertices level by level using a queue. It finds shortest paths in unweighted graphs and runs in O(V+E) time. Applications include finding connected components, bipartiteness testing, and minimum spanning trees in unweighted graphs.' },
            { type: 'text', name: 'Depth-First Search', content: 'DFS explores as deep as possible before backtracking using a stack or recursion. It classifies edges as tree, back, forward, or cross edges. Applications include topological sort, cycle detection, and finding strongly connected components.' },
            { type: 'online', name: 'Graph Traversal Animations', description: 'Step-by-step animations of BFS and DFS on various graph types showing vertex discovery and edge classification.' },
            { type: 'text', name: 'Topological Sort', content: 'Topological sort orders vertices of a DAG so that for every directed edge (u,v), u comes before v. Kahn\'s algorithm uses in-degree tracking. DFS-based topological sort uses finish times. Used for task scheduling and dependency resolution.' },
            { type: 'attachment', name: 'Graph Traversal Exercises' },
        ]},
        { title: 'Graph Algorithms II: Shortest Paths', description: 'Dijkstra, Bellman-Ford, and Floyd-Warshall algorithms.', units: [
            { type: 'text', name: 'Dijkstra\'s Algorithm', content: 'Dijkstra\'s algorithm finds shortest paths from a source to all vertices in a graph with non-negative edge weights. Using a min-priority queue, it runs in O((V+E) log V). It employs a greedy strategy, relaxing edges of the nearest unvisited vertex.' },
            { type: 'text', name: 'Bellman-Ford and Floyd-Warshall', content: 'Bellman-Ford handles negative edge weights in O(VE) and detects negative cycles. Floyd-Warshall computes all-pairs shortest paths in O(V^3) using dynamic programming. Johnson\'s algorithm combines both for sparse graphs with negative weights.' },
            { type: 'online', name: 'Shortest Path Visualizer', description: 'Interactive tool for running Dijkstra, Bellman-Ford, and A* algorithms on custom graphs with weighted edges.' },
            { type: 'text', name: 'A* Search Algorithm', content: 'A* uses a heuristic function h(n) to estimate distance to the goal, combining it with g(n) the actual cost. With an admissible heuristic, A* finds optimal paths. It is widely used in pathfinding for games and robotics navigation.' },
            { type: 'attachment', name: 'Shortest Path Problem Set' },
        ]},
        { title: 'Dynamic Programming', description: 'Overlapping subproblems, optimal substructure, and memoization techniques.', units: [
            { type: 'text', name: 'Principles of Dynamic Programming', content: 'Dynamic programming solves problems by breaking them into overlapping subproblems with optimal substructure. Top-down (memoization) caches recursive results. Bottom-up (tabulation) builds solutions iteratively. Both avoid redundant computation.' },
            { type: 'text', name: 'Classic DP Problems', content: 'Fibonacci, knapsack (0/1 and unbounded), longest common subsequence, edit distance, matrix chain multiplication, coin change, and longest increasing subsequence are fundamental DP problems that demonstrate different optimization techniques.' },
            { type: 'online', name: 'DP Problem Collection', description: 'Curated collection of dynamic programming problems organized by difficulty and pattern type.' },
            { type: 'text', name: 'DP on Trees and Graphs', content: 'Tree DP processes nodes bottom-up from leaves. Problems include tree diameter, maximum independent set, and tree path queries. DP on DAGs follows topological order. Bitmask DP handles subset problems in O(2^n * n).' },
            { type: 'attachment', name: 'Dynamic Programming Workbook' },
        ]},
        { title: 'Heaps and Priority Queues', description: 'Binary heaps, Fibonacci heaps, and priority queue applications.', units: [
            { type: 'text', name: 'Binary Heap Operations', content: 'A binary heap is a complete binary tree satisfying the heap property. Insert and extract-min/max run in O(log n). Build-heap runs in O(n) using bottom-up construction. Heaps are stored as arrays with parent at i/2 and children at 2i and 2i+1.' },
            { type: 'text', name: 'Applications of Priority Queues', content: 'Priority queues are used in Dijkstra\'s algorithm, Huffman coding, Prim\'s MST, job scheduling, and event-driven simulation. The median maintenance problem uses two heaps. K-way merge uses a min-heap of size k.' },
            { type: 'online', name: 'Heap Operations Visualizer', description: 'Interactive visualization of heap insert, extract, and heapify operations showing array and tree representations simultaneously.' },
            { type: 'text', name: 'Fibonacci and Binomial Heaps', content: 'Fibonacci heaps support decrease-key in O(1) amortized time, improving Dijkstra to O(V log V + E). Binomial heaps merge in O(log n). Both use lazy strategies that defer work to extract-min operations.' },
            { type: 'attachment', name: 'Heap Implementation Guide' },
        ]},
        { title: 'Graph Algorithms III: Minimum Spanning Trees', description: 'Kruskal and Prim algorithms for finding minimum spanning trees.', units: [
            { type: 'text', name: 'Kruskal\'s Algorithm', content: 'Kruskal\'s algorithm sorts edges by weight and adds them greedily if they don\'t form a cycle, using Union-Find for cycle detection. Runs in O(E log E). Produces a minimum spanning forest for disconnected graphs.' },
            { type: 'text', name: 'Prim\'s Algorithm', content: 'Prim\'s algorithm grows the MST from a starting vertex by always adding the cheapest edge to an unreached vertex. With a Fibonacci heap, it runs in O(E + V log V). Better than Kruskal for dense graphs.' },
            { type: 'online', name: 'MST Algorithm Comparison', description: 'Side-by-side comparison of Kruskal and Prim algorithms running on the same graph with step-by-step visualization.' },
            { type: 'text', name: 'Cut Property and MST Uniqueness', content: 'The cut property states that the lightest edge crossing any cut belongs to every MST. If all edge weights are distinct, the MST is unique. Boruvka\'s algorithm finds MST in O(E log V) using component merging.' },
            { type: 'attachment', name: 'MST Problem Set' },
        ]},
        { title: 'Divide and Conquer', description: 'Divide and conquer paradigm with applications beyond sorting.', units: [
            { type: 'text', name: 'Master Theorem', content: 'The Master Theorem solves recurrences of the form T(n) = aT(n/b) + f(n). Three cases compare f(n) with n^(log_b a). Case 1: polynomially smaller. Case 2: equal (with log factor). Case 3: polynomially larger. Covers most divide-and-conquer recurrences.' },
            { type: 'text', name: 'Closest Pair and Strassen', content: 'The closest pair problem finds the two nearest points in O(n log n) using divide and conquer with a strip-based merge step. Strassen\'s matrix multiplication achieves O(n^2.807) by reducing 8 recursive multiplications to 7.' },
            { type: 'online', name: 'Recurrence Relation Solver', description: 'Tool for solving recurrence relations using substitution, recursion tree, and Master Theorem methods.' },
            { type: 'text', name: 'Karatsuba Multiplication', content: 'Karatsuba multiplication computes the product of two n-digit numbers in O(n^1.585) by reducing three multiplications instead of four. This idea generalizes to Toom-Cook and FFT-based multiplication for even faster large number arithmetic.' },
            { type: 'attachment', name: 'Divide and Conquer Exercises' },
        ]},
        { title: 'String Algorithms', description: 'Pattern matching, string searching, and text processing algorithms.', units: [
            { type: 'text', name: 'KMP and Rabin-Karp', content: 'KMP (Knuth-Morris-Pratt) uses a failure function to avoid re-examining characters, achieving O(n+m) pattern matching. Rabin-Karp uses rolling hash functions for expected O(n+m) matching with O(nm) worst case.' },
            { type: 'text', name: 'Trie and Suffix Trees', content: 'Tries store strings character by character for O(m) lookup. Suffix trees store all suffixes of a text for O(m) pattern searching after O(n) construction. Suffix arrays are space-efficient alternatives to suffix trees.' },
            { type: 'online', name: 'String Matching Visualizer', description: 'Step-by-step visualization of KMP, Rabin-Karp, and Boyer-Moore string matching algorithms.' },
            { type: 'text', name: 'Edit Distance and LCS', content: 'Edit distance (Levenshtein distance) counts minimum insertions, deletions, and substitutions to transform one string into another using O(mn) DP. Longest Common Subsequence finds the longest sequence common to two strings.' },
            { type: 'attachment', name: 'String Algorithm Problems' },
        ]},
        { title: 'Greedy Algorithms', description: 'Greedy strategy, optimal substructure, and greedy choice property.', units: [
            { type: 'text', name: 'Greedy Choice Property', content: 'A greedy algorithm makes locally optimal choices hoping for a globally optimal solution. It works when the problem has greedy choice property (local optimum leads to global optimum) and optimal substructure.' },
            { type: 'text', name: 'Activity Selection and Huffman Coding', content: 'Activity Selection chooses the maximum number of non-overlapping activities by selecting earliest-finishing first. Huffman coding builds an optimal prefix-free code using a priority queue, assigning shorter codes to frequent symbols.' },
            { type: 'online', name: 'Greedy Algorithm Examples', description: 'Collection of greedy algorithm problems with proofs of correctness and counterexamples for incorrect greedy approaches.' },
            { type: 'text', name: 'Interval Scheduling and Coloring', content: 'Interval scheduling maximizes accepted requests. Interval coloring minimizes resources for all requests. The fractional knapsack uses greedy (value/weight ratio) while 0/1 knapsack requires DP.' },
            { type: 'attachment', name: 'Greedy Problems Worksheet' },
        ]},
        { title: 'Union-Find Data Structure', description: 'Disjoint set operations with union by rank and path compression.', units: [
            { type: 'text', name: 'Union-Find Operations', content: 'Union-Find (Disjoint Set Union) supports MakeSet, Find, and Union operations. Path compression flattens trees during Find. Union by rank attaches smaller trees under larger ones. Together they achieve nearly O(1) amortized per operation.' },
            { type: 'text', name: 'Applications of Union-Find', content: 'Union-Find is used in Kruskal\'s MST algorithm for cycle detection, connected components in dynamic graphs, image segmentation, equivalence class computation, and percolation problems.' },
            { type: 'online', name: 'Union-Find Visualization', description: 'Interactive visualization showing how Union-Find trees change with path compression and union by rank during a sequence of operations.' },
            { type: 'text', name: 'Weighted Quick Union Analysis', content: 'Without optimizations, Union-Find operations are O(n). Union by rank alone gives O(log n). Path compression alone gives amortized O(log n). Combined, the amortized cost is O(alpha(n)), the inverse Ackermann function, effectively constant.' },
            { type: 'attachment', name: 'Union-Find Implementation' },
        ]},
        { title: 'Network Flow Algorithms', description: 'Max flow, min cut, and bipartite matching using network flow.', units: [
            { type: 'text', name: 'Ford-Fulkerson Method', content: 'Ford-Fulkerson finds maximum flow by repeatedly finding augmenting paths in the residual graph. The max-flow min-cut theorem states that maximum flow equals minimum cut capacity. Edmonds-Karp uses BFS for O(VE^2) time.' },
            { type: 'text', name: 'Bipartite Matching', content: 'Maximum bipartite matching reduces to max flow by adding source and sink nodes. The Hungarian algorithm solves the assignment problem in O(n^3). Hopcroft-Karp finds maximum matching in O(E*sqrt(V)).' },
            { type: 'online', name: 'Network Flow Simulator', description: 'Interactive simulator for running Ford-Fulkerson and Edmonds-Karp algorithms on flow networks with adjustable capacities.' },
            { type: 'text', name: 'Applications of Network Flow', content: 'Network flow solves problems including maximum bipartite matching, edge-disjoint paths, circulation with demands, project selection, baseball elimination, and image segmentation. Many combinatorial problems reduce to max flow.' },
            { type: 'attachment', name: 'Network Flow Problems' },
        ]},
        { title: 'Computational Geometry', description: 'Convex hull, line intersection, and geometric algorithms.', units: [
            { type: 'text', name: 'Convex Hull Algorithms', content: 'The convex hull is the smallest convex polygon containing all points. Graham scan runs in O(n log n) using angular sorting. Jarvis march (gift wrapping) runs in O(nh). Chan\'s algorithm achieves optimal O(n log h) output-sensitive time.' },
            { type: 'text', name: 'Line Segment Intersection', content: 'The sweep line technique detects intersections by sweeping a vertical line left to right, maintaining active segments in a balanced BST. The Bentley-Ottmann algorithm finds all k intersections among n segments in O((n+k) log n) time.' },
            { type: 'online', name: 'Computational Geometry Demos', description: 'Interactive demonstrations of convex hull, Voronoi diagrams, Delaunay triangulation, and polygon triangulation algorithms.' },
            { type: 'text', name: 'Voronoi Diagrams and Delaunay Triangulation', content: 'Voronoi diagrams partition the plane into regions closest to each site. The dual is the Delaunay triangulation, which maximizes minimum angles. Fortune\'s algorithm constructs Voronoi diagrams in O(n log n) using a sweep line.' },
            { type: 'attachment', name: 'Geometry Problem Set' },
        ]},
        { title: 'NP-Completeness', description: 'Complexity classes, reductions, and NP-complete problems.', units: [
            { type: 'text', name: 'P, NP, and NP-Complete', content: 'P contains problems solvable in polynomial time. NP contains problems verifiable in polynomial time. NP-Complete problems are the hardest in NP: every NP problem reduces to them in polynomial time. P=NP is the biggest open question in CS.' },
            { type: 'text', name: 'Polynomial Reductions', content: 'A polynomial reduction from problem A to problem B transforms any instance of A into an instance of B in polynomial time. If B is in P, then A is in P. If A is NP-hard, then B is NP-hard. SAT, Vertex Cover, and Hamiltonian Cycle are classic NP-complete problems.' },
            { type: 'online', name: 'NP-Completeness Reference', description: 'Catalog of NP-complete problems with reduction chains from SAT, organized by problem domain (graph, set, logic, scheduling).' },
            { type: 'text', name: 'Approximation Algorithms', content: 'Since NP-complete problems likely have no polynomial exact solutions, approximation algorithms find near-optimal solutions with guaranteed bounds. 2-approximation for Vertex Cover, greedy O(log n) for Set Cover, and PTAS for Euclidean TSP.' },
            { type: 'attachment', name: 'NP-Completeness Proofs' },
        ]},
        { title: 'Randomized Algorithms', description: 'Probabilistic analysis, Las Vegas and Monte Carlo algorithms.', units: [
            { type: 'text', name: 'Randomized QuickSort', content: 'Randomized QuickSort selects a random pivot, achieving O(n log n) expected time regardless of input. The probability of worst-case O(n^2) is negligible. This eliminates adversarial inputs that degrade deterministic pivot selection.' },
            { type: 'text', name: 'Skip Lists', content: 'Skip lists are randomized data structures providing O(log n) expected time for search, insert, and delete. Each element is promoted to higher levels with probability 1/2. They are simpler to implement than balanced BSTs and used in Redis and LevelDB.' },
            { type: 'online', name: 'Randomized Algorithm Analysis', description: 'Tutorial on analyzing expected running times, tail bounds, and derandomization techniques for randomized algorithms.' },
            { type: 'text', name: 'Hashing and Random Sampling', content: 'Universal hashing families guarantee O(1) expected lookup. Reservoir sampling selects k items uniformly from a stream of unknown length. Randomized algorithms for median finding (QuickSelect) run in O(n) expected time.' },
            { type: 'attachment', name: 'Randomized Algorithms Exercises' },
        ]},
        { title: 'Advanced Data Structures', description: 'Segment trees, Fenwick trees, and other specialized structures.', units: [
            { type: 'text', name: 'Segment Trees', content: 'Segment trees support range queries (sum, min, max) and point updates in O(log n). Lazy propagation enables range updates in O(log n). Persistent segment trees allow querying historical versions. Used extensively in competitive programming.' },
            { type: 'text', name: 'Fenwick Trees (BIT)', content: 'Binary Indexed Trees (Fenwick trees) support prefix sum queries and point updates in O(log n) with O(n) space. Simpler to implement than segment trees. The key insight: each node stores the sum of a range determined by the lowest set bit.' },
            { type: 'online', name: 'Advanced Data Structure Library', description: 'Reference implementations of segment trees, Fenwick trees, splay trees, and treaps with detailed complexity analysis.' },
            { type: 'text', name: 'Balanced BSTs: Treaps and Splay Trees', content: 'Treaps combine BST and heap properties using random priorities for expected O(log n) operations. Splay trees use rotations to move accessed elements to the root, achieving O(log n) amortized and optimality for skewed access patterns.' },
            { type: 'attachment', name: 'Advanced DS Problem Set' },
        ]},
        { title: 'Linear Programming', description: 'LP formulations, simplex algorithm, and duality.', units: [
            { type: 'text', name: 'Linear Programming Basics', content: 'Linear programming optimizes a linear objective function subject to linear constraints. Standard form has maximize c^T x subject to Ax <= b, x >= 0. Many optimization problems (flow, matching, scheduling) can be formulated as LPs.' },
            { type: 'text', name: 'Simplex Algorithm', content: 'The simplex algorithm moves along vertices of the feasible polytope, improving the objective at each step. Despite exponential worst case, it runs efficiently in practice. Interior-point methods provide polynomial-time alternatives.' },
            { type: 'online', name: 'LP Solver Tool', description: 'Online tool for formulating and solving linear programming problems with graphical visualization of feasible regions.' },
            { type: 'text', name: 'LP Duality', content: 'Every LP has a dual LP. Strong duality: optimal primal = optimal dual. Complementary slackness connects primal and dual solutions. LP duality proves max-flow min-cut theorem and provides approximation algorithm bounds.' },
            { type: 'attachment', name: 'LP Formulation Exercises' },
        ]},
        { title: 'Algorithm Design Paradigms Review', description: 'Comparing and combining algorithmic design paradigms for problem solving.', units: [
            { type: 'text', name: 'Choosing the Right Paradigm', content: 'Brute force for small inputs. Greedy when local optimum leads to global optimum. Divide and conquer for independent subproblems. Dynamic programming for overlapping subproblems. Backtracking for constraint satisfaction. Recognize problem patterns to choose the paradigm.' },
            { type: 'text', name: 'Problem Reduction Techniques', content: 'Many problems can be solved by reducing them to known problems. Shortest path reduces to matrix multiplication. Bipartite matching reduces to max flow. Recognizing reductions saves implementation effort and leverages proven algorithms.' },
            { type: 'online', name: 'Algorithm Design Exercises', description: 'Practice problems requiring identification of the appropriate algorithm design paradigm and implementation.' },
            { type: 'text', name: 'Competitive Programming Strategies', content: 'Read the problem carefully. Identify the problem type and constraints. Choose the right data structure and algorithm. Implement cleanly. Test with edge cases. Time management: solve easy problems first, then medium, then hard.' },
            { type: 'attachment', name: 'Algorithm Design Cheat Sheet' },
        ]},
    ],
    exercises: {
        programming: [
            { title: 'Implement MergeSort', problemStatement: 'Implement MergeSort for an array of integers. Your implementation should be stable, use O(n) auxiliary space, and correctly handle empty arrays and single-element arrays.' },
            { title: 'Binary Search Variants', problemStatement: 'Implement three binary search variants: find exact match, find first occurrence, and find last occurrence of a target in a sorted array. Handle edge cases.' },
            { title: 'Build a Hash Map', problemStatement: 'Implement a hash map from scratch using chaining for collision resolution. Support put, get, remove, and resize operations. Use a good hash function distribution.' },
            { title: 'Graph BFS Shortest Path', problemStatement: 'Implement BFS to find the shortest path in an unweighted graph. Return the path as a list of vertices and handle disconnected components.' },
            { title: 'Dijkstra\'s Algorithm', problemStatement: 'Implement Dijkstra\'s algorithm using a min-priority queue. Handle graphs with non-negative weights and return both distances and paths.' },
            { title: 'Dynamic Programming: Knapsack', problemStatement: 'Solve the 0/1 Knapsack problem using dynamic programming. Implement both the value computation and item selection backtracking.' },
            { title: 'AVL Tree Implementation', problemStatement: 'Implement an AVL tree with insert, delete, and search operations. Maintain balance using left and right rotations after each modification.' },
            { title: 'Kruskal MST with Union-Find', problemStatement: 'Implement Kruskal\'s algorithm for finding the Minimum Spanning Tree. Use Union-Find with path compression and union by rank.' },
            { title: 'Huffman Encoding', problemStatement: 'Implement Huffman coding for text compression. Build the Huffman tree from character frequencies, generate codes, and encode/decode text.' },
            { title: 'KMP Pattern Matching', problemStatement: 'Implement the Knuth-Morris-Pratt string matching algorithm. Build the failure function and use it to find all occurrences of a pattern in a text.' },
            { title: 'Topological Sort', problemStatement: 'Implement topological sort for a directed acyclic graph using DFS. Detect cycles and throw an exception if the graph is not a DAG.' },
            { title: 'Red-Black Tree Insertion', problemStatement: 'Implement insertion into a Red-Black tree maintaining all five RB properties. Include the fixup procedure with rotations and recoloring.' },
            { title: 'Segment Tree Range Queries', problemStatement: 'Implement a segment tree supporting range sum queries and point updates. Include build, query, and update operations in O(log n).' },
            { title: 'Ford-Fulkerson Max Flow', problemStatement: 'Implement the Ford-Fulkerson algorithm for maximum flow using BFS (Edmonds-Karp). Build the residual graph and find augmenting paths.' },
            { title: 'QuickSelect for Kth Element', problemStatement: 'Implement the QuickSelect algorithm to find the kth smallest element in an unsorted array with O(n) expected time complexity.' },
            { title: 'Trie for Autocomplete', problemStatement: 'Implement a Trie data structure supporting insert, search, and prefix-based autocomplete. Return all words with a given prefix.' },
            { title: 'Bellman-Ford Negative Cycles', problemStatement: 'Implement Bellman-Ford algorithm for shortest paths with negative weights. Detect and report negative weight cycles.' },
            { title: 'LRU Cache Implementation', problemStatement: 'Implement an LRU (Least Recently Used) cache with O(1) get and put operations using a hash map and doubly linked list combination.' },
            { title: 'Convex Hull Graham Scan', problemStatement: 'Implement the Graham scan algorithm for computing the convex hull of a set of 2D points in O(n log n) time.' },
            { title: 'Edit Distance DP', problemStatement: 'Implement the edit distance (Levenshtein distance) algorithm using dynamic programming. Return both the minimum distance and the edit operations.' },
            { title: 'Implement a Priority Queue', problemStatement: 'Implement a min-priority queue using a binary heap stored in an array. Support insert, extractMin, decreaseKey, and peek operations.' },
            { title: 'DFS Cycle Detection', problemStatement: 'Implement cycle detection in directed and undirected graphs using DFS. Return the cycle if one exists.' },
            { title: 'Longest Common Subsequence', problemStatement: 'Find the longest common subsequence of two strings using dynamic programming. Return both the length and the actual subsequence.' },
            { title: 'Binary Heap Sort', problemStatement: 'Implement HeapSort by first building a max-heap in O(n) and then repeatedly extracting the maximum. Sort the array in-place.' },
            { title: 'Matrix Chain Multiplication', problemStatement: 'Solve the matrix chain multiplication problem using DP to find the optimal parenthesization that minimizes scalar multiplications.' },
            { title: 'Rabin-Karp String Search', problemStatement: 'Implement Rabin-Karp string matching using rolling hash. Handle hash collisions and find all occurrences of a pattern.' },
            { title: 'Prim\'s MST Algorithm', problemStatement: 'Implement Prim\'s algorithm for minimum spanning tree using a priority queue. Handle disconnected graphs by building a spanning forest.' },
            { title: 'Counting Sort Implementation', problemStatement: 'Implement Counting Sort for non-negative integers. Ensure stability and handle the range of input values efficiently.' },
            { title: 'Floyd-Warshall All Pairs', problemStatement: 'Implement Floyd-Warshall for all-pairs shortest paths. Detect negative cycles and reconstruct shortest paths between any two vertices.' },
            { title: 'Skip List Implementation', problemStatement: 'Implement a skip list with randomized promotion supporting search, insert, and delete operations in O(log n) expected time.' },
            { title: 'Fenwick Tree Prefix Sums', problemStatement: 'Implement a Fenwick tree (Binary Indexed Tree) for efficient prefix sum queries and point updates in O(log n) per operation.' },
            { title: 'Strongly Connected Components', problemStatement: 'Implement Tarjan\'s algorithm for finding all strongly connected components in a directed graph using a single DFS pass.' },
            { title: 'Interval Scheduling Greedy', problemStatement: 'Solve the interval scheduling problem using a greedy algorithm. Maximize the number of non-overlapping intervals selected.' },
            { title: 'Median of Two Sorted Arrays', problemStatement: 'Find the median of two sorted arrays in O(log(min(m,n))) time using binary search. Handle arrays of different lengths.' },
            { title: 'Bloom Filter Implementation', problemStatement: 'Implement a Bloom filter with configurable false positive rate. Support add and probabilistic contains operations with multiple hash functions.' },
            { title: 'A* Pathfinding', problemStatement: 'Implement the A* search algorithm for grid-based pathfinding. Use Manhattan distance as the heuristic and handle obstacles.' },
            { title: 'Disjoint Set Union', problemStatement: 'Implement Union-Find with path compression and union by rank. Test with a dynamic connectivity problem on a graph.' },
            { title: 'Radix Sort', problemStatement: 'Implement Radix Sort for sorting integers using Counting Sort as a stable subroutine. Handle both positive and negative numbers.' },
            { title: 'Suffix Array Construction', problemStatement: 'Construct a suffix array for a given string in O(n log n) time. Use it to find all occurrences of a pattern.' },
            { title: 'Maximum Subarray Kadane', problemStatement: 'Implement Kadane\'s algorithm for the maximum subarray sum problem. Return both the maximum sum and the subarray boundaries.' },
        ],
        text: [
            { title: 'Compare Sorting Algorithms', problemStatement: 'Compare QuickSort, MergeSort, and HeapSort. Discuss their time/space complexity, stability, cache performance, and practical use cases.' },
            { title: 'P vs NP Essay', problemStatement: 'Explain the P vs NP problem. Discuss its significance, known results, implications if P=NP or P!=NP, and current approaches.' },
            { title: 'Hash Table Collision Analysis', problemStatement: 'Analyze different collision resolution strategies for hash tables. Compare chaining, linear probing, and double hashing with examples.' },
            { title: 'Dynamic Programming vs Greedy', problemStatement: 'When should you use dynamic programming vs greedy algorithms? Provide examples of problems solvable by each and explain why.' },
            { title: 'Graph Algorithm Applications', problemStatement: 'Describe real-world applications of graph algorithms: social networks (BFS), GPS navigation (Dijkstra), network routing, and recommendation systems.' },
        ],
        modeling: [
            { title: 'BST Operations Diagram', problemStatement: 'Draw a class diagram for a Binary Search Tree implementation showing Node, BST, and Iterator classes with their methods and relationships.', diagramType: 'ClassDiagram' },
            { title: 'Graph Algorithm Flowchart', problemStatement: 'Create an activity diagram showing the steps of Dijkstra\'s algorithm including initialization, relaxation, and termination.', diagramType: 'ActivityDiagram' },
            { title: 'Hash Table Class Diagram', problemStatement: 'Design a class diagram for a hash table with separate chaining showing HashTable, Entry, LinkedList, and Iterator classes.', diagramType: 'ClassDiagram' },
            { title: 'Sorting Pipeline Activity', problemStatement: 'Model an activity diagram for a sorting pipeline that selects the best algorithm based on input size and characteristics.', diagramType: 'ActivityDiagram' },
            { title: 'Priority Queue Hierarchy', problemStatement: 'Create a class diagram showing the hierarchy of priority queue implementations: BinaryHeap, FibonacciHeap, and BinomialHeap.', diagramType: 'ClassDiagram' },
        ],
        quiz: [
            { title: 'Complexity Analysis Quiz', questions: [
                { type: 'multiple-choice', title: 'Big-O Notation', text: 'What is the time complexity of binary search?', points: 5, singleChoice: true, answerOptions: [{ text: 'O(log n)', isCorrect: true }, { text: 'O(n)', isCorrect: false }, { text: 'O(n log n)', isCorrect: false }, { text: 'O(1)', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Sorting Lower Bound', text: 'What is the lower bound for comparison-based sorting?', points: 5, singleChoice: true, answerOptions: [{ text: 'O(n log n)', isCorrect: true }, { text: 'O(n)', isCorrect: false }, { text: 'O(n^2)', isCorrect: false }, { text: 'O(log n)', isCorrect: false }] },
            ]},
            { title: 'Graph Algorithms Quiz', questions: [
                { type: 'multiple-choice', title: 'Shortest Path', text: 'Which algorithm finds shortest paths with negative edge weights?', points: 5, singleChoice: true, answerOptions: [{ text: 'Bellman-Ford', isCorrect: true }, { text: 'Dijkstra', isCorrect: false }, { text: 'BFS', isCorrect: false }, { text: 'Prim', isCorrect: false }] },
                { type: 'multiple-choice', title: 'MST Algorithm', text: 'Which data structure does Kruskal use for cycle detection?', points: 5, singleChoice: true, answerOptions: [{ text: 'Union-Find', isCorrect: true }, { text: 'Stack', isCorrect: false }, { text: 'Queue', isCorrect: false }, { text: 'Hash Map', isCorrect: false }] },
            ]},
            { title: 'Data Structures Quiz', questions: [
                { type: 'multiple-choice', title: 'AVL Trees', text: 'What is the maximum balance factor allowed in an AVL tree?', points: 5, singleChoice: true, answerOptions: [{ text: '1', isCorrect: true }, { text: '2', isCorrect: false }, { text: '0', isCorrect: false }, { text: '3', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Hash Table', text: 'What is the average time complexity of hash table lookup?', points: 5, singleChoice: true, answerOptions: [{ text: 'O(1)', isCorrect: true }, { text: 'O(n)', isCorrect: false }, { text: 'O(log n)', isCorrect: false }, { text: 'O(n^2)', isCorrect: false }] },
            ]},
        ],
        fileUpload: [
            { title: 'Algorithm Complexity Report', problemStatement: 'Upload a report comparing the empirical running times of QuickSort, MergeSort, and HeapSort on different input sizes and distributions.' },
            { title: 'Graph Algorithm Analysis', problemStatement: 'Upload a document analyzing the performance of Dijkstra vs Bellman-Ford on sparse and dense graphs with timing measurements.' },
        ],
    },
    faqs: [
        { title: 'What is the difference between O(n) and O(n^2)?', answer: 'O(n) means the algorithm\'s time grows linearly with input size. O(n^2) means it grows quadratically. For n=1000, an O(n) algorithm does ~1000 operations while O(n^2) does ~1,000,000. This difference matters greatly for large inputs.' },
        { title: 'When should I use a hash table vs a balanced BST?', answer: 'Use hash tables for O(1) average-case lookup when order doesn\'t matter. Use balanced BSTs when you need ordered operations (range queries, predecessor/successor, in-order traversal) with O(log n) guaranteed worst-case.' },
        { title: 'How do I identify if a problem can be solved with DP?', answer: 'Look for two properties: optimal substructure (optimal solution contains optimal sub-solutions) and overlapping subproblems (same subproblems solved multiple times). If recursion leads to repeated states, DP likely applies.' },
        { title: 'What is the difference between BFS and DFS?', answer: 'BFS explores level by level (breadth-first), finds shortest paths in unweighted graphs, uses a queue. DFS goes deep first, uses a stack/recursion, classifies edges, and is used for topological sort and cycle detection.' },
        { title: 'Why is QuickSort preferred over MergeSort in practice?', answer: 'QuickSort has better cache locality (in-place), lower constant factors, and O(1) extra space. MergeSort needs O(n) extra space. However, MergeSort is preferred for linked lists and when stability is required.' },
        { title: 'How do I choose between Kruskal and Prim for MST?', answer: 'Kruskal works well for sparse graphs (E << V^2) since it sorts edges. Prim with Fibonacci heap is better for dense graphs. Kruskal is simpler to implement; Prim integrates well with adjacency list representation.' },
        { title: 'What are the properties of a Red-Black tree?', answer: 'Five properties: (1) Every node is red or black. (2) Root is black. (3) All NIL leaves are black. (4) Red nodes have black children. (5) All paths from a node to NIL leaves have the same number of black nodes.' },
        { title: 'How does path compression work in Union-Find?', answer: 'During Find, path compression makes every node on the path point directly to the root. This flattens the tree structure, so subsequent Find operations are nearly O(1). Combined with union by rank, it achieves O(alpha(n)) amortized.' },
        { title: 'What is amortized analysis?', answer: 'Amortized analysis averages the cost of operations over a sequence rather than analyzing worst-case individually. Methods include aggregate, accounting, and potential. Example: dynamic array resizing is O(1) amortized per insertion despite occasional O(n) resizes.' },
        { title: 'How do I prove an algorithm is correct?', answer: 'Use mathematical induction, loop invariants, or structural induction. For loop invariants: establish the invariant before the loop, show it\'s maintained by each iteration, and show it implies the desired result upon termination.' },
        { title: 'When is a greedy algorithm guaranteed to be optimal?', answer: 'When the problem exhibits the greedy choice property (a locally optimal choice leads to a globally optimal solution) and optimal substructure. Prove optimality using exchange arguments or matroid theory.' },
        { title: 'What is the Master Theorem?', answer: 'The Master Theorem solves recurrences T(n) = aT(n/b) + f(n). Case 1: f(n) = O(n^(log_b(a)-e)) -> T(n) = O(n^log_b(a)). Case 2: f(n) = O(n^log_b(a)) -> T(n) = O(n^log_b(a) * log n). Case 3: f(n) = Omega(n^(log_b(a)+e)) -> T(n) = O(f(n)).' },
        { title: 'What is the difference between a tree and a graph?', answer: 'A tree is a connected acyclic graph with exactly n-1 edges for n vertices. Graphs can have cycles, may be disconnected, can be directed or undirected, and can have any number of edges. Every tree is a graph, but not vice versa.' },
        { title: 'How does Huffman coding achieve compression?', answer: 'Huffman coding assigns shorter codes to more frequent symbols and longer codes to less frequent ones. It builds an optimal prefix-free binary tree by repeatedly merging the two least frequent symbols. The result is provably optimal among prefix codes.' },
        { title: 'What is the significance of NP-completeness?', answer: 'If any NP-complete problem can be solved in polynomial time, then all NP problems can (P=NP). Since no polynomial algorithm is known for any NP-complete problem, proving a problem NP-complete suggests no efficient algorithm exists, guiding us toward approximation or heuristic approaches.' },
        { title: 'How do segment trees differ from Fenwick trees?', answer: 'Segment trees support arbitrary range queries (min, max, sum, GCD) and range updates with lazy propagation. Fenwick trees only support prefix-sum queries and point updates but use less memory and are simpler to implement. Use segment trees for more complex operations.' },
        { title: 'What is the time complexity of building a heap?', answer: 'Building a heap from an array is O(n), not O(n log n). The bottom-up siftDown approach processes n/2 nodes, with most near the bottom doing little work. The sum of work across all levels is bounded by O(n) using a geometric series argument.' },
        { title: 'How do I handle negative weights in shortest path problems?', answer: 'Dijkstra fails with negative weights. Use Bellman-Ford (single source, O(VE)) or Floyd-Warshall (all pairs, O(V^3)). If there are negative cycles, shortest paths are undefined (-infinity). Johnson\'s algorithm reweights edges for sparse graphs.' },
        { title: 'What is a Bloom filter used for?', answer: 'Bloom filters test set membership probabilistically with no false negatives. Used in databases (avoid unnecessary disk reads), web browsers (malicious URL checking), caches (prevent cache penetration), and spell checkers. They trade accuracy for extreme space efficiency.' },
        { title: 'How do I analyze recursive algorithms?', answer: 'Write the recurrence relation (e.g., T(n) = 2T(n/2) + n). Solve using the Master Theorem, recursion tree, or substitution method. For non-standard recurrences, use the Akra-Bazzi method or domain-specific techniques.' },
    ],
    channelMessages: [
        'Can someone explain why QuickSort has O(n^2) worst case but is still preferred in practice?',
        'I am confused about when to use BFS vs DFS for graph problems. Any rules of thumb?',
        'How do you determine the recurrence relation for a divide-and-conquer algorithm?',
        'My Dijkstra implementation returns wrong results for disconnected graphs. What am I missing?',
        'What is the intuition behind the potential method in amortized analysis?',
        'Can someone walk through an AVL tree rotation example? I keep getting the cases mixed up.',
        'How do I prove that the greedy algorithm for activity selection is optimal?',
        'Why does the knapsack problem require DP while the fractional version can be solved greedily?',
        'I am getting Time Limit Exceeded on the segment tree problem. Should I use lazy propagation?',
        'What is the difference between Tarjan\'s and Kosaraju\'s algorithm for SCCs?',
        'How do I reduce the 3-SAT problem to Vertex Cover for the NP-completeness proof?',
        'Can someone explain the Bellman-Ford relaxation step? Why do we need V-1 iterations?',
        'My hash map implementation has too many collisions. How do I choose a better hash function?',
        'What is the difference between a min-heap and a max-heap priority queue?',
        'How does the KMP failure function work? I do not understand the prefix-suffix table construction.',
    ],
};
