export default {
    topic: 'Cybersecurity',
    title: 'Foundations of Cybersecurity',
    shortNamePrefix: 'CYS',
    description: 'This course covers the fundamentals of cybersecurity including cryptography, network security, penetration testing, malware analysis, security protocols, and access control. Students learn to identify vulnerabilities, implement defensive measures, and understand the threat landscape of modern computing environments.',
    lectures: [
        {
            title: 'Symmetric Cryptography',
            description: 'Foundations of symmetric encryption algorithms, block ciphers, and modes of operation.',
            units: [
                { type: 'text', name: 'Block Ciphers and AES', content: 'The Advanced Encryption Standard (AES) operates on 128-bit blocks with key sizes of 128, 192, or 256 bits. It uses substitution-permutation networks across multiple rounds. Each round applies SubBytes, ShiftRows, MixColumns, and AddRoundKey transformations to achieve confusion and diffusion.' },
                { type: 'text', name: 'Modes of Operation', content: 'ECB encrypts blocks independently, revealing patterns in plaintext. CBC chains blocks using XOR with the previous ciphertext. CTR turns a block cipher into a stream cipher using a counter. GCM adds authenticated encryption with associated data (AEAD) for integrity protection.' },
                { type: 'online', name: 'NIST Cryptographic Standards', description: 'The NIST Special Publication 800-38A defines recommended modes of operation for symmetric block ciphers including ECB, CBC, CFB, OFB, and CTR.' },
                { type: 'text', name: 'Stream Ciphers and ChaCha20', content: 'Stream ciphers encrypt data one bit or byte at a time by XORing with a pseudorandom keystream. ChaCha20 is a modern stream cipher offering high performance on software platforms without hardware AES support. It is widely used in TLS 1.3 and WireGuard.' },
                { type: 'attachment', name: 'AES Round Visualization' },
            ],
        },
        {
            title: 'Asymmetric Cryptography and Key Exchange',
            description: 'Public-key cryptosystems, RSA, elliptic curve cryptography, and secure key exchange protocols.',
            units: [
                { type: 'text', name: 'RSA Algorithm', content: 'RSA is based on the difficulty of factoring large semiprimes. Key generation selects two large primes p and q, computes n = p*q and the totient, then chooses public exponent e and computes private exponent d. Security depends on key size; 2048 bits is the current minimum recommendation.' },
                { type: 'text', name: 'Elliptic Curve Cryptography', content: 'ECC provides equivalent security to RSA with smaller key sizes. A 256-bit ECC key offers comparable security to a 3072-bit RSA key. Operations are defined over points on an elliptic curve, with the discrete logarithm problem providing the security foundation.' },
                { type: 'online', name: 'Diffie-Hellman Key Exchange Tutorial', description: 'An interactive walkthrough of the Diffie-Hellman key exchange protocol demonstrating how two parties establish a shared secret over an insecure channel using modular exponentiation.' },
                { type: 'text', name: 'Digital Signatures and Certificates', content: 'Digital signatures use the signer\'s private key to create a verifiable proof of authenticity. X.509 certificates bind public keys to identities and are signed by Certificate Authorities. Certificate chains establish trust from root CAs to end-entity certificates.' },
                { type: 'attachment', name: 'Public Key Infrastructure Diagram' },
            ],
        },
        {
            title: 'Hash Functions and Message Authentication',
            description: 'Cryptographic hash functions, HMACs, and their role in ensuring data integrity and authentication.',
            units: [
                { type: 'text', name: 'Properties of Cryptographic Hash Functions', content: 'A cryptographic hash function must provide preimage resistance (cannot find input from output), second preimage resistance (cannot find another input with the same hash), and collision resistance (cannot find two inputs with the same hash). SHA-256 produces a 256-bit digest.' },
                { type: 'online', name: 'SHA-3 and Keccak', description: 'SHA-3 is based on the Keccak sponge construction, which absorbs input blocks and squeezes output. It provides an alternative to the Merkle-Damgard construction used by SHA-1 and SHA-2.' },
                { type: 'text', name: 'HMAC Construction', content: 'HMAC combines a hash function with a secret key to provide message authentication. HMAC-SHA256 computes H(K XOR opad || H(K XOR ipad || message)). It prevents length extension attacks that affect naive hash-based MACs.' },
                { type: 'text', name: 'Password Hashing', content: 'Passwords must be hashed with slow, salted algorithms like bcrypt, scrypt, or Argon2. Salts prevent rainbow table attacks. Key stretching with high iteration counts makes brute-force attacks computationally expensive. Argon2id is the current recommended standard.' },
                { type: 'attachment', name: 'Hash Function Comparison Table' },
            ],
        },
        {
            title: 'Network Security Fundamentals',
            description: 'Securing network communications, firewalls, intrusion detection systems, and network segmentation.',
            units: [
                { type: 'text', name: 'Firewalls and Packet Filtering', content: 'Packet-filtering firewalls inspect headers and apply rules based on IP addresses, ports, and protocols. Stateful firewalls track connection states to allow return traffic. Next-generation firewalls add application-layer inspection, intrusion prevention, and deep packet inspection.' },
                { type: 'text', name: 'Intrusion Detection and Prevention Systems', content: 'IDS monitors network traffic for suspicious activity and generates alerts. IPS can automatically block detected threats. Signature-based detection matches known attack patterns. Anomaly-based detection identifies deviations from normal behavior baselines.' },
                { type: 'online', name: 'Network Segmentation Best Practices', description: 'Guide to implementing network segmentation using VLANs, subnets, and micro-segmentation to limit lateral movement and contain breaches within isolated network zones.' },
                { type: 'text', name: 'VPN Technologies', content: 'IPsec VPNs operate at the network layer, providing tunnel and transport modes. SSL/TLS VPNs work at the application layer through web browsers. WireGuard is a modern, lightweight VPN protocol using state-of-the-art cryptography with minimal attack surface.' },
                { type: 'attachment', name: 'Network Defense Architecture Diagram' },
            ],
        },
        {
            title: 'Transport Layer Security',
            description: 'TLS protocol mechanics, certificate management, and securing web communications.',
            units: [
                { type: 'text', name: 'TLS 1.3 Handshake', content: 'TLS 1.3 reduces the handshake to one round trip. The client sends supported cipher suites and key shares. The server selects parameters and completes key exchange. Compared to TLS 1.2, it removes insecure algorithms, eliminates RSA key transport, and mandates perfect forward secrecy.' },
                { type: 'online', name: 'Certificate Transparency Logs', description: 'Certificate Transparency requires CAs to log all issued certificates to public append-only logs, enabling domain owners to detect misissued certificates and improving the accountability of the PKI ecosystem.' },
                { type: 'text', name: 'TLS Attacks and Mitigations', content: 'BEAST exploits CBC predictable IVs in TLS 1.0. POODLE downgrades to SSLv3. Heartbleed leaked server memory through an OpenSSL buffer over-read. ROBOT revived Bleichenbacher attacks on RSA. Mitigations include protocol version enforcement and disabling weak cipher suites.' },
                { type: 'text', name: 'Certificate Pinning and HSTS', content: 'Certificate pinning associates a host with its expected certificate or public key, preventing man-in-the-middle attacks using rogue certificates. HTTP Strict Transport Security (HSTS) forces browsers to use HTTPS, preventing protocol downgrade and cookie hijacking attacks.' },
                { type: 'attachment', name: 'TLS Configuration Checklist' },
            ],
        },
        {
            title: 'Web Application Security',
            description: 'Common web vulnerabilities, the OWASP Top 10, and defensive coding practices for web applications.',
            units: [
                { type: 'text', name: 'SQL Injection and Prevention', content: 'SQL injection inserts malicious SQL into application queries through unsanitized user input. Attackers can read, modify, or delete database contents. Prevention requires parameterized queries (prepared statements), input validation, least-privilege database accounts, and web application firewalls.' },
                { type: 'text', name: 'Cross-Site Scripting (XSS)', content: 'Stored XSS persists malicious scripts in the database. Reflected XSS includes scripts in URLs. DOM-based XSS manipulates the client-side DOM. Prevention includes output encoding, Content Security Policy headers, HTTPOnly cookies, and input sanitization.' },
                { type: 'online', name: 'OWASP Web Security Testing Guide', description: 'Comprehensive methodology for testing web application security covering authentication, session management, input validation, error handling, and cryptography testing procedures.' },
                { type: 'text', name: 'Cross-Site Request Forgery (CSRF)', content: 'CSRF tricks authenticated users into submitting unintended requests. An attacker embeds a forged request in an image tag or hidden form on a malicious site. Prevention uses anti-CSRF tokens, SameSite cookie attributes, and verifying the Origin header.' },
                { type: 'attachment', name: 'OWASP Top 10 Summary Sheet' },
            ],
        },
        {
            title: 'Penetration Testing Methodology',
            description: 'Structured approaches to penetration testing, reconnaissance, exploitation, and reporting.',
            units: [
                { type: 'text', name: 'Penetration Testing Phases', content: 'A penetration test follows five phases: reconnaissance (passive and active information gathering), scanning (port scanning, vulnerability scanning), exploitation (gaining access), post-exploitation (privilege escalation, lateral movement), and reporting (findings, risk ratings, remediation).' },
                { type: 'text', name: 'Reconnaissance and OSINT', content: 'Passive reconnaissance gathers information without touching the target: WHOIS lookups, DNS records, social media, job postings, and search engine dorking. Active reconnaissance directly probes the target with port scans, banner grabbing, and directory enumeration.' },
                { type: 'online', name: 'PTES Technical Guidelines', description: 'The Penetration Testing Execution Standard provides a comprehensive framework covering pre-engagement, intelligence gathering, threat modeling, vulnerability analysis, exploitation, post-exploitation, and reporting.' },
                { type: 'text', name: 'Vulnerability Scanning with Nmap and Nessus', content: 'Nmap discovers hosts and services through port scanning, OS fingerprinting, and script scanning. Nessus performs automated vulnerability assessments by comparing discovered services against a database of known vulnerabilities, misconfigurations, and compliance checks.' },
                { type: 'attachment', name: 'Penetration Test Report Template' },
            ],
        },
        {
            title: 'Exploitation Techniques',
            description: 'Buffer overflows, privilege escalation, and common exploitation frameworks and tools.',
            units: [
                { type: 'text', name: 'Buffer Overflow Attacks', content: 'Stack-based buffer overflows overwrite the return address to redirect execution. Heap overflows corrupt dynamic memory metadata. Mitigations include stack canaries, Address Space Layout Randomization (ASLR), Data Execution Prevention (DEP), and Control Flow Integrity (CFI).' },
                { type: 'online', name: 'Metasploit Framework Guide', description: 'Metasploit provides a modular framework for developing and executing exploit code. It includes payloads, encoders, auxiliary modules for scanning, and post-exploitation tools for privilege escalation and persistence.' },
                { type: 'text', name: 'Privilege Escalation Techniques', content: 'Linux privilege escalation exploits SUID binaries, misconfigured cron jobs, writable service paths, and kernel vulnerabilities. Windows techniques include unquoted service paths, DLL hijacking, token impersonation, and exploiting misconfigured Group Policy Objects.' },
                { type: 'text', name: 'Return-Oriented Programming', content: 'ROP bypasses DEP by chaining existing code snippets (gadgets) ending in return instructions. Attackers build arbitrary computation from gadgets found in loaded libraries. Modern mitigations include Control Flow Guard (CFG) and Intel CET shadow stacks.' },
                { type: 'attachment', name: 'Exploitation Lab Setup Guide' },
            ],
        },
        {
            title: 'Malware Analysis Fundamentals',
            description: 'Static and dynamic analysis techniques for understanding malicious software behavior.',
            units: [
                { type: 'text', name: 'Types of Malware', content: 'Viruses attach to host programs and spread when executed. Worms self-replicate across networks. Trojans disguise as legitimate software. Ransomware encrypts files and demands payment. Rootkits hide at the OS or firmware level. Advanced Persistent Threats combine multiple techniques for long-term access.' },
                { type: 'text', name: 'Static Analysis Techniques', content: 'Static analysis examines malware without execution. Techniques include file hashing for identification, string extraction for IOCs, PE header analysis for imports and sections, disassembly with IDA Pro or Ghidra, and YARA rules for pattern matching across malware families.' },
                { type: 'online', name: 'Dynamic Analysis with Sandboxes', description: 'Dynamic analysis executes malware in isolated sandbox environments like Cuckoo Sandbox or Any.Run to observe runtime behavior including file system changes, registry modifications, network communications, and process injection techniques.' },
                { type: 'text', name: 'Reverse Engineering with Ghidra', content: 'Ghidra is an open-source reverse engineering tool from the NSA. It provides a decompiler that converts assembly to pseudocode, cross-references for tracking data and code flow, and scripting capabilities for automating analysis tasks.' },
                { type: 'attachment', name: 'Malware Analysis Lab Environment Setup' },
            ],
        },
        {
            title: 'Access Control Models',
            description: 'Discretionary, mandatory, and role-based access control models and their implementation.',
            units: [
                { type: 'text', name: 'DAC and MAC Models', content: 'Discretionary Access Control (DAC) lets resource owners set permissions, as in Unix file permissions. Mandatory Access Control (MAC) uses system-enforced labels and clearance levels, as in SELinux. MAC prevents users from overriding security policy, making it suitable for high-security environments.' },
                { type: 'text', name: 'Role-Based Access Control (RBAC)', content: 'RBAC assigns permissions to roles rather than individual users. Users are assigned roles that grant the required permissions. Role hierarchies allow inheritance. Separation of duties prevents conflicts of interest by requiring multiple roles for sensitive operations.' },
                { type: 'online', name: 'Attribute-Based Access Control (ABAC)', description: 'ABAC evaluates access decisions based on attributes of the subject, resource, action, and environment. XACML provides a standard policy language for expressing complex access control rules beyond what RBAC can model.' },
                { type: 'text', name: 'Zero Trust Architecture', content: 'Zero Trust assumes no implicit trust based on network location. Every access request is authenticated, authorized, and encrypted. Key principles include least-privilege access, micro-segmentation, continuous verification, and assuming breach. Identity becomes the new perimeter.' },
                { type: 'attachment', name: 'Access Control Policy Template' },
            ],
        },
        {
            title: 'Authentication and Identity Management',
            description: 'Password security, multi-factor authentication, OAuth, and identity federation protocols.',
            units: [
                { type: 'text', name: 'Multi-Factor Authentication', content: 'MFA combines something you know (password), something you have (hardware token, phone), and something you are (biometrics). TOTP generates time-based one-time passwords. FIDO2/WebAuthn provides phishing-resistant authentication using public key cryptography with hardware authenticators.' },
                { type: 'text', name: 'OAuth 2.0 and OpenID Connect', content: 'OAuth 2.0 is an authorization framework that issues access tokens for delegated access. OpenID Connect adds an identity layer with ID tokens containing user claims. Authorization Code flow with PKCE is recommended for public clients. Refresh tokens provide long-lived sessions.' },
                { type: 'online', name: 'SAML and Identity Federation', description: 'Security Assertion Markup Language enables single sign-on across organizational boundaries. Identity providers issue assertions consumed by service providers, enabling federated authentication without sharing credentials.' },
                { type: 'text', name: 'Password Attacks and Defenses', content: 'Brute-force attacks try all combinations. Dictionary attacks use common passwords. Credential stuffing reuses leaked password databases. Defenses include rate limiting, account lockout, CAPTCHA, breached password checking, and passwordless authentication alternatives.' },
                { type: 'attachment', name: 'Authentication Flow Diagrams' },
            ],
        },
        {
            title: 'Security Operations and Incident Response',
            description: 'Security monitoring, SIEM systems, incident handling, and digital forensics fundamentals.',
            units: [
                { type: 'text', name: 'Security Information and Event Management', content: 'SIEM systems aggregate logs from network devices, servers, and applications. They correlate events to detect attack patterns, generate alerts, and support forensic investigation. Key features include log normalization, real-time alerting, dashboards, and compliance reporting.' },
                { type: 'online', name: 'NIST Incident Response Framework', description: 'NIST SP 800-61 defines an incident response lifecycle with four phases: preparation, detection and analysis, containment eradication and recovery, and post-incident activity including lessons learned and evidence preservation.' },
                { type: 'text', name: 'Digital Forensics Process', content: 'Digital forensics follows identification, preservation, collection, examination, analysis, and reporting phases. Chain of custody must be maintained for legal admissibility. Disk imaging with write blockers ensures evidence integrity. Timeline analysis reconstructs event sequences.' },
                { type: 'text', name: 'Threat Hunting and IOCs', content: 'Threat hunting proactively searches for undetected threats using hypotheses derived from threat intelligence. Indicators of Compromise (IOCs) include file hashes, IP addresses, domain names, and behavioral patterns. MITRE ATT&CK provides a knowledge base of adversary tactics and techniques.' },
                { type: 'attachment', name: 'Incident Response Playbook' },
            ],
        },
        {
            title: 'Wireless and Mobile Security',
            description: 'Securing wireless networks, mobile device management, and Bluetooth and IoT vulnerabilities.',
            units: [
                { type: 'text', name: 'Wi-Fi Security Protocols', content: 'WEP is broken due to weak RC4 key scheduling. WPA uses TKIP as a temporary fix. WPA2 uses AES-CCMP for confidentiality. WPA3 introduces Simultaneous Authentication of Equals (SAE) replacing the PSK four-way handshake, providing forward secrecy and resistance to offline dictionary attacks.' },
                { type: 'text', name: 'Mobile Device Security', content: 'Mobile threats include malicious apps, insecure data storage, insufficient transport layer security, and client-side injection. Mobile Device Management (MDM) enforces security policies. App sandboxing isolates applications. Certificate pinning prevents MITM attacks on mobile APIs.' },
                { type: 'online', name: 'Bluetooth and IoT Vulnerabilities', description: 'Bluetooth vulnerabilities include BlueBorne (remote code execution without pairing), KNOB (key negotiation downgrade), and BIAS (impersonation). IoT devices often have default credentials, unpatched firmware, and lack encryption.' },
                { type: 'text', name: 'Wireless Attack Techniques', content: 'Evil twin attacks create rogue access points mimicking legitimate networks. Deauthentication attacks disconnect clients to capture WPA handshakes. KRACK exploits WPA2 key reinstallation. Wardriving maps wireless networks for reconnaissance. Wireless IDS monitors for rogue APs.' },
                { type: 'attachment', name: 'Wireless Security Audit Checklist' },
            ],
        },
        {
            title: 'Cloud Security',
            description: 'Security challenges in cloud environments, shared responsibility models, and cloud-native security tools.',
            units: [
                { type: 'text', name: 'Shared Responsibility Model', content: 'In IaaS, the provider secures infrastructure while the customer secures OS, applications, and data. In PaaS, the provider also manages the OS and runtime. In SaaS, the provider handles nearly everything except user access and data classification. Understanding boundaries prevents security gaps.' },
                { type: 'text', name: 'Cloud Identity and Access Management', content: 'Cloud IAM policies follow least-privilege principles with resource-based and identity-based policies. Service accounts require credential rotation and scoping. Federated identity integrates on-premises directories. Conditional access policies enforce MFA and device compliance.' },
                { type: 'online', name: 'Cloud Security Alliance Best Practices', description: 'The CSA Cloud Controls Matrix provides a security controls framework covering 17 domains including application security, data security, encryption, identity management, and audit assurance for cloud environments.' },
                { type: 'text', name: 'Container and Kubernetes Security', content: 'Container images should be scanned for vulnerabilities and signed for integrity. Kubernetes RBAC controls API access. Network policies restrict pod communication. Pod security standards enforce privilege restrictions. Secrets management avoids storing credentials in environment variables.' },
                { type: 'attachment', name: 'Cloud Security Assessment Framework' },
            ],
        },
        {
            title: 'Cryptographic Protocols',
            description: 'Design and analysis of security protocols including key exchange, authentication, and secure communication.',
            units: [
                { type: 'text', name: 'Kerberos Authentication Protocol', content: 'Kerberos uses a Key Distribution Center with an Authentication Server and Ticket Granting Server. Users obtain Ticket Granting Tickets (TGTs) and then service tickets for specific resources. Timestamps prevent replay attacks. Kerberos provides mutual authentication and is the default protocol in Active Directory.' },
                { type: 'online', name: 'Signal Protocol and End-to-End Encryption', description: 'The Signal Protocol combines the Double Ratchet algorithm, X3DH key agreement, and prekeys to provide end-to-end encrypted messaging with forward secrecy and future secrecy. It is used by Signal, WhatsApp, and other messaging platforms.' },
                { type: 'text', name: 'Protocol Verification and Formal Methods', content: 'Formal verification uses mathematical models to prove protocol correctness. Tools like ProVerif and Tamarin Prover analyze protocols against attacker models. The Dolev-Yao model assumes the attacker controls the network but cannot break cryptographic primitives.' },
                { type: 'text', name: 'Key Management and Distribution', content: 'Key lifecycle includes generation, distribution, storage, rotation, and destruction. Hardware Security Modules (HSMs) protect keys in tamper-resistant hardware. Key escrow enables authorized recovery. Key agreement protocols like Station-to-Station add authentication to Diffie-Hellman.' },
                { type: 'attachment', name: 'Protocol Analysis Worksheet' },
            ],
        },
        {
            title: 'Security Risk Management',
            description: 'Risk assessment frameworks, threat modeling, and security governance for organizations.',
            units: [
                { type: 'text', name: 'Risk Assessment Methodologies', content: 'Quantitative risk assessment calculates Annual Loss Expectancy (ALE) as Single Loss Expectancy times Annual Rate of Occurrence. Qualitative assessment uses categories like High, Medium, and Low. FAIR (Factor Analysis of Information Risk) provides a structured quantitative framework for cybersecurity risk.' },
                { type: 'text', name: 'Threat Modeling with STRIDE and DREAD', content: 'STRIDE categorizes threats: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege. DREAD rates severity: Damage, Reproducibility, Exploitability, Affected users, Discoverability. Attack trees visualize multi-step attack paths.' },
                { type: 'online', name: 'NIST Cybersecurity Framework', description: 'The NIST CSF organizes security activities into five functions: Identify, Protect, Detect, Respond, and Recover. It provides implementation tiers and profiles for assessing and improving organizational cybersecurity posture.' },
                { type: 'text', name: 'Security Policies and Compliance', content: 'Security policies define acceptable use, data classification, incident response, and access control standards. Compliance frameworks include PCI DSS for payment cards, HIPAA for health data, SOC 2 for service providers, and GDPR for personal data in the EU.' },
                { type: 'attachment', name: 'Risk Assessment Matrix Template' },
            ],
        },
        {
            title: 'Network Protocol Attacks',
            description: 'Attacks against DNS, ARP, BGP, and other network protocols, along with detection and prevention.',
            units: [
                { type: 'text', name: 'DNS Attacks and DNSSEC', content: 'DNS cache poisoning injects forged records to redirect traffic. DNS tunneling exfiltrates data through DNS queries. DNS amplification uses open resolvers for DDoS. DNSSEC adds cryptographic signatures to DNS records, providing authenticity and integrity verification.' },
                { type: 'text', name: 'ARP Spoofing and Man-in-the-Middle', content: 'ARP spoofing sends forged ARP replies to associate the attacker\'s MAC with another IP. This enables man-in-the-middle attacks, session hijacking, and traffic interception. Defenses include Dynamic ARP Inspection, static ARP entries, and encrypted protocols.' },
                { type: 'online', name: 'BGP Hijacking and Route Security', description: 'BGP hijacking announces unauthorized IP prefixes to redirect internet traffic. Resource Public Key Infrastructure (RPKI) cryptographically validates route origin. BGPsec adds path validation to prevent route manipulation attacks.' },
                { type: 'text', name: 'Denial of Service Attacks', content: 'Volumetric DDoS floods bandwidth with amplified UDP traffic. Protocol attacks exhaust server resources with SYN floods or Slowloris. Application-layer attacks target specific services. Mitigations include rate limiting, CDN-based scrubbing, SYN cookies, and behavioral analysis.' },
                { type: 'attachment', name: 'Network Attack Detection Signatures' },
            ],
        },
        {
            title: 'Secure Software Development',
            description: 'Integrating security into the software development lifecycle with DevSecOps practices.',
            units: [
                { type: 'text', name: 'Secure SDLC and Shift-Left Security', content: 'Shift-left security integrates security early in development rather than as an afterthought. Security requirements are defined during design. Threat modeling identifies risks before coding. SAST tools analyze source code for vulnerabilities. DAST tools test running applications for exploitable flaws.' },
                { type: 'text', name: 'Input Validation and Output Encoding', content: 'Whitelist validation accepts only known-good input patterns. Blacklist validation rejects known-bad patterns but is less reliable. Context-aware output encoding prevents injection attacks: HTML encoding for web pages, URL encoding for query parameters, and parameterized queries for databases.' },
                { type: 'online', name: 'OWASP Secure Coding Practices', description: 'The OWASP Secure Coding Practices Quick Reference Guide provides a checklist covering input validation, output encoding, authentication, session management, access control, error handling, and cryptographic practices.' },
                { type: 'text', name: 'Dependency and Supply Chain Security', content: 'Software supply chain attacks compromise upstream dependencies. SolarWinds and Log4Shell demonstrated the impact. Mitigations include Software Bill of Materials (SBOM), dependency scanning, reproducible builds, signed releases, and pinning dependency versions.' },
                { type: 'attachment', name: 'Secure Code Review Checklist' },
            ],
        },
        {
            title: 'Ethical Hacking and Bug Bounties',
            description: 'Legal and ethical frameworks for security testing, responsible disclosure, and bug bounty programs.',
            units: [
                { type: 'text', name: 'Legal Framework for Penetration Testing', content: 'Penetration testing requires explicit written authorization defining scope, timeframes, and rules of engagement. The Computer Fraud and Abuse Act (CFAA) in the US and the Computer Misuse Act in the UK criminalize unauthorized access. Scope creep and out-of-scope testing carry legal risk.' },
                { type: 'online', name: 'Bug Bounty Platforms and Programs', description: 'Platforms like HackerOne and Bugcrowd connect security researchers with organizations offering rewards for finding vulnerabilities. Programs define scope, eligible vulnerability types, reward tiers, and safe harbor provisions for good-faith testing.' },
                { type: 'text', name: 'Responsible Disclosure Process', content: 'Responsible disclosure gives vendors a reasonable timeframe (typically 90 days) to fix vulnerabilities before public disclosure. The researcher reports the vulnerability privately, provides technical details, and coordinates a public advisory. CVE identifiers provide standardized vulnerability tracking.' },
                { type: 'text', name: 'Capture the Flag Competitions', content: 'CTF competitions develop security skills through challenges in categories like cryptography, web exploitation, binary exploitation, reverse engineering, and forensics. Jeopardy-style CTFs offer independent challenges. Attack-defense CTFs require teams to exploit opponents while defending their own services.' },
                { type: 'attachment', name: 'Penetration Testing Rules of Engagement Template' },
            ],
        },
        {
            title: 'Post-Quantum Cryptography',
            description: 'Quantum computing threats to current cryptography and post-quantum algorithm candidates.',
            units: [
                { type: 'text', name: 'Quantum Threats to Classical Cryptography', content: 'Shor\'s algorithm can factor large numbers and compute discrete logarithms in polynomial time on a quantum computer, breaking RSA, Diffie-Hellman, and ECC. Grover\'s algorithm halves the effective key length of symmetric ciphers, requiring doubling key sizes. Harvest-now-decrypt-later attacks motivate urgent migration.' },
                { type: 'text', name: 'Lattice-Based Cryptography', content: 'Lattice-based schemes like CRYSTALS-Kyber (key encapsulation) and CRYSTALS-Dilithium (digital signatures) are based on the hardness of the Learning With Errors problem. NIST selected Kyber as the primary post-quantum key exchange standard. Lattice schemes offer reasonable key sizes and performance.' },
                { type: 'online', name: 'NIST Post-Quantum Standardization', description: 'NIST completed its post-quantum cryptography standardization process, selecting algorithms for key encapsulation and digital signatures. The standards provide migration paths from classical to quantum-resistant cryptographic systems.' },
                { type: 'text', name: 'Hybrid Cryptographic Schemes', content: 'Hybrid schemes combine classical and post-quantum algorithms to maintain security during the transition. A TLS connection might use both X25519 and Kyber for key exchange. This approach ensures security even if one algorithm is broken, whether by classical or quantum attacks.' },
                { type: 'attachment', name: 'Post-Quantum Migration Roadmap' },
            ],
        },
    ],
    exercises: {
        programming: [
            { title: 'Implement AES Encryption', problemStatement: 'Implement AES-128 encryption in ECB mode from scratch. Create the key expansion, SubBytes, ShiftRows, MixColumns, and AddRoundKey operations. Verify your implementation against NIST test vectors.' },
            { title: 'Caesar Cipher Breaker', problemStatement: 'Write a program that breaks a Caesar cipher using frequency analysis. Analyze letter frequencies in the ciphertext and compare against expected English letter distributions to determine the shift key.' },
            { title: 'RSA Key Generation', problemStatement: 'Implement RSA key pair generation with configurable key sizes. Generate two large primes, compute n and the totient, select a public exponent, and derive the private exponent using the extended Euclidean algorithm.' },
            { title: 'Password Strength Checker', problemStatement: 'Build a password strength analyzer that evaluates entropy, checks against common password lists, detects keyboard patterns, and provides a strength score with improvement suggestions.' },
            { title: 'Port Scanner Implementation', problemStatement: 'Implement a TCP port scanner that performs connect scans on a target host. Support scanning port ranges, concurrent scanning with thread pools, service banner grabbing, and timeout handling.' },
            { title: 'Hash Cracker with Rainbow Tables', problemStatement: 'Build a hash cracking tool that generates and uses rainbow tables for MD5 hashes. Implement the reduction function, chain generation, and lookup algorithm. Compare performance against brute-force cracking.' },
            { title: 'Packet Sniffer', problemStatement: 'Create a network packet sniffer that captures and parses Ethernet frames, IP packets, and TCP/UDP segments. Display source and destination addresses, ports, protocol types, and payload summaries.' },
            { title: 'SQL Injection Scanner', problemStatement: 'Build an automated SQL injection detection tool that tests URL parameters with common injection payloads. Detect error-based, boolean-based, and time-based blind SQL injection vulnerabilities.' },
            { title: 'XSS Vulnerability Scanner', problemStatement: 'Implement a cross-site scripting scanner that crawls web pages, identifies input fields, tests reflection points with XSS payloads, and reports vulnerable parameters with proof-of-concept examples.' },
            { title: 'Implement Diffie-Hellman Key Exchange', problemStatement: 'Implement the Diffie-Hellman key exchange protocol with safe prime generation. Simulate two parties exchanging public values and deriving a shared secret. Add verification that both parties compute the same key.' },
            { title: 'HMAC Implementation', problemStatement: 'Implement HMAC-SHA256 from scratch following RFC 2104. Handle key padding, inner and outer hash computations, and verify your output against known test vectors from the RFC.' },
            { title: 'Firewall Rule Engine', problemStatement: 'Build a packet-filtering firewall simulator that processes network packets against an ordered rule set. Support rules based on source/destination IP, port ranges, protocols, and actions (allow/deny/log).' },
            { title: 'Certificate Chain Validator', problemStatement: 'Implement an X.509 certificate chain validation tool. Parse certificates, verify digital signatures along the chain, check expiration dates, validate key usage extensions, and detect self-signed certificates.' },
            { title: 'Brute Force Login Detector', problemStatement: 'Create a log analysis tool that detects brute-force login attempts by analyzing authentication logs. Identify suspicious patterns like multiple failed attempts, credential stuffing, and distributed attacks.' },
            { title: 'Encryption File Vault', problemStatement: 'Build a file encryption tool that encrypts files using AES-256-GCM. Implement key derivation from a password using Argon2, secure key storage, file integrity verification, and secure deletion of plaintext.' },
            { title: 'Network Traffic Analyzer', problemStatement: 'Develop a tool that reads PCAP files and generates traffic analysis reports. Identify top talkers, protocol distribution, suspicious connections, potential data exfiltration, and DNS query anomalies.' },
            { title: 'TOTP Authenticator', problemStatement: 'Implement a Time-based One-Time Password (TOTP) generator and validator following RFC 6238. Support configurable time steps, digits, and hash algorithms. Generate QR codes for authenticator app enrollment.' },
            { title: 'Steganography Tool', problemStatement: 'Build a tool that hides secret messages within PNG images using LSB steganography. Implement both encoding and decoding. Add optional encryption of the hidden message before embedding.' },
            { title: 'Vulnerability Report Parser', problemStatement: 'Create a tool that parses vulnerability scan reports in multiple formats (CSV, JSON, XML), normalizes findings, calculates CVSS scores, prioritizes remediation, and generates an executive summary.' },
            { title: 'Access Control System', problemStatement: 'Implement a role-based access control system with users, roles, and permissions. Support role hierarchies, separation of duties constraints, and audit logging of all access decisions.' },
            { title: 'Secure Chat Application', problemStatement: 'Build a client-server chat application with end-to-end encryption using the Double Ratchet algorithm. Implement key exchange, message encryption and decryption, and forward secrecy for past messages.' },
            { title: 'Log Anomaly Detector', problemStatement: 'Develop a log analysis tool that establishes baseline behavior patterns and detects anomalies. Use statistical methods to identify unusual login times, access patterns, and data transfer volumes.' },
            { title: 'DNS Resolver with DNSSEC Validation', problemStatement: 'Implement a DNS resolver that queries DNS servers and validates DNSSEC signatures. Verify the chain of trust from the root zone to the queried domain and report validation failures.' },
            { title: 'Secure File Transfer Protocol', problemStatement: 'Build a secure file transfer application using TLS sockets. Implement mutual authentication with client certificates, file integrity verification with SHA-256 checksums, and resume support for interrupted transfers.' },
            { title: 'Intrusion Detection Rule Engine', problemStatement: 'Create a signature-based intrusion detection engine that matches network traffic against Snort-compatible rules. Support content matching, flow direction, threshold-based alerting, and IP address grouping.' },
            { title: 'OAuth 2.0 Authorization Server', problemStatement: 'Implement an OAuth 2.0 authorization server supporting the Authorization Code flow with PKCE. Issue access tokens and refresh tokens, validate scopes, and handle token revocation.' },
            { title: 'Malware Signature Generator', problemStatement: 'Build a tool that analyzes a set of malware samples, extracts common byte sequences, and generates YARA rules for detection. Minimize false positives by testing against a clean file corpus.' },
            { title: 'Buffer Overflow Exploit Lab', problemStatement: 'Write an exploit for a provided vulnerable C program with a stack-based buffer overflow. Craft shellcode, calculate offsets, handle null bytes, and demonstrate code execution with a reverse shell payload.' },
            { title: 'Web Application Firewall', problemStatement: 'Implement a basic web application firewall that inspects HTTP requests for SQL injection, XSS, path traversal, and command injection patterns. Support configurable rules, whitelisting, and request logging.' },
            { title: 'Keylogger Detector', problemStatement: 'Create a tool that detects keylogger activity by monitoring for suspicious keyboard hooks, unusual process behavior, keystroke interception patterns, and unauthorized screen capture processes.' },
            { title: 'Digital Forensics Image Analyzer', problemStatement: 'Build a tool that analyzes disk images to extract deleted files, recover file fragments using carving techniques, build file system timelines, and identify suspicious artifacts.' },
            { title: 'Blockchain-Based Audit Log', problemStatement: 'Implement a tamper-evident audit log using a hash chain structure. Each log entry includes a hash of the previous entry, ensuring integrity. Provide verification and tampering detection capabilities.' },
            { title: 'Encrypted Password Manager', problemStatement: 'Build a command-line password manager that stores credentials encrypted with AES-256-GCM. Derive the master key with Argon2, support password generation, clipboard integration, and auto-lock after inactivity.' },
            { title: 'Network Honeypot', problemStatement: 'Create a low-interaction honeypot that simulates common services (SSH, HTTP, FTP). Log connection attempts, capture credentials, record commands, and generate alerts for suspicious activity.' },
            { title: 'Certificate Authority Simulator', problemStatement: 'Implement a simple Certificate Authority that generates root and intermediate certificates, signs certificate signing requests, manages revocation lists, and validates certificate chains.' },
            { title: 'Phishing Email Detector', problemStatement: 'Build a tool that analyzes emails for phishing indicators: suspicious URLs, domain spoofing, urgency language patterns, header anomalies, and SPF/DKIM/DMARC validation failures.' },
            { title: 'Secure API Gateway', problemStatement: 'Implement an API gateway that enforces authentication, rate limiting, input validation, request signing, and audit logging. Support JWT validation, API key management, and IP-based access control.' },
            { title: 'Entropy Analyzer', problemStatement: 'Create a tool that calculates Shannon entropy of files and data streams to detect encrypted or compressed content, packed executables, and hidden data within seemingly normal files.' },
            { title: 'Two-Factor Authentication System', problemStatement: 'Implement a complete 2FA system supporting TOTP, SMS backup codes, and recovery keys. Include enrollment, verification, backup code generation, and account recovery workflows.' },
            { title: 'Side-Channel Attack Simulator', problemStatement: 'Demonstrate a timing side-channel attack against a naive string comparison function used for password verification. Measure response time differences and recover the password character by character.' },
        ],
        text: [
            { title: 'Analyze the SolarWinds Supply Chain Attack', problemStatement: 'Write a detailed analysis of the SolarWinds supply chain attack. Discuss the attack vector, the scope of compromise, detection timeline, attribution, and lessons learned for software supply chain security.' },
            { title: 'Compare Symmetric and Asymmetric Cryptography', problemStatement: 'Compare symmetric and asymmetric cryptography in terms of performance, key management, use cases, and security guarantees. Discuss why modern systems use hybrid approaches combining both types.' },
            { title: 'Zero Trust Architecture Assessment', problemStatement: 'Evaluate the Zero Trust security model compared to traditional perimeter-based security. Discuss implementation challenges, required technologies, organizational changes, and scenarios where each approach is more appropriate.' },
            { title: 'Ethics of Offensive Security Research', problemStatement: 'Discuss the ethical boundaries of offensive security research. Address responsible disclosure, the legality of vulnerability research, dual-use tools, and the balance between security improvement and potential harm.' },
            { title: 'Post-Quantum Cryptography Migration', problemStatement: 'Analyze the challenges of migrating current cryptographic infrastructure to post-quantum algorithms. Discuss timeline urgency, backward compatibility, performance impacts, and recommended migration strategies.' },
        ],
        modeling: [
            { title: 'Network Security Architecture', problemStatement: 'Create a class diagram modeling a network security architecture including Firewall, IDS, VPN Gateway, DMZ, SIEM, and their relationships to network zones and security policies.', diagramType: 'ClassDiagram' },
            { title: 'Incident Response Workflow', problemStatement: 'Model the incident response process as an activity diagram covering detection, triage, containment, eradication, recovery, and lessons learned with decision points for escalation.', diagramType: 'ActivityDiagram' },
            { title: 'Authentication System Design', problemStatement: 'Create a class diagram for a multi-factor authentication system showing User, Credential, AuthenticationProvider, Token, Session, and various factor types with their relationships.', diagramType: 'ClassDiagram' },
            { title: 'Penetration Test Workflow', problemStatement: 'Model the penetration testing lifecycle as an activity diagram including scope definition, reconnaissance, vulnerability scanning, exploitation, reporting, and remediation verification.', diagramType: 'ActivityDiagram' },
            { title: 'Access Control Model', problemStatement: 'Design a class diagram for an RBAC system showing User, Role, Permission, Resource, Policy, and AuditLog entities with role hierarchies and separation of duty constraints.', diagramType: 'ClassDiagram' },
        ],
        quiz: [
            { title: 'Cryptography Fundamentals Quiz', questions: [
                { type: 'multiple-choice', title: 'AES Key Sizes', text: 'Which of the following are valid AES key sizes?', points: 5, singleChoice: false, answerOptions: [{ text: '128 bits', isCorrect: true }, { text: '192 bits', isCorrect: true }, { text: '256 bits', isCorrect: true }, { text: '512 bits', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Asymmetric Cryptography', text: 'What mathematical problem is the security of RSA based on?', points: 5, singleChoice: true, answerOptions: [{ text: 'Integer factorization', isCorrect: true }, { text: 'Discrete logarithm', isCorrect: false }, { text: 'Elliptic curve point multiplication', isCorrect: false }, { text: 'Hash collision finding', isCorrect: false }] },
            ]},
            { title: 'Network Security Quiz', questions: [
                { type: 'multiple-choice', title: 'Firewall Types', text: 'Which firewall type inspects traffic at the application layer?', points: 5, singleChoice: true, answerOptions: [{ text: 'Next-generation firewall', isCorrect: true }, { text: 'Packet-filtering firewall', isCorrect: false }, { text: 'Circuit-level gateway', isCorrect: false }, { text: 'NAT firewall', isCorrect: false }] },
                { type: 'multiple-choice', title: 'TLS Version', text: 'How many round trips does the TLS 1.3 handshake require?', points: 5, singleChoice: true, answerOptions: [{ text: 'One', isCorrect: true }, { text: 'Two', isCorrect: false }, { text: 'Three', isCorrect: false }, { text: 'Zero', isCorrect: false }] },
            ]},
            { title: 'Web Security Quiz', questions: [
                { type: 'multiple-choice', title: 'XSS Prevention', text: 'Which HTTP header helps prevent cross-site scripting attacks?', points: 5, singleChoice: true, answerOptions: [{ text: 'Content-Security-Policy', isCorrect: true }, { text: 'X-Frame-Options', isCorrect: false }, { text: 'Cache-Control', isCorrect: false }, { text: 'Accept-Encoding', isCorrect: false }] },
                { type: 'multiple-choice', title: 'SQL Injection Defense', text: 'What is the most effective defense against SQL injection?', points: 5, singleChoice: true, answerOptions: [{ text: 'Parameterized queries', isCorrect: true }, { text: 'Input length validation', isCorrect: false }, { text: 'Web application firewall', isCorrect: false }, { text: 'Error message suppression', isCorrect: false }] },
            ]},
        ],
        fileUpload: [
            { title: 'Security Audit Report', problemStatement: 'Upload a security audit report for a fictional web application. Include an executive summary, methodology, findings categorized by severity (Critical, High, Medium, Low), evidence screenshots, and remediation recommendations with priority rankings.' },
            { title: 'Incident Response Plan', problemStatement: 'Upload an incident response plan document for an organization. Include roles and responsibilities, communication procedures, incident classification criteria, response procedures for common incident types, and post-incident review templates.' },
        ],
    },
    faqs: [
        { title: 'What is the difference between encryption and hashing?', answer: 'Encryption is reversible using a key and protects data confidentiality. Hashing is a one-way function that produces a fixed-size digest and is used for integrity verification and password storage. You can decrypt encrypted data, but you cannot reverse a hash to recover the original input.' },
        { title: 'Why is MD5 considered insecure?', answer: 'MD5 is vulnerable to collision attacks where two different inputs produce the same hash. Practical collision attacks were demonstrated in 2004. MD5 should not be used for security-sensitive applications like digital signatures or password hashing. Use SHA-256 or SHA-3 instead.' },
        { title: 'What is the difference between symmetric and asymmetric encryption?', answer: 'Symmetric encryption uses the same key for encryption and decryption (e.g., AES), offering high performance. Asymmetric encryption uses a public-private key pair (e.g., RSA), enabling key exchange without shared secrets. Hybrid systems use asymmetric crypto to exchange a symmetric session key.' },
        { title: 'How does a VPN protect network traffic?', answer: 'A VPN creates an encrypted tunnel between the client and VPN server. All traffic is encapsulated and encrypted, hiding the content and destination from network observers. The VPN server decrypts and forwards traffic, making it appear to originate from the VPN server\'s IP address.' },
        { title: 'What is the principle of least privilege?', answer: 'Least privilege means granting users and processes only the minimum permissions necessary to perform their tasks. This limits the damage from compromised accounts, reduces attack surface, and prevents accidental misuse. Permissions should be reviewed and revoked when no longer needed.' },
        { title: 'What is a man-in-the-middle attack?', answer: 'A MITM attack intercepts communication between two parties by positioning the attacker between them. The attacker can read, modify, or inject messages while both parties believe they are communicating directly. TLS with certificate validation prevents MITM attacks.' },
        { title: 'How does multi-factor authentication improve security?', answer: 'MFA requires multiple verification factors from different categories: knowledge (password), possession (phone or token), and inherence (biometrics). Even if one factor is compromised, the attacker cannot access the account without the others. TOTP and FIDO2 are common second factors.' },
        { title: 'What is a buffer overflow vulnerability?', answer: 'A buffer overflow occurs when a program writes data beyond an allocated memory buffer, overwriting adjacent memory. Attackers can overwrite return addresses to execute arbitrary code. Mitigations include stack canaries, ASLR, DEP/NX bits, and using memory-safe languages.' },
        { title: 'What is the difference between IDS and IPS?', answer: 'An Intrusion Detection System (IDS) monitors traffic and generates alerts for suspicious activity but does not block it. An Intrusion Prevention System (IPS) can automatically block or drop malicious traffic. IDS is passive monitoring; IPS is active prevention.' },
        { title: 'How does HTTPS protect web communication?', answer: 'HTTPS uses TLS to encrypt HTTP traffic between browser and server. The TLS handshake authenticates the server using certificates, establishes an encrypted session with forward secrecy, and protects data integrity with MACs. This prevents eavesdropping, tampering, and impersonation.' },
        { title: 'What is social engineering in cybersecurity?', answer: 'Social engineering manipulates people into divulging confidential information or performing actions that compromise security. Techniques include phishing emails, pretexting, baiting, tailgating, and vishing. Defense requires security awareness training, verification procedures, and a culture of healthy skepticism.' },
        { title: 'What is a zero-day vulnerability?', answer: 'A zero-day vulnerability is a security flaw unknown to the vendor, meaning no patch exists. Zero-day exploits target these vulnerabilities before they are discovered and fixed. Detection relies on behavioral analysis and anomaly detection since no signatures exist.' },
        { title: 'How should passwords be stored securely?', answer: 'Passwords must never be stored in plaintext. Use adaptive hashing algorithms like bcrypt, scrypt, or Argon2id with unique per-user salts. These algorithms are deliberately slow to resist brute-force attacks. The iteration count should be tuned to take at least 100ms per hash.' },
        { title: 'What is the MITRE ATT&CK framework?', answer: 'MITRE ATT&CK is a knowledge base of adversary tactics, techniques, and procedures (TTPs) based on real-world observations. It covers techniques across the attack lifecycle from initial access to exfiltration. Security teams use it for threat modeling, detection engineering, and red team exercises.' },
        { title: 'What is certificate pinning and why is it used?', answer: 'Certificate pinning associates a host with its expected certificate or public key, preventing attacks using fraudulently issued certificates. The application rejects connections if the server presents a different certificate, even if it is signed by a trusted CA. It is commonly used in mobile apps.' },
        { title: 'How does ransomware typically work?', answer: 'Ransomware encrypts victim files using strong encryption and demands payment for the decryption key. It often spreads through phishing emails or exploiting vulnerabilities. Modern ransomware uses double extortion by also stealing data. Prevention includes backups, patching, network segmentation, and email filtering.' },
        { title: 'What is the difference between penetration testing and vulnerability scanning?', answer: 'Vulnerability scanning uses automated tools to identify known vulnerabilities without exploiting them. Penetration testing goes further by actively attempting to exploit vulnerabilities, chain findings, and demonstrate real-world impact. Pen testing requires skilled testers and produces more actionable results.' },
        { title: 'What is DNSSEC and why is it important?', answer: 'DNSSEC adds cryptographic signatures to DNS records, allowing resolvers to verify that responses have not been tampered with. Without DNSSEC, attackers can poison DNS caches to redirect users to malicious sites. DNSSEC provides authentication and integrity but not confidentiality for DNS queries.' },
        { title: 'How does a firewall differ from an antivirus?', answer: 'Firewalls control network traffic flow based on rules about ports, protocols, and addresses. Antivirus software detects and removes malicious software on endpoints using signatures and behavioral analysis. They complement each other: firewalls protect the network perimeter while antivirus protects individual hosts.' },
        { title: 'What is the CIA triad in information security?', answer: 'The CIA triad represents the three fundamental goals of information security: Confidentiality (preventing unauthorized disclosure), Integrity (preventing unauthorized modification), and Availability (ensuring authorized access when needed). All security controls map to one or more of these properties.' },
    ],
    channelMessages: [
        'Can someone explain the difference between ECB and CBC modes of operation? Why is ECB considered insecure?',
        'I am having trouble with the RSA key generation exercise. How do I efficiently generate large prime numbers?',
        'What tools do you recommend for practicing penetration testing in a safe lab environment?',
        'How does TLS 1.3 improve security compared to TLS 1.2? Is it just about removing weak ciphers?',
        'Can someone help me understand how ARP spoofing works? I cannot get the man-in-the-middle lab to work.',
        'What is the difference between a vulnerability scan and a penetration test in practice?',
        'I am confused about the difference between authentication and authorization. Are they not the same thing?',
        'Does anyone have resources for learning reverse engineering with Ghidra? The interface is overwhelming.',
        'How do you determine the appropriate key size for AES in a real-world application?',
        'Can someone explain why we need both encryption and message authentication? Is encryption not enough?',
        'What is the best approach for implementing rate limiting to prevent brute-force attacks?',
        'I found an XSS vulnerability in the lab application but I am not sure how to write the report. Any tips?',
        'How does certificate transparency help prevent fraudulent certificates from being used?',
        'What is the practical difference between RBAC and ABAC for access control in web applications?',
        'Can someone explain how the Double Ratchet algorithm provides forward secrecy in messaging apps?',
    ],
};
