export default {
    topic: 'Database Systems',
    title: 'Database Systems and Data Management',
    shortNamePrefix: 'DBS',
    description: 'This course covers relational database design, SQL programming, query optimization, transaction management, and NoSQL systems. Students learn normalization theory, indexing strategies, ACID properties, and distributed database architectures for building data-intensive applications.',
    lectures: [
        { title: 'Relational Data Model', description: 'Relations, tuples, attributes, keys, and relational algebra operations.', units: [
            { type: 'text', name: 'Relations and Keys', content: 'A relation is a set of tuples over a schema of attributes. A superkey uniquely identifies tuples. A candidate key is a minimal superkey. A primary key is the chosen candidate key. Foreign keys reference primary keys of other relations to establish relationships.' },
            { type: 'text', name: 'Relational Algebra', content: 'Relational algebra provides operators for querying: selection (sigma) filters rows, projection (pi) selects columns, join combines tables, union merges compatible relations, difference removes common tuples, and rename (rho) changes attribute names.' },
            { type: 'online', name: 'Relational Algebra Visualizer', description: 'Interactive tool for building and executing relational algebra expressions with visual representations of intermediate results.' },
            { type: 'text', name: 'Entity-Relationship Model', content: 'ER diagrams model entities (rectangles), attributes (ovals), and relationships (diamonds). Cardinalities (1:1, 1:N, M:N) specify relationship participation. Weak entities depend on strong entities. ISA hierarchies model specialization and generalization.' },
            { type: 'attachment', name: 'ER Diagram Examples' },
        ]},
        { title: 'SQL Fundamentals', description: 'Data definition, manipulation, and query language syntax.', units: [
            { type: 'text', name: 'DDL: CREATE, ALTER, DROP', content: 'CREATE TABLE defines schema with columns, data types, and constraints (PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, CHECK). ALTER TABLE modifies existing schemas. DROP TABLE removes tables. Data types include INTEGER, VARCHAR, DATE, DECIMAL, BOOLEAN.' },
            { type: 'text', name: 'DML: SELECT, INSERT, UPDATE, DELETE', content: 'SELECT retrieves data with WHERE filtering, ORDER BY sorting, GROUP BY aggregation, and HAVING post-aggregation filtering. INSERT adds rows. UPDATE modifies existing rows. DELETE removes rows. Subqueries enable nested queries.' },
            { type: 'online', name: 'SQL Practice Platform', description: 'Interactive SQL exercises with an embedded database for practicing queries from basic to advanced levels.' },
            { type: 'text', name: 'Joins and Set Operations', content: 'INNER JOIN returns matching rows. LEFT/RIGHT OUTER JOIN includes unmatched rows. FULL OUTER JOIN combines both. CROSS JOIN produces Cartesian product. NATURAL JOIN matches on common columns. UNION, INTERSECT, EXCEPT perform set operations.' },
            { type: 'attachment', name: 'SQL Cheat Sheet' },
        ]},
        { title: 'Database Normalization', description: 'Normal forms, functional dependencies, and decomposition algorithms.', units: [
            { type: 'text', name: 'Functional Dependencies', content: 'A functional dependency X -> Y means X uniquely determines Y. Armstrong\'s axioms (reflexivity, augmentation, transitivity) derive all FDs from a given set. The closure X+ of attributes X under a set of FDs determines all attributes functionally determined by X.' },
            { type: 'text', name: 'Normal Forms: 1NF through BCNF', content: '1NF: atomic values only. 2NF: no partial dependencies on candidate keys. 3NF: no transitive dependencies. BCNF: every determinant is a superkey. Higher normal forms reduce redundancy. Decomposition should be lossless-join and dependency-preserving.' },
            { type: 'online', name: 'Normalization Calculator', description: 'Tool that computes functional dependency closures, candidate keys, and determines the highest normal form of a relation.' },
            { type: 'text', name: 'Decomposition Algorithms', content: 'BCNF decomposition repeatedly splits relations with violating FDs, guaranteeing lossless join but possibly losing dependency preservation. 3NF synthesis uses the minimal cover and creates a relation for each FD, preserving dependencies and lossless join.' },
            { type: 'attachment', name: 'Normalization Exercises' },
        ]},
        { title: 'Indexing and Query Processing', description: 'B-trees, hash indexes, and query optimization strategies.', units: [
            { type: 'text', name: 'B-Tree and B+ Tree Indexes', content: 'B+ trees store keys in internal nodes and data pointers in leaves linked sequentially. Insertions and deletions maintain balance through splits and merges. Order m means each node has between ceil(m/2) and m children. Used in most RDBMS systems.' },
            { type: 'text', name: 'Query Optimization', content: 'The query optimizer transforms SQL into an efficient execution plan. Steps: parsing, logical optimization (predicate pushdown, join reordering), physical optimization (index selection, join algorithm choice). Cost estimation uses statistics (cardinality, selectivity, histograms).' },
            { type: 'online', name: 'EXPLAIN Plan Guide', description: 'Guide to reading and interpreting EXPLAIN output from PostgreSQL, MySQL, and Oracle for query performance analysis.' },
            { type: 'text', name: 'Join Algorithms', content: 'Nested loop join: O(n*m), simple but slow. Sort-merge join: sorts both inputs, then merges in O(n log n + m log m). Hash join: builds hash table on smaller relation, probes with larger. Grace hash join handles data larger than memory.' },
            { type: 'attachment', name: 'Query Plan Analysis Guide' },
        ]},
        { title: 'Transaction Management', description: 'ACID properties, concurrency control, and recovery mechanisms.', units: [
            { type: 'text', name: 'ACID Properties', content: 'Atomicity: transactions are all-or-nothing. Consistency: transactions maintain database invariants. Isolation: concurrent transactions appear serial. Durability: committed changes survive failures. ACID properties are fundamental to reliable transaction processing.' },
            { type: 'text', name: 'Concurrency Control Protocols', content: 'Two-phase locking (2PL) acquires all locks before releasing any. Strict 2PL holds locks until commit. Optimistic concurrency control validates at commit time. Multi-version CC (MVCC) keeps multiple versions for snapshot isolation. Deadlock detection uses wait-for graphs.' },
            { type: 'online', name: 'Transaction Isolation Levels', description: 'Interactive demonstration of SQL isolation levels (READ UNCOMMITTED through SERIALIZABLE) showing anomalies at each level.' },
            { type: 'text', name: 'Write-Ahead Logging', content: 'WAL writes log records before modifying data pages. ARIES recovery algorithm uses analysis, redo, and undo phases. Checkpoints reduce recovery time by flushing dirty pages. Log sequence numbers (LSN) ensure correct ordering of operations.' },
            { type: 'attachment', name: 'Transaction Scenarios' },
        ]},
        { title: 'NoSQL Database Systems', description: 'Document stores, key-value stores, column families, and graph databases.', units: [
            { type: 'text', name: 'CAP Theorem and NoSQL Motivation', content: 'The CAP theorem states that a distributed system can provide at most two of: Consistency, Availability, and Partition tolerance. NoSQL databases trade consistency for availability and scalability. BASE (Basically Available, Soft state, Eventual consistency) contrasts with ACID.' },
            { type: 'text', name: 'Document and Key-Value Stores', content: 'MongoDB stores JSON-like documents with flexible schemas. Redis is an in-memory key-value store supporting strings, lists, sets, and sorted sets. Document stores enable schema evolution and nested data. Key-value stores provide O(1) access by key.' },
            { type: 'online', name: 'NoSQL Database Comparison', description: 'Feature comparison of MongoDB, Redis, Cassandra, Neo4j, and DynamoDB with use case recommendations.' },
            { type: 'text', name: 'Graph Databases', content: 'Graph databases like Neo4j store nodes, relationships, and properties. Cypher query language traverses the graph using pattern matching. Graph databases excel at relationship-heavy queries (social networks, recommendations, fraud detection) where joins would be expensive.' },
            { type: 'attachment', name: 'NoSQL Hands-on Guide' },
        ]},
        { title: 'Advanced SQL', description: 'Window functions, CTEs, recursive queries, and stored procedures.', units: [
            { type: 'text', name: 'Window Functions', content: 'Window functions compute values across rows related to the current row. ROW_NUMBER, RANK, DENSE_RANK assign sequential values. SUM, AVG, COUNT OVER (PARTITION BY ... ORDER BY ...) compute running aggregates. LAG/LEAD access previous/next rows.' },
            { type: 'text', name: 'Common Table Expressions', content: 'CTEs (WITH clause) define named temporary result sets for readability. Recursive CTEs handle hierarchical data (org charts, bill of materials). They consist of a base case and a recursive step joined with UNION ALL.' },
            { type: 'online', name: 'Advanced SQL Exercises', description: 'Practice platform with challenging SQL problems covering window functions, recursive CTEs, and complex analytical queries.' },
            { type: 'text', name: 'Stored Procedures and Triggers', content: 'Stored procedures encapsulate reusable SQL logic on the server. Functions return values. Triggers execute automatically on INSERT, UPDATE, or DELETE events. Use triggers cautiously as they can make debugging difficult and impact performance.' },
            { type: 'attachment', name: 'Advanced SQL Worksheet' },
        ]},
        { title: 'Database Design Methodology', description: 'Conceptual, logical, and physical database design process.', units: [
            { type: 'text', name: 'Conceptual Design with ER', content: 'Conceptual design captures the data requirements using ER diagrams. Identify entities, attributes, relationships, and constraints from requirements. Consider generalization/specialization hierarchies and weak entities. The result is implementation-independent.' },
            { type: 'text', name: 'Logical Design: ER to Relational', content: 'Transform ER diagrams to relational schemas: entities become tables, M:N relationships become junction tables, 1:N relationships add foreign keys. Multivalued attributes create separate tables. ISA hierarchies can use single table, one per subclass, or one per entity.' },
            { type: 'online', name: 'Database Design Tool', description: 'Online tool for creating ER diagrams and automatically generating SQL DDL from the visual model.' },
            { type: 'text', name: 'Physical Design and Tuning', content: 'Physical design involves choosing indexes, partitioning strategies, denormalization for performance, and storage parameters. Monitor slow queries, analyze execution plans, and create indexes on frequently filtered and joined columns.' },
            { type: 'attachment', name: 'Database Design Case Study' },
        ]},
        { title: 'Distributed Databases', description: 'Replication, partitioning, and distributed query processing.', units: [
            { type: 'text', name: 'Data Replication Strategies', content: 'Master-slave replication sends writes to master and reads from replicas. Multi-master allows writes anywhere with conflict resolution. Synchronous replication guarantees consistency but adds latency. Asynchronous replication is faster but risks data loss.' },
            { type: 'text', name: 'Partitioning and Sharding', content: 'Horizontal partitioning (sharding) distributes rows across nodes by a shard key. Range partitioning groups consecutive keys. Hash partitioning distributes uniformly. Consistent hashing minimizes redistribution when nodes are added or removed.' },
            { type: 'online', name: 'Distributed Systems Patterns', description: 'Reference for distributed database patterns including consensus algorithms, replication strategies, and partition management.' },
            { type: 'text', name: 'Two-Phase Commit', content: 'Two-phase commit (2PC) coordinates distributed transactions. Phase 1: coordinator asks participants to prepare (vote yes/no). Phase 2: coordinator sends commit or abort based on votes. 2PC is blocking; three-phase commit and Paxos address this limitation.' },
            { type: 'attachment', name: 'Distributed Database Architecture' },
        ]},
        { title: 'Data Warehousing and Analytics', description: 'OLAP, star schemas, ETL processes, and analytical query optimization.', units: [
            { type: 'text', name: 'Star and Snowflake Schemas', content: 'Star schemas have a central fact table surrounded by dimension tables. Snowflake schemas normalize dimensions into sub-dimensions. Fact tables store measurements (sales amount, quantity). Dimension tables store descriptive attributes (product name, date, location).' },
            { type: 'text', name: 'ETL and Data Pipelines', content: 'Extract-Transform-Load (ETL) moves data from operational sources to the warehouse. Extract reads from sources. Transform cleans, deduplicates, and reshapes. Load writes to the target. Modern ELT loads raw data first, then transforms in the warehouse.' },
            { type: 'online', name: 'Data Warehouse Design Guide', description: 'Best practices for designing data warehouses with dimensional modeling, slowly changing dimensions, and materialized views.' },
            { type: 'text', name: 'OLAP Operations', content: 'OLAP (Online Analytical Processing) supports roll-up (aggregate), drill-down (detail), slice (filter one dimension), dice (filter multiple dimensions), and pivot (rotate) operations. MOLAP uses multidimensional arrays; ROLAP uses relational tables.' },
            { type: 'attachment', name: 'Data Warehouse Project' },
        ]},
        { title: 'Database Security', description: 'Access control, SQL injection prevention, and data encryption.', units: [
            { type: 'text', name: 'Access Control: GRANT and REVOKE', content: 'SQL GRANT gives privileges (SELECT, INSERT, UPDATE, DELETE) to users or roles. REVOKE removes privileges. Role-based access control groups permissions. Row-level security restricts data visibility per user. Views can enforce column-level security.' },
            { type: 'text', name: 'SQL Injection Prevention', content: 'SQL injection inserts malicious SQL through user input. Prevention: use parameterized queries/prepared statements, input validation, stored procedures, ORM frameworks, and principle of least privilege. Never concatenate user input into SQL strings.' },
            { type: 'online', name: 'Database Security Best Practices', description: 'Comprehensive guide to database security covering authentication, authorization, encryption, auditing, and vulnerability assessment.' },
            { type: 'text', name: 'Data Encryption', content: 'Transparent Data Encryption (TDE) encrypts data at rest. SSL/TLS encrypts data in transit. Column-level encryption protects sensitive fields (SSN, credit cards). Key management and rotation are critical. Always hash passwords with bcrypt or Argon2.' },
            { type: 'attachment', name: 'Security Audit Checklist' },
        ]},
        { title: 'Object-Relational Mapping', description: 'ORM frameworks, JPA, Hibernate, and the impedance mismatch.', units: [
            { type: 'text', name: 'Object-Relational Impedance Mismatch', content: 'The impedance mismatch between object-oriented programming and relational databases includes: granularity (classes vs tables), inheritance (no SQL equivalent), identity (object identity vs primary key), associations (references vs foreign keys), and data navigation.' },
            { type: 'text', name: 'JPA and Hibernate', content: 'JPA defines the standard for Java ORM. Hibernate implements JPA with annotations: @Entity, @Table, @Id, @Column, @OneToMany, @ManyToOne, @ManyToMany. JPQL provides object-oriented query syntax. Lazy loading defers association fetching until accessed.' },
            { type: 'online', name: 'Hibernate Performance Guide', description: 'Guide to optimizing Hibernate performance: N+1 query problem, batch fetching, second-level cache, and query optimization.' },
            { type: 'text', name: 'Active Record vs Repository Pattern', content: 'Active Record embeds persistence in the domain object (model.save()). Repository pattern separates persistence behind a collection-like interface. Active Record is simpler for CRUD; Repository is better for complex domains with Domain-Driven Design.' },
            { type: 'attachment', name: 'ORM Configuration Guide' },
        ]},
        { title: 'Database Performance Tuning', description: 'Query optimization, index tuning, and performance monitoring.', units: [
            { type: 'text', name: 'Query Performance Analysis', content: 'Use EXPLAIN ANALYZE to see actual execution times and row counts. Look for sequential scans on large tables (add indexes), hash joins with bad estimates (update statistics), and sort operations on large result sets (add covering indexes).' },
            { type: 'text', name: 'Index Design Strategies', content: 'Create indexes on WHERE clause columns, JOIN columns, and ORDER BY columns. Composite indexes follow the leftmost prefix rule. Covering indexes include all query columns to avoid table lookups. Partial indexes filter on a subset of rows. Too many indexes slow writes.' },
            { type: 'online', name: 'Database Benchmarking Tools', description: 'Guide to using pgbench, sysbench, and TPC benchmarks for measuring and comparing database performance.' },
            { type: 'text', name: 'Connection Pooling and Caching', content: 'Connection pools (HikariCP, PgBouncer) reuse database connections to avoid connection overhead. Query result caching (Redis, Memcached) reduces database load for read-heavy workloads. Materialized views precompute expensive queries.' },
            { type: 'attachment', name: 'Performance Tuning Checklist' },
        ]},
        { title: 'NewSQL and Modern Database Trends', description: 'NewSQL databases, time-series databases, and vector databases.', units: [
            { type: 'text', name: 'NewSQL Databases', content: 'NewSQL databases (CockroachDB, Google Spanner, TiDB) provide SQL interfaces with horizontal scalability and ACID transactions. Spanner uses TrueTime for global consistency. CockroachDB uses Raft consensus. They bridge the gap between SQL and NoSQL.' },
            { type: 'text', name: 'Specialized Database Systems', content: 'Time-series databases (InfluxDB, TimescaleDB) optimize for time-stamped data. Vector databases (Pinecone, Weaviate, Milvus) store embeddings for similarity search. Streaming databases (ksqlDB, Materialize) process continuous queries on data streams.' },
            { type: 'online', name: 'Database Landscape Overview', description: 'Interactive map of the database ecosystem showing relational, document, graph, time-series, vector, and streaming database categories.' },
            { type: 'text', name: 'Database Selection Criteria', content: 'Consider: data model fit (relational, document, graph), consistency requirements (strong vs eventual), scalability needs (vertical vs horizontal), query patterns (OLTP vs OLAP), operational complexity, community, and licensing costs.' },
            { type: 'attachment', name: 'Database Comparison Matrix' },
        ]},
        { title: 'Full-Text Search in Databases', description: 'Text search capabilities, inverted indexes, and search engines.', units: [
            { type: 'text', name: 'Full-Text Search Fundamentals', content: 'Full-text search enables keyword-based retrieval. Inverted indexes map terms to documents containing them. Tokenization, stemming, and stop word removal preprocess text. TF-IDF and BM25 rank documents by relevance.' },
            { type: 'text', name: 'Elasticsearch and PostgreSQL FTS', content: 'Elasticsearch provides distributed full-text search with RESTful API. PostgreSQL has built-in full-text search using tsvector and tsquery. Both support phrase matching, fuzzy matching, faceted search, and highlighting. Choose based on query complexity and scale.' },
            { type: 'online', name: 'Search Engine Architecture', description: 'Overview of search engine internals: crawling, indexing, query processing, ranking, and result presentation.' },
            { type: 'text', name: 'Vector Search and Embeddings', content: 'Vector search finds similar items by computing distances in embedding space. Dense retrieval uses neural encoders to embed queries and documents. Approximate nearest neighbor algorithms (HNSW, IVF) enable fast similarity search at scale.' },
            { type: 'attachment', name: 'Search Implementation Guide' },
        ]},
        { title: 'Database Migration and Evolution', description: 'Schema migration tools, backward compatibility, and zero-downtime migrations.', units: [
            { type: 'text', name: 'Schema Migration with Flyway and Liquibase', content: 'Flyway uses numbered SQL scripts for version-controlled migrations. Liquibase uses XML/YAML changelogs with rollback support. Both track applied migrations in a metadata table. Always test migrations on staging before production.' },
            { type: 'text', name: 'Zero-Downtime Migrations', content: 'Zero-downtime migrations use expand-contract pattern: add new column, backfill data, update code to write both, remove old column. Online schema changes (pt-online-schema-change, gh-ost) modify large tables without locking.' },
            { type: 'online', name: 'Migration Best Practices', description: 'Guide to safe database migrations covering backward compatibility, rollback planning, and data migration strategies.' },
            { type: 'text', name: 'Data Migration Patterns', content: 'ETL pipelines for bulk migration. Dual-write during transition periods. Event sourcing enables replay-based migration. Blue-green database deployment switches between two database versions. Always verify data integrity after migration.' },
            { type: 'attachment', name: 'Migration Planning Template' },
        ]},
        { title: 'Database Administration', description: 'Backup strategies, monitoring, and operational best practices.', units: [
            { type: 'text', name: 'Backup and Recovery', content: 'Full backups capture everything. Incremental backups save changes since last backup. Point-in-time recovery uses WAL archives to restore to any moment. Test restores regularly. Store backups offsite. Follow the 3-2-1 rule: 3 copies, 2 media types, 1 offsite.' },
            { type: 'text', name: 'Monitoring and Alerting', content: 'Monitor: query latency (p50, p95, p99), connections (active, idle, waiting), replication lag, disk usage, cache hit ratio, lock contention, and slow queries. Use pg_stat_statements, Performance Schema, or cloud monitoring tools.' },
            { type: 'online', name: 'DBA Operational Guide', description: 'Comprehensive guide for database administrators covering daily operations, maintenance windows, capacity planning, and incident response.' },
            { type: 'text', name: 'Capacity Planning', content: 'Estimate storage growth from row counts and sizes. Plan IOPS for expected query load. Size memory for working set and buffer pool. Monitor trends to predict when scaling is needed. Consider read replicas for read-heavy workloads.' },
            { type: 'attachment', name: 'DBA Checklist' },
        ]},
        { title: 'Temporal and Spatial Databases', description: 'Managing time-varying data and geographic information.', units: [
            { type: 'text', name: 'Temporal Database Concepts', content: 'Valid time records when facts are true in the real world. Transaction time records when facts are stored in the database. Bitemporal tables track both. SQL:2011 added temporal support with PERIOD, FOR PORTION OF, and temporal primary keys.' },
            { type: 'text', name: 'Spatial Data and PostGIS', content: 'PostGIS extends PostgreSQL with spatial types (POINT, LINESTRING, POLYGON) and spatial indexes (R-tree via GiST). Spatial queries include ST_Distance, ST_Contains, ST_Intersects, and ST_Buffer. Used in mapping, logistics, and location-based services.' },
            { type: 'online', name: 'Spatial SQL Tutorial', description: 'Hands-on tutorial for writing spatial queries with PostGIS including nearest neighbor, containment, and distance calculations.' },
            { type: 'text', name: 'Time-Series Data Management', content: 'Time-series databases optimize for append-heavy workloads with time-based queries. Compression techniques exploit temporal ordering. Retention policies automatically expire old data. Continuous aggregates precompute time-windowed summaries.' },
            { type: 'attachment', name: 'Spatial Data Exercises' },
        ]},
        { title: 'Graph Databases in Depth', description: 'Property graph model, Cypher query language, and graph analytics.', units: [
            { type: 'text', name: 'Property Graph Model', content: 'Property graphs consist of nodes (with labels and properties) connected by directed relationships (with types and properties). Unlike relational joins, graph traversals follow relationships directly using index-free adjacency. This makes relationship queries constant time per hop.' },
            { type: 'text', name: 'Cypher Query Language', content: 'Cypher uses ASCII art patterns: (n:Person)-[:KNOWS]->(m:Person). MATCH finds patterns. WHERE filters. RETURN projects results. CREATE adds data. WITH chains query parts. Path functions find shortest paths. Aggregation and ordering work like SQL.' },
            { type: 'online', name: 'Neo4j Sandbox', description: 'Interactive Neo4j environment for practicing Cypher queries on sample datasets like movie recommendations and social networks.' },
            { type: 'text', name: 'Graph Analytics', content: 'Graph algorithms: PageRank for importance, community detection for clustering, shortest path for routing, centrality measures for influence. Neo4j Graph Data Science library provides scalable implementations. Graph embeddings learn node representations for ML.' },
            { type: 'attachment', name: 'Graph Database Project' },
        ]},
    ],
    exercises: {
        programming: [
            { title: 'SQL Query Challenge: Basic', problemStatement: 'Write SQL queries for a university database: find students enrolled in specific courses, compute average grades per department, and list professors teaching multiple courses.' },
            { title: 'Database Normalization Tool', problemStatement: 'Implement a tool that takes a relation schema and functional dependencies, computes the closure, finds candidate keys, and determines the normal form (1NF, 2NF, 3NF, BCNF).' },
            { title: 'B+ Tree Implementation', problemStatement: 'Implement a B+ tree with configurable order supporting insert, delete, search, and range queries. Maintain leaf node links for sequential access.' },
            { title: 'Transaction Scheduler', problemStatement: 'Implement a transaction scheduler using strict two-phase locking. Handle lock requests, detect deadlocks using a wait-for graph, and resolve by aborting the youngest transaction.' },
            { title: 'SQL Query Optimizer', problemStatement: 'Implement a simple query optimizer that parses SQL SELECT queries, builds a relational algebra tree, and applies optimization rules (predicate pushdown, join reordering).' },
            { title: 'Connection Pool Manager', problemStatement: 'Implement a JDBC connection pool with configurable pool size, connection validation, idle timeout, and maximum wait time for connection acquisition.' },
            { title: 'NoSQL Document Store', problemStatement: 'Implement a simple document store supporting insert, find (with query filters), update, and delete operations on JSON documents with in-memory indexing.' },
            { title: 'Schema Migration Engine', problemStatement: 'Build a schema migration tool that tracks applied migrations, executes pending migrations in order, supports rollback, and validates checksums for integrity.' },
            { title: 'Query Result Cache', problemStatement: 'Implement a query result cache with LRU eviction, TTL-based expiration, and cache invalidation on table modifications. Support parameterized query caching.' },
            { title: 'MVCC Simulator', problemStatement: 'Implement a multi-version concurrency control simulator. Maintain version chains, implement snapshot isolation, and detect write-write conflicts.' },
            { title: 'SQL Window Functions', problemStatement: 'Write SQL queries using window functions: running totals, ranking within groups, moving averages, lag/lead comparisons, and cumulative distributions.' },
            { title: 'ER to Schema Generator', problemStatement: 'Implement a tool that reads an ER diagram specification (JSON format) and generates SQL CREATE TABLE statements with proper keys and constraints.' },
            { title: 'Full-Text Search Engine', problemStatement: 'Build a simple full-text search engine with tokenization, inverted index construction, TF-IDF scoring, and boolean query support (AND, OR, NOT).' },
            { title: 'Database Index Advisor', problemStatement: 'Analyze a query workload and recommend indexes. Consider column selectivity, query frequency, and the cost of maintaining indexes during writes.' },
            { title: 'Replication Simulator', problemStatement: 'Simulate master-slave replication with configurable lag. Demonstrate read-after-write consistency issues and implement monotonic read consistency.' },
            { title: 'SQL Advanced Joins', problemStatement: 'Write complex SQL queries using self-joins, lateral joins, anti-joins, and recursive CTEs to solve hierarchical and graph-like query problems.' },
            { title: 'Database Backup Manager', problemStatement: 'Implement a backup management system supporting full and incremental backups, scheduled execution, retention policies, and point-in-time recovery coordination.' },
            { title: 'Graph Database Queries', problemStatement: 'Use Neo4j and Cypher to model and query a social network: find friend-of-friend recommendations, shortest paths between users, and community detection.' },
            { title: 'Data Warehouse ETL Pipeline', problemStatement: 'Build an ETL pipeline that extracts data from CSV sources, transforms it (cleaning, deduplication, type conversion), and loads it into a star schema warehouse.' },
            { title: 'Query Performance Benchmark', problemStatement: 'Create a benchmarking tool that generates test data, runs queries with and without indexes, measures execution times, and produces a performance comparison report.' },
            { title: 'Stored Procedure Library', problemStatement: 'Write PostgreSQL stored procedures for common operations: audit logging trigger, automatic archiving, cascading soft deletes, and denormalized view maintenance.' },
            { title: 'Hash Join Implementation', problemStatement: 'Implement the hash join algorithm for two relations. Support both in-memory and grace hash join (partitioned) for data larger than available memory.' },
            { title: 'SQL Injection Scanner', problemStatement: 'Build a tool that analyzes Java code to detect potential SQL injection vulnerabilities: string concatenation in queries, missing parameterized statements, and unsafe dynamic SQL.' },
            { title: 'Time-Series Data Processor', problemStatement: 'Implement a time-series data processor supporting downsampling, interpolation, gap filling, and continuous aggregate computation over time windows.' },
            { title: 'Object-Relational Mapper', problemStatement: 'Build a simple ORM that maps Java classes to database tables. Support basic CRUD operations, one-to-many relationships, and lazy loading of associations.' },
            { title: 'Distributed Lock Manager', problemStatement: 'Implement a distributed lock manager using a database table for coordination. Support exclusive and shared locks with automatic expiration and deadlock detection.' },
            { title: 'Query Plan Visualizer', problemStatement: 'Parse PostgreSQL EXPLAIN ANALYZE JSON output and generate a visual tree representation showing node types, costs, row estimates vs actuals, and timing.' },
            { title: 'CDC Event Processor', problemStatement: 'Implement a Change Data Capture processor that monitors database changes via WAL or triggers and publishes events to downstream consumers.' },
            { title: 'Data Quality Validator', problemStatement: 'Build a data quality framework that validates constraints (nullability, uniqueness, referential integrity, business rules) and generates quality reports with violation details.' },
            { title: 'Pagination Strategies', problemStatement: 'Implement offset-based and cursor-based pagination for SQL queries. Compare performance characteristics and handle concurrent modifications during pagination.' },
            { title: 'ACID Transaction Tester', problemStatement: 'Create a test suite that verifies ACID properties under concurrent access: atomicity on failure, consistency of constraints, isolation between transactions, and durability after crash.' },
            { title: 'Vector Similarity Search', problemStatement: 'Implement approximate nearest neighbor search using locality-sensitive hashing. Store and query vector embeddings with configurable distance metrics.' },
            { title: 'SQL Parser', problemStatement: 'Build a basic SQL parser that tokenizes and parses SELECT statements into an AST. Support WHERE, JOIN, GROUP BY, and ORDER BY clauses.' },
            { title: 'Database Diff Tool', problemStatement: 'Implement a tool that compares two database schemas and generates ALTER statements to migrate from one to the other, handling tables, columns, indexes, and constraints.' },
            { title: 'Batch Data Loader', problemStatement: 'Implement a high-performance batch data loader using COPY/bulk insert operations, parallel loading, error handling, and progress reporting.' },
            { title: 'Query Result Serializer', problemStatement: 'Build a query result serializer that converts JDBC ResultSets to JSON, CSV, and XML formats with configurable column selection, formatting, and streaming for large results.' },
            { title: 'Database Health Monitor', problemStatement: 'Create a monitoring dashboard that tracks connection counts, query latency histograms, table sizes, index usage, and cache hit ratios via database system views.' },
            { title: 'Spatial Query Processor', problemStatement: 'Implement spatial query operations: point-in-polygon, nearest neighbor search, bounding box intersection, and distance calculations using an R-tree index.' },
            { title: 'Multi-Tenant Database Router', problemStatement: 'Implement a multi-tenant database routing layer that directs queries to tenant-specific schemas based on context, with connection pooling per tenant.' },
            { title: 'Write-Ahead Log Implementation', problemStatement: 'Implement a simple write-ahead log with log record types (begin, update, commit, abort), checkpointing, and crash recovery using the ARIES algorithm.' },
        ],
        text: [
            { title: 'SQL vs NoSQL Comparison', problemStatement: 'Compare relational databases with NoSQL databases. Discuss consistency models, scalability, query flexibility, schema evolution, and appropriate use cases for each.' },
            { title: 'CAP Theorem Analysis', problemStatement: 'Explain the CAP theorem and its implications for distributed database design. Provide examples of CP, AP, and CA systems and when to choose each.' },
            { title: 'Database Normalization Trade-offs', problemStatement: 'Discuss the trade-offs between normalized and denormalized database designs. When is denormalization justified? Provide examples from real-world applications.' },
            { title: 'MVCC Implementation Comparison', problemStatement: 'Compare how PostgreSQL and MySQL implement MVCC. Discuss version storage, vacuum/purge processes, and the impact on read and write performance.' },
            { title: 'Future of Databases', problemStatement: 'Discuss emerging trends in database technology: NewSQL, serverless databases, vector databases, and AI-integrated query optimization. What problems do they solve?' },
        ],
        modeling: [
            { title: 'University Database ER Diagram', problemStatement: 'Design an ER diagram for a university system with Students, Courses, Professors, Departments, and Enrollments. Include cardinalities and attributes.', diagramType: 'ClassDiagram' },
            { title: 'E-Commerce Database Schema', problemStatement: 'Create a class diagram showing the database schema for an e-commerce platform with Customers, Orders, Products, Categories, Reviews, and Payments.', diagramType: 'ClassDiagram' },
            { title: 'Query Processing Pipeline', problemStatement: 'Model the query processing pipeline as an activity diagram: parsing, validation, optimization, plan generation, execution, and result formatting.', diagramType: 'ActivityDiagram' },
            { title: 'Transaction Lifecycle', problemStatement: 'Create an activity diagram showing the lifecycle of a database transaction: begin, operations, commit/rollback, lock management, and recovery.', diagramType: 'ActivityDiagram' },
            { title: 'Social Network Graph Model', problemStatement: 'Design a property graph model for a social network with Users, Posts, Comments, Groups, and various relationship types (FOLLOWS, LIKES, MEMBER_OF).', diagramType: 'ClassDiagram' },
        ],
        quiz: [
            { title: 'SQL Basics Quiz', questions: [
                { type: 'multiple-choice', title: 'JOIN Types', text: 'Which JOIN returns rows even when there is no match in the right table?', points: 5, singleChoice: true, answerOptions: [{ text: 'LEFT OUTER JOIN', isCorrect: true }, { text: 'INNER JOIN', isCorrect: false }, { text: 'CROSS JOIN', isCorrect: false }, { text: 'NATURAL JOIN', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Normalization', text: 'Which normal form eliminates transitive dependencies?', points: 5, singleChoice: true, answerOptions: [{ text: '3NF', isCorrect: true }, { text: '1NF', isCorrect: false }, { text: '2NF', isCorrect: false }, { text: 'BCNF', isCorrect: false }] },
            ]},
            { title: 'Transaction Management Quiz', questions: [
                { type: 'multiple-choice', title: 'ACID', text: 'Which ACID property ensures transactions are all-or-nothing?', points: 5, singleChoice: true, answerOptions: [{ text: 'Atomicity', isCorrect: true }, { text: 'Consistency', isCorrect: false }, { text: 'Isolation', isCorrect: false }, { text: 'Durability', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Isolation Levels', text: 'Which isolation level prevents phantom reads?', points: 5, singleChoice: true, answerOptions: [{ text: 'SERIALIZABLE', isCorrect: true }, { text: 'READ COMMITTED', isCorrect: false }, { text: 'READ UNCOMMITTED', isCorrect: false }, { text: 'REPEATABLE READ', isCorrect: false }] },
            ]},
            { title: 'NoSQL Quiz', questions: [
                { type: 'multiple-choice', title: 'CAP Theorem', text: 'According to CAP theorem, a distributed system cannot guarantee all three of:', points: 5, singleChoice: true, answerOptions: [{ text: 'Consistency, Availability, Partition Tolerance', isCorrect: true }, { text: 'Consistency, Atomicity, Performance', isCorrect: false }, { text: 'Availability, Backup, Caching', isCorrect: false }, { text: 'Consistency, Backup, Partition Tolerance', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Document Store', text: 'Which is a document-oriented NoSQL database?', points: 5, singleChoice: true, answerOptions: [{ text: 'MongoDB', isCorrect: true }, { text: 'Redis', isCorrect: false }, { text: 'Neo4j', isCorrect: false }, { text: 'Cassandra', isCorrect: false }] },
            ]},
        ],
        fileUpload: [
            { title: 'Database Design Document', problemStatement: 'Upload a complete database design document including ER diagram, relational schema, normalization analysis, and sample queries for a library management system.' },
            { title: 'Query Optimization Report', problemStatement: 'Upload a report analyzing query performance before and after optimization. Include EXPLAIN plans, index recommendations, and timing measurements.' },
        ],
    },
    faqs: [
        { title: 'What is the difference between WHERE and HAVING in SQL?', answer: 'WHERE filters rows before grouping (applied to individual rows). HAVING filters groups after GROUP BY aggregation (applied to aggregate results). Example: WHERE salary > 50000 filters individuals; HAVING AVG(salary) > 50000 filters groups.' },
        { title: 'When should I use an index?', answer: 'Create indexes on columns used in WHERE clauses, JOIN conditions, and ORDER BY. Avoid indexes on frequently updated columns, low-selectivity columns, and small tables. Each index adds write overhead. Monitor index usage and remove unused ones.' },
        { title: 'What is the N+1 query problem?', answer: 'N+1 occurs when fetching a list (1 query) and then loading related data for each item individually (N queries). Fix with JOIN FETCH (eager loading), batch fetching (@BatchSize), or query projection. Common in ORM frameworks like Hibernate.' },
        { title: 'How does MVCC work?', answer: 'MVCC keeps multiple versions of each row. Readers see a consistent snapshot without blocking writers. PostgreSQL stores versions in the main table with xmin/xmax transaction IDs. MySQL InnoDB uses undo logs for version reconstruction.' },
        { title: 'What is the difference between clustered and non-clustered indexes?', answer: 'A clustered index determines the physical order of data (one per table, usually the primary key). Non-clustered indexes are separate structures pointing to data rows. Clustered indexes are faster for range queries; non-clustered for lookups.' },
        { title: 'How do I prevent SQL injection?', answer: 'Use parameterized queries (PreparedStatement in Java) instead of string concatenation. ORMs handle this automatically. Additionally: validate input types, use stored procedures, apply least privilege, and enable WAF rules.' },
        { title: 'What is normalization and why is it important?', answer: 'Normalization organizes tables to reduce redundancy and prevent update anomalies. Each normal form (1NF-BCNF) eliminates specific types of dependencies. Over-normalization can hurt read performance; denormalize strategically with materialized views.' },
        { title: 'When should I use a NoSQL database instead of SQL?', answer: 'Use NoSQL when you need: flexible schema (document stores), high write throughput (column stores), graph traversals (graph DB), or simple key-value access (Redis). Use SQL when you need ACID transactions, complex queries, or strong consistency.' },
        { title: 'What are the differences between 2NF, 3NF, and BCNF?', answer: '2NF: no partial dependencies (non-key attribute depends on part of a candidate key). 3NF: no transitive dependencies (non-key depends on non-key). BCNF: every determinant is a superkey. Each eliminates more redundancy.' },
        { title: 'How do I optimize a slow SQL query?', answer: 'Steps: run EXPLAIN ANALYZE, check for sequential scans (add indexes), verify join order, update table statistics (ANALYZE), rewrite subqueries as JOINs, use covering indexes, add WHERE clause filters early, and consider query plan hints.' },
        { title: 'What is the CAP theorem?', answer: 'The CAP theorem states a distributed system can only guarantee two of three: Consistency (all nodes see the same data), Availability (every request gets a response), Partition Tolerance (system works despite network splits). Since partitions are inevitable, the real choice is CP vs AP.' },
        { title: 'How do database transactions work?', answer: 'BEGIN starts a transaction. SQL statements execute within it. COMMIT makes changes permanent. ROLLBACK undoes all changes. The database ensures ACID properties through locking, MVCC, and write-ahead logging.' },
        { title: 'What is a deadlock and how is it handled?', answer: 'A deadlock occurs when two transactions each hold a lock the other needs. The database detects deadlocks using a wait-for graph and resolves by aborting one transaction (usually the one with less work done). The application should retry the aborted transaction.' },
        { title: 'How do I design a many-to-many relationship?', answer: 'Create a junction/bridge table with foreign keys to both tables. Example: student_course table with student_id and course_id as a composite primary key. Add additional attributes (enrollment_date, grade) to the junction table as needed.' },
        { title: 'What is sharding and when do I need it?', answer: 'Sharding horizontally partitions data across multiple database instances by a shard key. Need it when: single database cannot handle the load, data exceeds single server storage, or latency requires geographic distribution. Choose shard key carefully to avoid hotspots.' },
        { title: 'How do window functions differ from GROUP BY?', answer: 'GROUP BY collapses rows into groups, returning one row per group. Window functions compute over a set of rows but retain all individual rows. OVER (PARTITION BY ... ORDER BY ...) defines the window. Example: ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC).' },
        { title: 'What is a materialized view?', answer: 'A materialized view stores the result of a query physically, unlike regular views which execute the query each time. They speed up expensive queries but need refreshing when underlying data changes. REFRESH MATERIALIZED VIEW updates the data.' },
        { title: 'How do I handle database migrations safely?', answer: 'Use migration tools (Flyway, Liquibase). Write forward-compatible migrations. Test on staging first. Use expand-contract for breaking changes. Plan rollback for each migration. Avoid locking operations on large tables. Monitor during deployment.' },
        { title: 'What is the difference between OLTP and OLAP?', answer: 'OLTP (Online Transaction Processing): many short transactions, normalized schema, write-heavy. OLAP (Online Analytical Processing): complex analytical queries, denormalized schema (star/snowflake), read-heavy. Data warehouses serve OLAP workloads.' },
        { title: 'How do I choose between PostgreSQL and MySQL?', answer: 'PostgreSQL: better standards compliance, advanced features (window functions, CTEs, JSON, full-text search, PostGIS), extensible. MySQL: simpler setup, faster for simple reads, wider hosting support. Both are mature, reliable, and free. Consider your specific feature needs.' },
    ],
    channelMessages: [
        'Can someone explain the difference between a LEFT JOIN and a LEFT OUTER JOIN in SQL?',
        'My query runs fine on small data but takes 30 seconds on the production database. How do I debug this?',
        'I am confused about when to use 3NF vs BCNF. When would I stop at 3NF?',
        'How do I model a self-referencing relationship in SQL? For example, an employee reporting to a manager.',
        'What is the best way to handle soft deletes? Should I use a deleted flag or a separate archive table?',
        'Can someone explain the difference between a view and a materialized view with a practical example?',
        'My application has the N+1 query problem with Hibernate. What is the best fix?',
        'How do I write a recursive CTE to query an organizational hierarchy?',
        'What isolation level should I use for a banking application? Is SERIALIZABLE too slow?',
        'I need to store JSON data. Should I use a JSON column in PostgreSQL or switch to MongoDB?',
        'How do I set up master-slave replication for read scaling in PostgreSQL?',
        'What is the difference between TRUNCATE and DELETE in terms of transaction behavior?',
        'Can someone explain how B+ tree indexes handle range queries efficiently?',
        'My database backup is taking too long. Should I switch to incremental backups?',
        'How do I implement full-text search in PostgreSQL without Elasticsearch?',
    ],
};
