export default {
    topic: 'Distributed Systems',
    title: 'Distributed Systems and Cloud Computing',
    shortNamePrefix: 'DS',
    description: 'This course covers the design and implementation of distributed systems including consensus algorithms, replication strategies, consistency models, fault tolerance, RPC, microservices, and cloud-native architectures. Students learn to build reliable systems that span multiple networked machines.',
    lectures: [
        { title: 'Introduction to Distributed Systems', description: 'Challenges, models, and fundamental concepts of distributed computing.', units: [
            { type: 'text', name: 'Why Distributed Systems?', content: 'Distributed systems provide scalability (handle more load), fault tolerance (survive failures), and low latency (place data near users). Challenges include partial failures, network unreliability, clock skew, and the impossibility of global state.' },
            { type: 'text', name: 'System Models', content: 'Synchronous models assume bounded message delays and clock drift. Asynchronous models make no timing assumptions. Crash-stop failures mean processes halt. Byzantine failures include arbitrary behavior. The FLP impossibility shows consensus is impossible in asynchronous systems with one crash failure.' },
            { type: 'online', name: 'Distributed Systems Overview', description: 'Visual introduction to distributed systems concepts with interactive examples of network partitions and failure scenarios.' },
            { type: 'text', name: 'Fallacies of Distributed Computing', content: 'Peter Deutsch\'s eight fallacies: the network is reliable, latency is zero, bandwidth is infinite, the network is secure, topology doesn\'t change, there is one administrator, transport cost is zero, the network is homogeneous. Designing around these is essential.' },
            { type: 'attachment', name: 'Distributed Systems Reading List' },
        ]},
        { title: 'Remote Procedure Calls', description: 'RPC semantics, gRPC, and service communication patterns.', units: [
            { type: 'text', name: 'RPC Fundamentals', content: 'RPC makes remote function calls look like local calls. The client stub marshals parameters, sends them over the network, the server stub unmarshals and calls the function, then sends back the result. Challenges: network failures, at-most-once vs at-least-once semantics.' },
            { type: 'text', name: 'gRPC and Protocol Buffers', content: 'gRPC uses HTTP/2 for transport and Protocol Buffers for serialization. Proto files define services and messages. Code generation creates client and server stubs. Supports unary, server-streaming, client-streaming, and bidirectional streaming RPCs.' },
            { type: 'online', name: 'gRPC Tutorial', description: 'Hands-on tutorial for building gRPC services with Protocol Buffers in multiple languages.' },
            { type: 'text', name: 'REST vs gRPC vs GraphQL', content: 'REST uses HTTP methods on resources, is widely supported, but can over-fetch. gRPC uses binary serialization for performance and supports streaming. GraphQL lets clients specify exact data needs. Choose based on performance, ecosystem, and flexibility requirements.' },
            { type: 'attachment', name: 'RPC Design Patterns' },
        ]},
        { title: 'Time and Ordering', description: 'Logical clocks, vector clocks, and causal ordering in distributed systems.', units: [
            { type: 'text', name: 'Lamport Clocks', content: 'Lamport logical clocks assign a counter to each event. Rules: increment before each event, include counter in messages, receiver sets clock to max(local, received)+1. If a happened-before b, then L(a) < L(b). But L(a) < L(b) does not imply a happened-before b.' },
            { type: 'text', name: 'Vector Clocks', content: 'Vector clocks use a vector of counters (one per process). Each process increments its own entry. On receive, take element-wise maximum. Vector clocks capture causality: V(a) < V(b) if and only if a causally precedes b. Used in Amazon Dynamo for conflict detection.' },
            { type: 'online', name: 'Clock Synchronization Visualization', description: 'Interactive visualization of Lamport clocks, vector clocks, and their relationship to causal ordering of events.' },
            { type: 'text', name: 'Hybrid Logical Clocks', content: 'HLC combines physical time with logical counters. It captures causality like vector clocks but uses bounded space (single counter). HLC timestamps are always close to physical time. Used in CockroachDB and other distributed databases for consistent ordering.' },
            { type: 'attachment', name: 'Clock Exercises' },
        ]},
        { title: 'Consensus Algorithms', description: 'Paxos, Raft, and Byzantine fault-tolerant consensus.', units: [
            { type: 'text', name: 'Paxos Algorithm', content: 'Paxos achieves consensus among distributed processes despite failures. Phase 1 (Prepare): proposer picks a number, asks acceptors. Phase 2 (Accept): if majority responds, propose a value. Acceptors commit if no higher-numbered proposal seen. Multi-Paxos optimizes for repeated consensus.' },
            { type: 'text', name: 'Raft Consensus', content: 'Raft is designed for understandability. Leader election: candidates request votes with timeout. Log replication: leader appends entries, replicates to followers, commits when majority acknowledges. Safety: committed entries are never lost. Used in etcd, CockroachDB, and TiKV.' },
            { type: 'online', name: 'Raft Visualization', description: 'Interactive Raft visualization showing leader election, log replication, and handling of network partitions step by step.' },
            { type: 'text', name: 'Byzantine Fault Tolerance', content: 'BFT handles arbitrary (malicious) failures. PBFT requires 3f+1 nodes to tolerate f Byzantine failures. Three phases: pre-prepare, prepare, commit. Used in blockchain systems. HotStuff simplifies PBFT with linear communication complexity.' },
            { type: 'attachment', name: 'Consensus Algorithm Comparison' },
        ]},
        { title: 'Replication', description: 'Data replication strategies, consistency models, and conflict resolution.', units: [
            { type: 'text', name: 'Replication Strategies', content: 'Single-leader: one node accepts writes, replicates to followers. Multi-leader: multiple nodes accept writes (conflict resolution needed). Leaderless: any node accepts reads and writes (quorum-based). Each trades off consistency, availability, and latency differently.' },
            { type: 'text', name: 'Consistency Models', content: 'Strong consistency: reads always return the latest write. Eventual consistency: reads may return stale data but converge. Causal consistency: respects causal order. Read-your-writes: user sees their own updates. Monotonic reads: user never sees older data after newer.' },
            { type: 'online', name: 'Consistency Model Explorer', description: 'Interactive tool for exploring different consistency models with examples showing what reads return under each model.' },
            { type: 'text', name: 'Conflict Resolution', content: 'Last-writer-wins (LWW) uses timestamps (simple but lossy). CRDTs (Conflict-free Replicated Data Types) merge automatically. Application-level resolution (Amazon shopping cart) presents conflicts to users. Operational transformation (Google Docs) resolves concurrent edits.' },
            { type: 'attachment', name: 'Replication Design Guide' },
        ]},
        { title: 'Partitioning and Sharding', description: 'Data partitioning strategies and distributed query processing.', units: [
            { type: 'text', name: 'Partitioning Strategies', content: 'Range partitioning groups adjacent keys (good for range queries, risk of hotspots). Hash partitioning distributes uniformly (good for point queries, poor for ranges). Consistent hashing minimizes data movement when nodes join/leave. Compound partitioning combines both.' },
            { type: 'text', name: 'Consistent Hashing', content: 'Consistent hashing maps both keys and nodes to a ring. Each key is assigned to the next node clockwise. Adding/removing a node only affects neighboring keys. Virtual nodes improve balance. Used in Amazon Dynamo, Cassandra, and CDN routing.' },
            { type: 'online', name: 'Consistent Hashing Visualizer', description: 'Interactive visualization of consistent hashing showing key assignment, node addition/removal, and virtual node distribution.' },
            { type: 'text', name: 'Secondary Indexes in Partitioned Systems', content: 'Local indexes (document-partitioned) keep indexes on the same partition as data. Global indexes (term-partitioned) partition the index separately. Local indexes require scatter-gather for queries. Global indexes require distributed updates.' },
            { type: 'attachment', name: 'Partitioning Exercises' },
        ]},
        { title: 'Distributed Transactions', description: 'Two-phase commit, Saga pattern, and distributed ACID.', units: [
            { type: 'text', name: 'Two-Phase Commit', content: '2PC coordinates atomic commits across participants. Phase 1 (Prepare): coordinator asks all participants to prepare. Phase 2 (Commit/Abort): if all vote yes, commit; otherwise abort. 2PC is blocking: if coordinator fails during phase 2, participants are stuck.' },
            { type: 'text', name: 'Saga Pattern', content: 'Sagas break distributed transactions into local transactions with compensating actions. Choreography: services communicate via events. Orchestration: a central coordinator drives the saga. Sagas provide eventual consistency without distributed locking.' },
            { type: 'online', name: 'Distributed Transaction Patterns', description: 'Comparison of 2PC, 3PC, Saga, and TCC (Try-Confirm-Cancel) patterns with failure scenario analysis.' },
            { type: 'text', name: 'Spanner and Calvin', content: 'Google Spanner uses TrueTime (GPS + atomic clocks) for globally consistent transactions. Calvin uses deterministic ordering to avoid coordination. Both achieve serializable distributed transactions but with different trade-offs in latency and deployment requirements.' },
            { type: 'attachment', name: 'Distributed Transaction Exercises' },
        ]},
        { title: 'Fault Tolerance', description: 'Failure detection, recovery mechanisms, and reliability patterns.', units: [
            { type: 'text', name: 'Failure Detection', content: 'Heartbeat-based detection: nodes send periodic messages. Timeout indicates failure (but may be false positive). Phi accrual failure detector uses adaptive thresholds. SWIM protocol uses peer-to-peer gossip for scalable failure detection.' },
            { type: 'text', name: 'Reliability Patterns', content: 'Circuit breaker prevents cascading failures by stopping calls to failing services. Retry with exponential backoff handles transient failures. Bulkhead isolates components to contain failures. Timeouts prevent indefinite waiting. These patterns compose for resilient systems.' },
            { type: 'online', name: 'Chaos Engineering Introduction', description: 'Introduction to chaos engineering principles and tools like Chaos Monkey for testing system resilience in production.' },
            { type: 'text', name: 'Checkpointing and Recovery', content: 'Checkpointing saves process state periodically for recovery. Coordinated checkpointing uses distributed snapshots (Chandy-Lamport). Uncoordinated checkpointing requires domino-effect-free recovery. Write-ahead logging enables fine-grained recovery without full checkpoints.' },
            { type: 'attachment', name: 'Fault Tolerance Patterns' },
        ]},
        { title: 'Distributed Storage Systems', description: 'Key-value stores, distributed file systems, and object storage.', units: [
            { type: 'text', name: 'Amazon Dynamo', content: 'Dynamo is a highly available key-value store using consistent hashing, vector clocks for versioning, sloppy quorums for availability, gossip for membership, and Merkle trees for anti-entropy. It prioritizes availability over consistency (AP in CAP).' },
            { type: 'text', name: 'Google File System and HDFS', content: 'GFS stores large files in 64MB chunks replicated across chunkservers. A single master manages metadata. HDFS follows the same design with NameNode and DataNodes. Both optimize for large sequential reads/writes and append-heavy workloads.' },
            { type: 'online', name: 'Distributed Storage Comparison', description: 'Comparison of Dynamo, Cassandra, GFS/HDFS, Ceph, and MinIO distributed storage systems.' },
            { type: 'text', name: 'Object Storage', content: 'Object storage (S3, MinIO) stores data as objects in flat namespaces. Objects have metadata and unique keys. No file hierarchy or random writes. Highly scalable and durable. Best for unstructured data: images, backups, logs, and data lake storage.' },
            { type: 'attachment', name: 'Storage System Design' },
        ]},
        { title: 'Microservices Architecture', description: 'Service decomposition, API gateways, and service mesh.', units: [
            { type: 'text', name: 'Microservices Principles', content: 'Decompose by business capability. Each service owns its data. Communicate via APIs (REST, gRPC, events). Deploy independently. Team autonomy (two-pizza teams). Smart endpoints, dumb pipes. Design for failure. Automate everything (CI/CD, monitoring).' },
            { type: 'text', name: 'Service Mesh and API Gateway', content: 'API gateways handle external traffic: routing, authentication, rate limiting, SSL termination. Service meshes (Istio, Linkerd) manage service-to-service traffic: load balancing, circuit breaking, mutual TLS, observability. Both use sidecar proxies (Envoy).' },
            { type: 'online', name: 'Microservices Patterns Reference', description: 'Comprehensive reference of microservices patterns: decomposition, data management, communication, observability, and deployment.' },
            { type: 'text', name: 'Event-Driven Microservices', content: 'Event-driven architecture decouples services via asynchronous events. Event sourcing stores all changes as events. CQRS separates read and write models. Apache Kafka provides the event backbone. Events enable temporal decoupling and audit trails.' },
            { type: 'attachment', name: 'Microservices Design Guide' },
        ]},
        { title: 'Distributed Computing Frameworks', description: 'MapReduce, Spark, and stream processing systems.', units: [
            { type: 'text', name: 'MapReduce', content: 'MapReduce processes large datasets in parallel. Map phase applies a function to each record, producing key-value pairs. Shuffle groups by key. Reduce aggregates values per key. Fault tolerance via task re-execution. Limited by batch processing model.' },
            { type: 'text', name: 'Apache Spark', content: 'Spark extends MapReduce with in-memory computation, lazy evaluation, and a DAG execution model. RDDs (Resilient Distributed Datasets) are immutable, partitioned collections. Spark SQL, Spark Streaming, MLlib, and GraphX provide higher-level APIs.' },
            { type: 'online', name: 'Stream Processing Comparison', description: 'Comparison of Apache Kafka Streams, Apache Flink, and Apache Spark Structured Streaming for real-time data processing.' },
            { type: 'text', name: 'Stream Processing', content: 'Stream processing handles unbounded data in real-time. Windowing (tumbling, sliding, session) groups events. Watermarks handle late data. Exactly-once semantics require checkpointing and idempotent sinks. Apache Flink provides advanced streaming with event-time processing.' },
            { type: 'attachment', name: 'MapReduce Exercises' },
        ]},
        { title: 'Service Discovery and Configuration', description: 'Service registries, DNS-based discovery, and distributed configuration.', units: [
            { type: 'text', name: 'Service Discovery Patterns', content: 'Client-side discovery: clients query a registry (Eureka) and load-balance. Server-side discovery: a load balancer queries the registry (AWS ELB). DNS-based: services register DNS records. Kubernetes uses DNS and kube-proxy for built-in service discovery.' },
            { type: 'text', name: 'Distributed Configuration', content: 'Centralized config stores (etcd, Consul, ZooKeeper) provide consistent configuration across services. Features: key-value storage, watches for changes, distributed locking, leader election. Config changes propagate without redeployment.' },
            { type: 'online', name: 'Service Discovery Tools', description: 'Comparison of service discovery tools: Consul, etcd, ZooKeeper, and Kubernetes native discovery.' },
            { type: 'text', name: 'ZooKeeper and etcd', content: 'ZooKeeper provides a hierarchical key-value store with watches, ephemeral nodes, and sequential nodes. Used for leader election, distributed locks, and configuration. etcd uses Raft consensus, simpler API, and is the backbone of Kubernetes. Both guarantee linearizability.' },
            { type: 'attachment', name: 'Service Discovery Lab' },
        ]},
        { title: 'Load Balancing and Caching', description: 'Load distribution strategies and distributed caching systems.', units: [
            { type: 'text', name: 'Load Balancing Algorithms', content: 'Round-robin distributes evenly. Weighted round-robin accounts for capacity differences. Least connections sends to the least busy server. Consistent hashing ensures the same client reaches the same server (session affinity). Power of two choices samples randomly for balance.' },
            { type: 'text', name: 'Distributed Caching', content: 'Memcached provides distributed in-memory key-value caching. Redis adds data structures, persistence, and pub/sub. Cache-aside: application manages cache. Write-through: cache writes synchronously to database. Cache invalidation is the hardest problem in caching.' },
            { type: 'online', name: 'Caching Strategies Guide', description: 'Best practices for distributed caching: TTL policies, eviction strategies, cache stampede prevention, and consistency patterns.' },
            { type: 'text', name: 'CDN and Edge Caching', content: 'CDNs (Cloudflare, CloudFront) cache content at edge locations near users. Static content (images, CSS, JS) is cached easily. Dynamic content caching uses cache keys and Vary headers. Edge computing extends CDNs with computation at edge nodes.' },
            { type: 'attachment', name: 'Caching Exercises' },
        ]},
        { title: 'Distributed Messaging Systems', description: 'Message brokers, event streaming, and pub/sub patterns.', units: [
            { type: 'text', name: 'Apache Kafka Architecture', content: 'Kafka stores messages in topics partitioned across brokers. Producers append to partitions. Consumers in consumer groups each read distinct partitions. ZooKeeper (being replaced by KRaft) manages cluster metadata. Kafka guarantees ordering within partitions and at-least-once delivery.' },
            { type: 'text', name: 'Message Queue vs Event Stream', content: 'Message queues (RabbitMQ) deliver messages to one consumer (competing consumers pattern). Event streams (Kafka) retain events for replay and multiple consumers. Queues are for work distribution; streams are for event sourcing and analytics pipelines.' },
            { type: 'online', name: 'Kafka Tutorial', description: 'Hands-on Kafka tutorial covering producers, consumers, topics, partitions, consumer groups, and stream processing.' },
            { type: 'text', name: 'Exactly-Once Semantics', content: 'At-most-once: fire and forget (may lose messages). At-least-once: retry on failure (may duplicate). Exactly-once: idempotent producers + transactional consumers. Kafka supports exactly-once with idempotent producers and transactional API.' },
            { type: 'attachment', name: 'Messaging Patterns Reference' },
        ]},
        { title: 'Observability in Distributed Systems', description: 'Logging, metrics, tracing, and debugging distributed applications.', units: [
            { type: 'text', name: 'Three Pillars of Observability', content: 'Logs capture discrete events (structured logging with JSON). Metrics aggregate numerical measurements over time (counters, gauges, histograms). Traces follow requests across services (spans with trace IDs). Together they enable understanding system behavior.' },
            { type: 'text', name: 'Distributed Tracing', content: 'OpenTelemetry provides vendor-neutral APIs for tracing. Each request gets a trace ID propagated across services. Spans represent operations within a trace. Jaeger and Zipkin visualize traces as waterfalls. Traces identify latency bottlenecks in microservices.' },
            { type: 'online', name: 'Observability Stack Guide', description: 'Guide to setting up an observability stack with Prometheus (metrics), Grafana (dashboards), Loki (logs), and Jaeger (traces).' },
            { type: 'text', name: 'SLIs, SLOs, and Error Budgets', content: 'Service Level Indicators (SLIs) measure service quality (latency, availability). Service Level Objectives (SLOs) set targets (99.9% availability). Error budgets = 1 - SLO, allowing controlled risk-taking. When budget is depleted, prioritize reliability over features.' },
            { type: 'attachment', name: 'Observability Checklist' },
        ]},
        { title: 'Cloud-Native Architecture', description: 'Containers, Kubernetes, and cloud-native design principles.', units: [
            { type: 'text', name: 'Container Orchestration with Kubernetes', content: 'Kubernetes manages containerized applications: Pods run containers, Deployments manage replicas, Services provide networking, ConfigMaps/Secrets manage configuration. The control plane (API server, etcd, scheduler, controller manager) coordinates worker nodes.' },
            { type: 'text', name: 'Twelve-Factor App', content: 'The twelve factors: codebase in version control, explicit dependencies, config in environment, backing services as attached resources, strict build/release/run separation, stateless processes, port binding, concurrency via process model, disposability, dev/prod parity, logs as streams, admin processes.' },
            { type: 'online', name: 'Kubernetes Workshop', description: 'Hands-on workshop for deploying, scaling, and managing applications on Kubernetes with kubectl and Helm charts.' },
            { type: 'text', name: 'Serverless Computing', content: 'Serverless (FaaS) executes functions in response to events. No server management. Pay per invocation. AWS Lambda, Google Cloud Functions, Azure Functions. Cold starts add latency. Best for event-driven, sporadic workloads. Not suited for long-running or stateful processing.' },
            { type: 'attachment', name: 'Cloud-Native Design Patterns' },
        ]},
        { title: 'Distributed Security', description: 'Authentication, authorization, and secure communication in distributed systems.', units: [
            { type: 'text', name: 'Mutual TLS', content: 'mTLS authenticates both client and server using X.509 certificates. The service mesh (Istio) automates certificate management and rotation. mTLS encrypts inter-service communication. Certificate authorities (CAs) issue and verify certificates in the trust chain.' },
            { type: 'text', name: 'OAuth2 and JWT', content: 'OAuth2 delegates authorization: authorization code, client credentials, and device code flows. JWTs (JSON Web Tokens) carry claims signed by the issuer. Access tokens authorize API calls. Refresh tokens obtain new access tokens. OIDC adds authentication on top of OAuth2.' },
            { type: 'online', name: 'Distributed Security Patterns', description: 'Security patterns for microservices: API gateway authentication, token relay, service-to-service auth, and secrets management.' },
            { type: 'text', name: 'Secrets Management', content: 'HashiCorp Vault stores and manages secrets centrally. Dynamic secrets are generated on demand and auto-expire. Encryption as a service protects data at rest. Kubernetes Secrets store sensitive data (base64 encoded, not encrypted by default). External secret operators integrate Vault with K8s.' },
            { type: 'attachment', name: 'Security Architecture Guide' },
        ]},
        { title: 'Distributed Databases', description: 'NewSQL, multi-region databases, and global consistency.', units: [
            { type: 'text', name: 'CockroachDB Architecture', content: 'CockroachDB is a distributed SQL database using Raft consensus per range. Ranges automatically split and rebalance. SQL layer translates queries to distributed KV operations. Supports serializable transactions across ranges using parallel commits and timestamp ordering.' },
            { type: 'text', name: 'Multi-Region Database Design', content: 'Multi-region databases replicate data across geographic regions. Region pinning keeps data in specific regions for compliance. Follower reads reduce read latency. Global tables replicate everywhere for fast reads. Write latency depends on quorum requirements.' },
            { type: 'online', name: 'NewSQL Database Comparison', description: 'Comparison of CockroachDB, Google Spanner, TiDB, and YugabyteDB features, consistency models, and performance.' },
            { type: 'text', name: 'Cassandra Data Modeling', content: 'Cassandra uses wide-column storage with partition keys and clustering keys. Design tables around queries (denormalize). Partition key determines data placement. Clustering key sorts within a partition. Avoid large partitions and secondary indexes for performance.' },
            { type: 'attachment', name: 'Distributed Database Lab' },
        ]},
        { title: 'Distributed Algorithms', description: 'Leader election, mutual exclusion, and distributed snapshots.', units: [
            { type: 'text', name: 'Leader Election Algorithms', content: 'Bully algorithm: highest-ID node wins, O(n^2) messages. Ring algorithm: election message circulates, O(n) messages. Raft leader election: candidates request votes with randomized timeouts to prevent ties. Leader election is fundamental for coordinating distributed systems.' },
            { type: 'text', name: 'Chandy-Lamport Snapshot', content: 'The Chandy-Lamport algorithm captures a consistent global snapshot without stopping the system. The initiator records its state and sends markers on all channels. On receiving a marker, a process records its state and channel state. The snapshot captures a consistent cut.' },
            { type: 'online', name: 'Distributed Algorithm Animations', description: 'Animated visualizations of leader election, mutual exclusion, and global snapshot algorithms in distributed systems.' },
            { type: 'text', name: 'Distributed Mutual Exclusion', content: 'Lamport algorithm uses logical clocks and message ordering. Ricart-Agrawala reduces messages using deferred replies. Token-based algorithms circulate a token; only the holder enters the critical section. Maekawa uses voting sets for quorum-based exclusion.' },
            { type: 'attachment', name: 'Distributed Algorithms Exercises' },
        ]},
        { title: 'System Design Case Studies', description: 'Designing real-world distributed systems: URL shortener, chat, and more.', units: [
            { type: 'text', name: 'Designing a URL Shortener', content: 'Requirements: shorten URLs, redirect, analytics. Architecture: API gateway, ID generator (snowflake), key-value store (Redis + persistent DB), cache layer. Base62 encoding converts IDs to short strings. Read-heavy: optimize with caching and CDN.' },
            { type: 'text', name: 'Designing a Chat System', content: 'Requirements: one-to-one and group messaging, online presence, message history. Architecture: WebSocket servers for real-time delivery, message queue (Kafka) for reliability, NoSQL for message storage, presence service using heartbeats, push notification service for offline users.' },
            { type: 'online', name: 'System Design Interview Guide', description: 'Framework for approaching system design problems: requirements, estimation, high-level design, deep dive, and trade-offs.' },
            { type: 'text', name: 'Designing a Rate Limiter', content: 'Algorithms: token bucket (smooth rate), sliding window log (exact), sliding window counter (approximate). Distributed rate limiting uses Redis for shared state. Fixed window has burst issues at boundaries. Rate limit headers inform clients of remaining quota.' },
            { type: 'attachment', name: 'System Design Templates' },
        ]},
    ],
    exercises: {
        programming: [
            { title: 'Raft Consensus Implementation', problemStatement: 'Implement the Raft consensus algorithm with leader election, log replication, and commit handling. Test with simulated network partitions.' },
            { title: 'Distributed Key-Value Store', problemStatement: 'Build a distributed key-value store with consistent hashing, replication factor configuration, and quorum reads/writes.' },
            { title: 'Vector Clock Library', problemStatement: 'Implement a vector clock library supporting increment, merge, compare (concurrent, before, after), and serialization/deserialization.' },
            { title: 'Two-Phase Commit Coordinator', problemStatement: 'Implement a 2PC coordinator and participant protocol. Handle participant failures, coordinator recovery from logs, and timeout-based abort.' },
            { title: 'Service Discovery Registry', problemStatement: 'Build a service discovery registry supporting registration, heartbeat-based health checking, DNS-compatible queries, and watch notifications for changes.' },
            { title: 'Saga Orchestrator', problemStatement: 'Implement a saga orchestrator that coordinates a multi-step order workflow (payment, inventory, shipping) with compensating transactions on failure.' },
            { title: 'Gossip Protocol', problemStatement: 'Implement a gossip protocol for membership management and failure detection. Nodes periodically exchange state with random peers. Detect and remove failed nodes.' },
            { title: 'Consistent Hashing Ring', problemStatement: 'Implement a consistent hashing ring with virtual nodes, key lookup, and node addition/removal. Measure key redistribution when topology changes.' },
            { title: 'Distributed Lock Service', problemStatement: 'Build a distributed lock service using a consensus algorithm. Support lock acquisition with timeout, automatic expiration, and fencing tokens.' },
            { title: 'MapReduce Framework', problemStatement: 'Implement a simplified MapReduce framework with a coordinator that assigns map and reduce tasks to workers. Handle worker failures with task reassignment.' },
            { title: 'Circuit Breaker Pattern', problemStatement: 'Implement a circuit breaker with closed, open, and half-open states. Configure failure threshold, timeout duration, and success threshold for recovery.' },
            { title: 'Event Sourcing Store', problemStatement: 'Build an event store supporting append, read by aggregate ID, and snapshot creation. Implement event replay and projection building.' },
            { title: 'Load Balancer', problemStatement: 'Implement a load balancer supporting round-robin, weighted round-robin, least connections, and consistent hashing algorithms. Include health checking.' },
            { title: 'Distributed Rate Limiter', problemStatement: 'Implement a distributed rate limiter using the token bucket algorithm with Redis as shared state. Support per-user and per-endpoint limits.' },
            { title: 'CRDT Counter', problemStatement: 'Implement a G-Counter (grow-only) and PN-Counter (positive-negative) CRDT. Support increment, decrement, merge, and value operations across replicas.' },
            { title: 'Leader Election Service', problemStatement: 'Implement a leader election service using a distributed lock. Support leader heartbeats, automatic failover, and leader change notifications.' },
            { title: 'Chandy-Lamport Snapshot', problemStatement: 'Implement the Chandy-Lamport distributed snapshot algorithm. Simulate processes exchanging messages and capture a consistent global state.' },
            { title: 'Message Broker', problemStatement: 'Build a message broker supporting publish-subscribe with topics, consumer groups, message persistence, and at-least-once delivery guarantees.' },
            { title: 'Distributed Cache', problemStatement: 'Implement a distributed cache with consistent hashing for key distribution, TTL-based expiration, LRU eviction, and cache coherence notifications.' },
            { title: 'gRPC Service', problemStatement: 'Build a gRPC service with Protocol Buffers for a task management API. Implement unary and server-streaming RPCs with error handling and interceptors.' },
            { title: 'Retry with Backoff', problemStatement: 'Implement a configurable retry library with exponential backoff, jitter, maximum retries, and circuit breaker integration. Support idempotency keys.' },
            { title: 'Distributed Tracing', problemStatement: 'Implement distributed tracing with trace ID propagation, span creation, parent-child relationships, and trace export to a collector.' },
            { title: 'Quorum-Based Replication', problemStatement: 'Implement a replicated data store with configurable read and write quorum. Demonstrate the W + R > N consistency guarantee.' },
            { title: 'Kubernetes Operator', problemStatement: 'Build a simple Kubernetes operator using the Java client library. Watch for custom resource events and reconcile desired state.' },
            { title: 'Health Check Aggregator', problemStatement: 'Build a service health checker that monitors multiple services, aggregates health status, and exposes a unified health endpoint with dependency information.' },
            { title: 'Idempotent API', problemStatement: 'Implement an idempotent REST API using idempotency keys. Store request/response mappings and return cached responses for duplicate requests.' },
            { title: 'Sidecar Proxy', problemStatement: 'Implement a simple sidecar proxy that intercepts HTTP traffic, adds retry logic, circuit breaking, and request logging for a target service.' },
            { title: 'Merkle Tree', problemStatement: 'Implement a Merkle tree for efficient data synchronization. Support building from data blocks, verification of individual blocks, and identifying differing subtrees.' },
            { title: 'Bulkhead Pattern', problemStatement: 'Implement the bulkhead pattern with thread pool isolation. Limit concurrent calls per dependency to prevent cascading failures from slow services.' },
            { title: 'Distributed Task Queue', problemStatement: 'Build a distributed task queue with priority-based scheduling, retry on failure, dead letter queue, and worker scaling.' },
            { title: 'Feature Flag Service', problemStatement: 'Implement a feature flag service supporting boolean flags, percentage rollouts, user targeting, and real-time flag updates via SSE.' },
            { title: 'Blue-Green Deployment Controller', problemStatement: 'Build a deployment controller that manages blue-green deployments. Support traffic switching, health verification, and automatic rollback on failure.' },
            { title: 'Lamport Clock Implementation', problemStatement: 'Implement Lamport logical clocks for a set of simulated processes. Demonstrate event ordering and the happened-before relationship.' },
            { title: 'Sharded Counter', problemStatement: 'Implement a sharded counter that distributes increments across shards for high throughput, then aggregates for reads.' },
            { title: 'Chaos Engineering Tool', problemStatement: 'Build a chaos engineering tool that injects failures: network latency, random errors, process crashes, and disk full conditions into a distributed system.' },
            { title: 'API Gateway', problemStatement: 'Implement an API gateway with routing, JWT authentication, rate limiting, request transformation, and response caching.' },
            { title: 'Config Service', problemStatement: 'Build a configuration service storing key-value pairs with namespaces, versioning, watch notifications, and encrypted secret values.' },
            { title: 'Outbox Pattern', problemStatement: 'Implement the transactional outbox pattern: write events to an outbox table in the same transaction as data changes, then relay events to a message broker.' },
            { title: 'Service Registry Client', problemStatement: 'Implement a service registry client with registration, heartbeat renewal, self-preservation mode, and client-side load balancing with caching.' },
            { title: 'Distributed Scheduler', problemStatement: 'Build a distributed job scheduler using leader election. Support cron-like scheduling, single-execution guarantees, and job persistence.' },
        ],
        text: [
            { title: 'CAP vs PACELC', problemStatement: 'Compare the CAP theorem with the PACELC model. Explain what PACELC adds and how it better characterizes distributed system trade-offs with real examples.' },
            { title: 'Microservices vs Monolith', problemStatement: 'When should a team choose microservices over a monolith? Discuss team size, deployment independence, data consistency, operational complexity, and migration strategies.' },
            { title: 'Consensus Algorithm Comparison', problemStatement: 'Compare Paxos, Raft, and PBFT consensus algorithms. Discuss their assumptions, message complexity, fault tolerance, and practical implementations.' },
            { title: 'Event-Driven Architecture Trade-offs', problemStatement: 'Analyze the benefits and challenges of event-driven architecture: temporal decoupling, eventual consistency, debugging complexity, and event schema evolution.' },
            { title: 'Distributed System Failures', problemStatement: 'Analyze three real-world distributed system failures (AWS S3 outage, GitHub database incident, Cloudflare outage). Identify root causes and lessons learned.' },
        ],
        modeling: [
            { title: 'Microservices Architecture', problemStatement: 'Create a class diagram showing Service, API Gateway, Service Registry, Config Server, and Message Broker components with their interactions.', diagramType: 'ClassDiagram' },
            { title: 'Raft Consensus Flow', problemStatement: 'Design an activity diagram showing the Raft leader election process: timeout, candidate state, vote request, vote collection, and leader establishment.', diagramType: 'ActivityDiagram' },
            { title: 'Saga Orchestration', problemStatement: 'Model an activity diagram for a saga-based order processing: payment, inventory, shipping with compensation actions on failure.', diagramType: 'ActivityDiagram' },
            { title: 'Service Mesh Architecture', problemStatement: 'Create a class diagram showing Service, Sidecar Proxy, Control Plane, Data Plane, and Certificate Authority components in a service mesh.', diagramType: 'ClassDiagram' },
            { type: 'ClassDiagram', title: 'Event Sourcing Model', problemStatement: 'Design a class diagram for an event sourcing system with Event Store, Aggregate, Command, Event, Projection, and Snapshot classes.', diagramType: 'ClassDiagram' },
        ],
        quiz: [
            { title: 'Consensus Quiz', questions: [
                { type: 'multiple-choice', title: 'Raft Leader', text: 'In Raft, what triggers a new leader election?', points: 5, singleChoice: true, answerOptions: [{ text: 'Election timeout expiration', isCorrect: true }, { text: 'New node joining', isCorrect: false }, { text: 'Client request', isCorrect: false }, { text: 'Log compaction', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Byzantine Faults', text: 'How many nodes does PBFT need to tolerate f Byzantine faults?', points: 5, singleChoice: true, answerOptions: [{ text: '3f + 1', isCorrect: true }, { text: '2f + 1', isCorrect: false }, { text: 'f + 1', isCorrect: false }, { text: '4f + 1', isCorrect: false }] },
            ]},
            { title: 'Replication Quiz', questions: [
                { type: 'multiple-choice', title: 'Quorum', text: 'For a system with N=5, what are the minimum W and R for strong consistency?', points: 5, singleChoice: true, answerOptions: [{ text: 'W=3, R=3 (W+R > N)', isCorrect: true }, { text: 'W=1, R=1', isCorrect: false }, { text: 'W=5, R=5', isCorrect: false }, { text: 'W=2, R=2', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Consistency', text: 'Which consistency model allows reading stale data that eventually converges?', points: 5, singleChoice: true, answerOptions: [{ text: 'Eventual consistency', isCorrect: true }, { text: 'Linearizability', isCorrect: false }, { text: 'Serializability', isCorrect: false }, { text: 'Strict consistency', isCorrect: false }] },
            ]},
            { title: 'Architecture Quiz', questions: [
                { type: 'multiple-choice', title: 'Service Discovery', text: 'Which tool is used as the configuration store for Kubernetes?', points: 5, singleChoice: true, answerOptions: [{ text: 'etcd', isCorrect: true }, { text: 'Redis', isCorrect: false }, { text: 'Consul', isCorrect: false }, { text: 'ZooKeeper', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Circuit Breaker', text: 'What does a circuit breaker do when it is in the open state?', points: 5, singleChoice: true, answerOptions: [{ text: 'Immediately fails requests without calling the service', isCorrect: true }, { text: 'Routes traffic to a backup service', isCorrect: false }, { text: 'Retries the request multiple times', isCorrect: false }, { text: 'Queues requests for later processing', isCorrect: false }] },
            ]},
        ],
        fileUpload: [
            { title: 'Distributed System Design Document', problemStatement: 'Upload a system design document for a distributed application including architecture diagram, data flow, consistency requirements, and failure handling strategy.' },
            { title: 'Chaos Engineering Report', problemStatement: 'Upload a report documenting chaos engineering experiments: failure injection scenarios, observed behavior, recovery metrics, and improvement recommendations.' },
        ],
    },
    faqs: [
        { title: 'What is the CAP theorem?', answer: 'CAP states a distributed system can guarantee at most two of: Consistency (all nodes see the same data), Availability (every request gets a response), Partition tolerance (system works despite network splits). Since partitions are unavoidable, the real trade-off is CP vs AP.' },
        { title: 'How does Raft differ from Paxos?', answer: 'Raft was designed for understandability. It separates leader election, log replication, and safety clearly. Paxos is more general but harder to understand and implement. Raft requires a stable leader; Paxos can make progress without one. Both tolerate f failures with 2f+1 nodes.' },
        { title: 'What is eventual consistency?', answer: 'Eventual consistency means that if no new updates are made, all replicas will eventually converge to the same value. There is no bound on how long this takes. It is weaker than strong consistency but enables higher availability. Used in DNS, Cassandra, and DynamoDB.' },
        { title: 'When should I use a message queue vs direct API calls?', answer: 'Use message queues for: asynchronous processing, decoupling services, handling load spikes (buffering), and when exact timing does not matter. Use direct API calls for: synchronous request-response, low-latency requirements, and when the caller needs an immediate result.' },
        { title: 'What is the difference between 2PC and Saga?', answer: '2PC provides atomic distributed transactions but is blocking and synchronous. Sagas break the transaction into local steps with compensating actions, providing eventual consistency without distributed locks. Sagas are more available but harder to reason about.' },
        { title: 'How does consistent hashing work?', answer: 'Both keys and nodes are mapped to positions on a hash ring. Each key is assigned to the next node clockwise. Adding a node only moves keys between the new node and its predecessor. Virtual nodes improve balance. Used in DynamoDB, Cassandra, and CDNs.' },
        { title: 'What is a CRDT?', answer: 'Conflict-free Replicated Data Types merge concurrent updates automatically without coordination. G-Counter only grows. PN-Counter supports increment/decrement. G-Set only adds elements. OR-Set supports add and remove. CRDTs enable strong eventual consistency.' },
        { title: 'How do vector clocks detect conflicts?', answer: 'Vector clocks track causality with a vector of counters (one per node). If one vector dominates another (all entries >=), the events are causally ordered. If neither dominates, the events are concurrent (conflict). Used in Dynamo for conflict detection.' },
        { title: 'What is the split-brain problem?', answer: 'Split-brain occurs when a network partition divides a cluster into two groups, each believing it is the sole active group. Both accept writes, causing data divergence. Solutions: quorum-based decisions, fencing tokens, and STONITH (Shoot The Other Node In The Head).' },
        { title: 'How does a circuit breaker work?', answer: 'Closed state: requests pass through normally. After a failure threshold, transitions to Open state: all requests fail immediately. After a timeout, transitions to Half-Open: a few test requests are allowed. If they succeed, back to Closed; if they fail, back to Open.' },
        { title: 'What is the difference between horizontal and vertical scaling?', answer: 'Vertical scaling (scale up): add more CPU/RAM/disk to a single machine. Limited by hardware caps. Horizontal scaling (scale out): add more machines. Requires distributed system design (partitioning, replication). Horizontal scaling is theoretically unlimited.' },
        { title: 'How does Kubernetes handle service discovery?', answer: 'Kubernetes uses DNS: each Service gets a DNS name (service.namespace.svc.cluster.local). kube-proxy configures iptables/IPVS rules to load-balance traffic to pod endpoints. CoreDNS resolves service names. Headless services return pod IPs directly for client-side load balancing.' },
        { title: 'What is idempotency and why is it important?', answer: 'An operation is idempotent if executing it multiple times produces the same result as executing it once. Important in distributed systems because retries can cause duplicate execution. Use idempotency keys, conditional writes, or naturally idempotent operations (PUT, DELETE).' },
        { title: 'How do I handle distributed system debugging?', answer: 'Use distributed tracing (Jaeger/Zipkin) to follow requests across services. Correlate logs with trace IDs. Monitor metrics dashboards. Reproduce issues in staging. Use chaos engineering to test failure scenarios. Structured logging with consistent field names enables cross-service queries.' },
        { title: 'What is the Saga pattern?', answer: 'Sagas decompose distributed transactions into local transactions with compensating actions. If step 3 fails, compensate steps 2 and 1. Choreography: services react to events. Orchestration: a coordinator drives the flow. Sagas provide eventual consistency without distributed locks.' },
        { title: 'What is event sourcing?', answer: 'Event sourcing stores all state changes as immutable events instead of overwriting current state. Current state is derived by replaying events. Benefits: complete audit trail, temporal queries, easy debugging. Challenges: event schema evolution, performance of long event streams, eventual consistency.' },
        { title: 'How do I choose between REST and gRPC?', answer: 'REST: widely supported, human-readable (JSON), good for public APIs, browser-friendly. gRPC: binary serialization (faster), strong typing via protobuf, native streaming, code generation. Use REST for external APIs and gRPC for internal service-to-service communication.' },
        { title: 'What is the outbox pattern?', answer: 'The outbox pattern writes events to an outbox table in the same database transaction as data changes. A separate process reads the outbox and publishes events to a message broker. This ensures data consistency and reliable event delivery without distributed transactions.' },
        { title: 'How do I prevent cascading failures?', answer: 'Use circuit breakers to stop calling failing services. Set timeouts on all remote calls. Use bulkheads to isolate failures. Implement retry with backoff and jitter. Degrade gracefully (return cached data, default values). Monitor and alert on error rates.' },
        { title: 'What is the FLP impossibility result?', answer: 'Fischer, Lynch, and Paterson proved that in an asynchronous system with even one crash failure, no deterministic algorithm can guarantee consensus. Practical systems work around this using timeouts (partial synchrony), randomization, or failure detectors.' },
    ],
    exerciseMessages: [
        'I am stuck on the Raft leader election exercise. My candidate keeps timing out before collecting enough votes. Does the election timeout need to be randomized?',
        'For the Paxos exercise, do we need to handle the case where a proposer crashes after sending prepare but before sending accept?',
        'Can someone clarify what the expected output should be for the vector clock merge operation in Exercise 3? I get a different result when two concurrent events happen on the same node.',
        'My RPC implementation passes the local tests but fails when the grader introduces network delays. How do I handle RPC timeouts properly without breaking idempotency?',
        'In the two-phase commit exercise, should the coordinator log its decision before or after sending the commit message to participants?',
        'Has anyone figured out the sharding exercise? I am not sure how to handle re-sharding when a new node joins the consistent hashing ring.',
        'The CAP theorem exercise asks us to demonstrate a scenario where we sacrifice availability for consistency. Is it enough to show a node rejecting reads during a partition?',
        'I keep getting a deadlock in the distributed mutex exercise. I think my Lamport clock implementation has an off-by-one error when comparing timestamps.',
        'For the message queue exercise, how do we guarantee exactly-once delivery? The instructions say we cannot use deduplication tables.',
        'My Raft log replication is not working correctly. The follower accepts entries but the commit index never advances. Do I need to wait for a majority before updating commitIndex?',
        'Question about the fault tolerance exercise: when we inject a node crash, should the system recover automatically or do we need to manually trigger a recovery procedure?',
        'In the distributed transaction exercise, I implemented saga pattern but my compensating transactions are executing out of order. How do I enforce the correct rollback sequence?',
        'Can someone explain why my consistent hashing implementation produces uneven load distribution? I am using MD5 for the hash function with 3 virtual nodes per server.',
        'The replication exercise says to implement chain replication. Is the tail allowed to serve reads directly or does it need to go through the head?',
        'I am confused about the Lamport timestamps exercise. If process A sends a message to process B, should B increment its clock before or after updating it with the received timestamp?',
        'My gRPC service for the RPC exercise keeps throwing UNAVAILABLE errors under load. Do I need to implement client-side load balancing or is round-robin on the server enough?',
        'For the Byzantine fault tolerance exercise, is the requirement to tolerate f faults with 3f+1 nodes or 2f+1 nodes? The lecture slides and the exercise description seem to differ.',
        'How do I properly implement read-your-writes consistency in the replication exercise? My implementation works for single-client tests but fails with concurrent clients.',
        'The distributed snapshot exercise asks for a consistent global state. My Chandy-Lamport implementation does not terminate because some channels never receive a marker. Is there a timeout mechanism?',
        'In the vector clocks exercise, how do I detect if two events are concurrent? I compare element-wise but I am not sure about the condition when one vector has entries the other does not.',
        'My Raft implementation handles leader election fine but fails the log compaction test. How do I implement snapshotting without blocking the state machine?',
        'For the distributed hash table exercise, which Chord finger table entry should I use when the key falls exactly on a node ID?',
        'I implemented the anti-entropy protocol for the eventual consistency exercise but my Merkle tree comparison is too slow. Any tips on optimizing the tree traversal?',
        'The gossip protocol exercise expects convergence within 10 rounds but my implementation takes 15. Should I increase the fanout or use a different peer selection strategy?',
        'Can someone help with the MapReduce exercise? My reduce function receives keys out of order and the output does not match the expected result.',
        'In the distributed locking exercise, how do I handle lock expiration? If a client holds a lock and crashes, the other clients wait forever.',
        'My implementation of the Bully election algorithm keeps electing the wrong coordinator. I think the issue is with how I compare process IDs during the election phase.',
        'For the CRDTs exercise, I implemented a G-Counter but the merge operation produces incorrect totals when nodes rejoin after a network partition. What am I missing?',
        'The exercise on distributed transactions asks us to implement 2PC with a timeout. How long should the timeout be, and what should participants do if the coordinator does not respond?',
        'I am struggling with the lease-based locking exercise. My lease renewal keeps racing with the expiration check on the server. Is there a standard way to handle clock skew?',
        'In the stream processing exercise, how do I handle late-arriving events that fall outside the current window? Should I drop them or recompute the window?',
        'My Paxos implementation passes the basic tests but fails when two proposers compete simultaneously. I think my proposal numbers are not unique across proposers.',
        'For the consensus exercise, what is the difference between Multi-Paxos and Raft in terms of the guarantees they provide? The exercise description mentions both.',
        'The partitioning exercise requires us to implement range-based sharding. How do I handle hot spots when all writes go to the same partition?',
        'Has anyone completed the failure detector exercise? I am implementing a phi-accrual failure detector but my suspicion level calculation seems off.',
        'In the distributed file system exercise, how should I handle the case where a chunk server fails during a write operation? Do I need to implement write-ahead logging?',
        'My vector clock implementation for the causal ordering exercise does not detect causal violations. I think the issue is in how I merge clocks during message delivery.',
        'For the load balancing exercise, consistent hashing with bounded loads is required. How do I enforce the load bound without causing too many key relocations?',
        'The quorum exercise asks for tunable consistency. If I set W=2 and R=2 with N=3, does that guarantee strong consistency or just eventual consistency?',
        'I cannot get the distributed barrier exercise to work. My implementation using ZooKeeper ephemeral nodes sometimes misses a participant when it reconnects quickly.',
        'In the data replication exercise, my multi-leader setup has write conflicts. The exercise says to use last-writer-wins but my timestamps are not synchronized across nodes.',
        'My implementation of the Raft pre-vote extension prevents disruptions from partitioned nodes, but now legitimate elections take longer. Is there a way to tune this?',
        'For the event sourcing exercise, how do I handle the projection rebuild when the event store has millions of events? Snapshotting is mentioned but not explained.',
        'The distributed deadlock detection exercise requires implementing a wait-for graph across nodes. How do I handle the case where the graph information is stale?',
        'I am having trouble with the total order broadcast exercise. My implementation using Lamport clocks does not break ties consistently when two messages have the same timestamp.',
        'In the consensus number exercise, we need to prove that compare-and-swap has infinite consensus number. Is a constructive proof required or is a contradiction argument acceptable?',
        'My chain replication exercise fails when the tail node crashes. How does the system reconfigure the chain, and who becomes the new tail?',
        'For the idempotency exercise, I store request IDs in a hash map, but the map grows unboundedly. How do I garbage collect old entries without losing idempotency guarantees?',
        'The distributed cache exercise asks us to implement a cache invalidation protocol. Should I use a push-based or pull-based approach for notifying other nodes?',
        'Can someone explain how to implement the protocol buffer serialization for the RPC exercise? I keep getting version mismatch errors between client and server stubs.',
    ],
    channelMessages: [
        'Can someone explain the difference between strong consistency and linearizability?',
        'My Raft implementation gets stuck when the leader fails during log replication. Any debugging tips?',
        'How do I decide between Kafka and RabbitMQ for my microservices project?',
        'What is the practical difference between at-least-once and exactly-once delivery?',
        'How does Netflix handle service failures across their microservices architecture?',
        'Can someone walk through the Chandy-Lamport snapshot algorithm with an example?',
        'How do I implement graceful degradation when a downstream service is unavailable?',
        'What is the difference between a partition key and a clustering key in Cassandra?',
        'How do I test distributed systems? Are there good frameworks for fault injection?',
        'Can someone explain why 2PC is considered blocking and what alternatives exist?',
        'How does Kubernetes handle rolling updates without downtime?',
        'What is the difference between event sourcing and change data capture?',
        'How do I handle schema evolution in event-driven architectures?',
        'My distributed cache has inconsistency issues after node failures. Should I use write-through or write-behind?',
        'What is the difference between a service mesh and an API gateway?',
    ],
};
