export default {
    topic: 'Operating Systems',
    title: 'Operating Systems Concepts',
    shortNamePrefix: 'OS',
    description: 'This course covers the fundamental concepts of operating systems including process management, memory management, file systems, I/O systems, and virtualization. Students learn how modern OS kernels schedule processes, manage virtual memory, and provide abstractions for hardware resources.',
    lectures: [
        { title: 'Introduction to Operating Systems', description: 'History, structure, and role of operating systems in computing.', units: [
            { type: 'text', name: 'What is an Operating System?', content: 'An operating system is software that manages hardware resources and provides services for application programs. It acts as an intermediary between users and hardware, providing abstractions like processes, files, and virtual memory that simplify programming.' },
            { type: 'text', name: 'OS Architecture: Monolithic vs Microkernel', content: 'Monolithic kernels (Linux) run all OS services in kernel space for performance. Microkernels (Minix, L4) run minimal code in kernel space with services in user space for reliability. Hybrid kernels (Windows NT, macOS XNU) combine both approaches.' },
            { type: 'online', name: 'Operating System Timeline', description: 'Interactive timeline of operating system evolution from batch processing to modern cloud-native OS designs.' },
            { type: 'text', name: 'System Calls and API', content: 'System calls provide the interface between user programs and the kernel. POSIX defines standard system calls: open, read, write, close for files; fork, exec, wait for processes; mmap, brk for memory. The C library wraps system calls for convenience.' },
            { type: 'attachment', name: 'OS Concepts Overview' },
        ]},
        { title: 'Process Management', description: 'Process creation, states, scheduling, and inter-process communication.', units: [
            { type: 'text', name: 'Process Lifecycle', content: 'A process transitions through states: new, ready, running, waiting, terminated. fork() creates a child process. exec() replaces the process image. wait() collects child exit status. The PCB (Process Control Block) stores process state, registers, and scheduling info.' },
            { type: 'text', name: 'Context Switching', content: 'Context switching saves the state of the running process and loads the state of the next process. It involves saving/restoring registers, updating the page table base register, and flushing TLB entries. Context switches are expensive (1-10 microseconds).' },
            { type: 'online', name: 'Process States Simulator', description: 'Interactive simulator showing process state transitions with scheduling events, I/O operations, and system calls.' },
            { type: 'text', name: 'Inter-Process Communication', content: 'IPC mechanisms include pipes (unidirectional byte streams), message queues (structured messages), shared memory (fastest, needs synchronization), sockets (network or local), and signals (asynchronous notifications). Each has different performance and complexity trade-offs.' },
            { type: 'attachment', name: 'Process Management Lab Guide' },
        ]},
        { title: 'CPU Scheduling', description: 'Scheduling algorithms, criteria, and real-time scheduling.', units: [
            { type: 'text', name: 'Scheduling Algorithms', content: 'FCFS (First Come First Served) is simple but has convoy effect. SJF (Shortest Job First) minimizes average waiting time but needs prediction. Round Robin uses time quantum for fairness. Priority scheduling can cause starvation, solved by aging.' },
            { type: 'text', name: 'Multilevel Feedback Queue', content: 'MLFQ uses multiple queues with different priorities. New processes start at highest priority. CPU-bound processes move to lower queues. I/O-bound processes stay at higher priorities. Periodic boosting prevents starvation. Used in Linux CFS and Windows schedulers.' },
            { type: 'online', name: 'Scheduling Simulator', description: 'Simulate different CPU scheduling algorithms with configurable process arrival times, burst lengths, and time quantum.' },
            { type: 'text', name: 'Real-Time Scheduling', content: 'Hard real-time systems must meet deadlines absolutely (pacemakers, ABS). Soft real-time allows occasional misses (video streaming). Rate Monotonic assigns priority by period. Earliest Deadline First is optimal for single-processor systems.' },
            { type: 'attachment', name: 'Scheduling Problems Set' },
        ]},
        { title: 'Threads and Concurrency', description: 'Thread models, synchronization primitives, and concurrent programming.', units: [
            { type: 'text', name: 'Threads vs Processes', content: 'Threads share the same address space, file descriptors, and heap within a process but have their own stack and registers. Thread creation is faster than process creation. Pthreads is the POSIX threading API. Java uses java.lang.Thread and ExecutorService.' },
            { type: 'text', name: 'Synchronization Primitives', content: 'Mutexes provide mutual exclusion for critical sections. Semaphores generalize mutexes with a counter. Condition variables enable waiting for specific conditions. Read-write locks allow concurrent readers but exclusive writers. Barriers synchronize thread groups.' },
            { type: 'online', name: 'Concurrency Visualization', description: 'Visual demonstration of race conditions, deadlocks, and how synchronization primitives prevent them.' },
            { type: 'text', name: 'Classic Synchronization Problems', content: 'Producer-Consumer uses a bounded buffer with semaphores. Readers-Writers allows concurrent reads with exclusive writes. Dining Philosophers illustrates deadlock with resource ordering solutions. These problems model real concurrency challenges.' },
            { type: 'attachment', name: 'Concurrency Exercises' },
        ]},
        { title: 'Deadlocks', description: 'Deadlock conditions, prevention, avoidance, and detection.', units: [
            { type: 'text', name: 'Deadlock Conditions', content: 'Four necessary conditions for deadlock: mutual exclusion (resources are non-shareable), hold and wait (processes hold resources while waiting for others), no preemption (resources cannot be forcibly taken), circular wait (circular chain of waiting processes).' },
            { type: 'text', name: 'Banker\'s Algorithm', content: 'The Banker\'s Algorithm (Dijkstra) avoids deadlock by checking if resource allocation leaves the system in a safe state. A safe state has a sequence where every process can complete. It requires knowing maximum resource needs in advance.' },
            { type: 'online', name: 'Deadlock Detection Tool', description: 'Interactive tool for building resource allocation graphs and detecting deadlock cycles with step-by-step analysis.' },
            { type: 'text', name: 'Deadlock Recovery', content: 'Detection uses resource allocation graphs or wait-for graphs to find cycles. Recovery options: terminate one or more deadlocked processes, preempt resources from processes, or roll back processes to checkpoints. Each has different costs.' },
            { type: 'attachment', name: 'Deadlock Scenarios' },
        ]},
        { title: 'Memory Management Basics', description: 'Address spaces, memory allocation, and segmentation.', units: [
            { type: 'text', name: 'Address Spaces', content: 'Each process has a virtual address space divided into text (code), data (global variables), heap (dynamic allocation growing upward), and stack (function calls growing downward). The memory management unit (MMU) translates virtual to physical addresses.' },
            { type: 'text', name: 'Contiguous Memory Allocation', content: 'First-fit allocates the first large enough hole. Best-fit finds the smallest sufficient hole. Worst-fit uses the largest hole. External fragmentation wastes space between allocated blocks. Compaction eliminates external fragmentation but is expensive.' },
            { type: 'online', name: 'Memory Allocation Visualizer', description: 'Visualize first-fit, best-fit, and worst-fit allocation strategies showing fragmentation over time.' },
            { type: 'text', name: 'Segmentation', content: 'Segmentation divides memory into logical segments (code, data, stack). Each segment has a base address and limit. The segment table maps segment numbers to physical addresses. Segmentation supports sharing and protection at the logical level.' },
            { type: 'attachment', name: 'Memory Management Exercises' },
        ]},
        { title: 'Virtual Memory and Paging', description: 'Page tables, TLB, demand paging, and page replacement.', units: [
            { type: 'text', name: 'Paging Fundamentals', content: 'Paging divides virtual memory into fixed-size pages and physical memory into frames. The page table maps virtual page numbers to physical frame numbers. Multi-level page tables reduce memory overhead. x86-64 uses 4-level page tables with 4KB pages.' },
            { type: 'text', name: 'Translation Lookaside Buffer', content: 'The TLB is a hardware cache for page table entries. TLB hit avoids page table walk. TLB miss requires traversing page table levels. TLB is typically fully associative with 64-1024 entries. Context switches may require TLB flush (ASID tags avoid this).' },
            { type: 'online', name: 'Virtual Memory Simulator', description: 'Step-by-step simulation of address translation through multi-level page tables with TLB lookup.' },
            { type: 'text', name: 'Page Replacement Algorithms', content: 'FIFO replaces the oldest page but suffers Belady\'s anomaly. LRU replaces least recently used (optimal approximation). Clock algorithm uses reference bits in a circular list. Working set model tracks the active page set to prevent thrashing.' },
            { type: 'attachment', name: 'Paging Problem Set' },
        ]},
        { title: 'File Systems', description: 'File system interfaces, implementation, and directory structures.', units: [
            { type: 'text', name: 'File System Interface', content: 'Files are named persistent data containers with attributes (size, permissions, timestamps). Operations: open, close, read, write, seek, truncate. Access methods: sequential, direct, indexed. File descriptors are per-process handles to open files.' },
            { type: 'text', name: 'File System Implementation', content: 'Superblock stores file system metadata. Inodes store file metadata (size, permissions, block pointers). Directory entries map names to inode numbers. Free space tracking uses bitmaps or free lists. ext4, XFS, Btrfs, and ZFS are modern Linux file systems.' },
            { type: 'online', name: 'File System Internals', description: 'Deep dive into ext4 file system internals: superblock, group descriptors, inode tables, extent trees, and journaling.' },
            { type: 'text', name: 'Journaling and Log-Structured File Systems', content: 'Journaling (ext4, NTFS) writes metadata changes to a log before committing, enabling crash recovery. Write-ahead logging ensures consistency. Log-structured file systems (LFS) write everything sequentially for better write performance.' },
            { type: 'attachment', name: 'File System Lab' },
        ]},
        { title: 'I/O Systems', description: 'I/O hardware, device drivers, and I/O scheduling.', units: [
            { type: 'text', name: 'I/O Hardware and Software', content: 'I/O devices connect via buses (PCIe, USB, SATA). Device controllers handle low-level protocols. Device drivers translate OS requests to controller commands. I/O methods: programmed I/O (polling), interrupt-driven I/O, and DMA (Direct Memory Access).' },
            { type: 'text', name: 'Disk Scheduling Algorithms', content: 'FCFS serves requests in order. SSTF (Shortest Seek Time First) minimizes seek distance. SCAN (elevator) sweeps back and forth. C-SCAN only sweeps one direction. LOOK and C-LOOK reverse at the last request instead of the disk end.' },
            { type: 'online', name: 'Disk Scheduling Visualizer', description: 'Simulate disk head movement under different scheduling algorithms with configurable request queues.' },
            { type: 'text', name: 'RAID Storage Systems', content: 'RAID 0 stripes for performance (no redundancy). RAID 1 mirrors for reliability. RAID 5 uses distributed parity. RAID 6 uses double parity. RAID 10 combines mirroring and striping. Choose based on performance, capacity, and fault tolerance needs.' },
            { type: 'attachment', name: 'I/O Systems Reference' },
        ]},
        { title: 'Virtualization', description: 'Virtual machines, hypervisors, and containers.', units: [
            { type: 'text', name: 'Hypervisor Types', content: 'Type 1 (bare-metal) hypervisors run directly on hardware (VMware ESXi, Xen, KVM). Type 2 (hosted) run on a host OS (VirtualBox, VMware Workstation). Hardware virtualization extensions (VT-x, AMD-V) enable efficient CPU virtualization.' },
            { type: 'text', name: 'Container Virtualization', content: 'Containers share the host kernel, using namespaces for isolation (PID, network, mount, user) and cgroups for resource limits (CPU, memory, I/O). Docker packages containers. Container images are layered filesystems. Much lighter than VMs.' },
            { type: 'online', name: 'Virtualization Comparison', description: 'Side-by-side comparison of VMs and containers covering architecture, performance, isolation, and use cases.' },
            { type: 'text', name: 'Memory Virtualization', content: 'Shadow page tables maintain guest-virtual to host-physical mappings. Extended Page Tables (EPT/NPT) provide hardware-assisted two-level translation. Memory ballooning reclaims unused guest memory. KSM (Kernel Same-page Merging) deduplicates identical pages.' },
            { type: 'attachment', name: 'Virtualization Lab Guide' },
        ]},
        { title: 'Security and Protection', description: 'Access control, capabilities, and security mechanisms in OS.', units: [
            { type: 'text', name: 'Protection Mechanisms', content: 'Hardware rings (ring 0-3) enforce privilege levels. User mode restricts access to hardware and privileged instructions. Kernel mode has full access. System calls transition from user to kernel mode. Address space layout randomization (ASLR) prevents exploits.' },
            { type: 'text', name: 'Access Control Models', content: 'Discretionary access control (DAC) lets owners set permissions (Unix file permissions). Mandatory access control (MAC) enforces system-wide policies (SELinux, AppArmor). Role-based access control (RBAC) assigns permissions to roles, not users.' },
            { type: 'online', name: 'OS Security Mechanisms', description: 'Overview of operating system security features: sandboxing, capabilities, seccomp, and integrity verification.' },
            { type: 'text', name: 'Buffer Overflow Protection', content: 'Stack canaries detect buffer overflows before return. DEP/NX marks stack and heap non-executable. ASLR randomizes memory layout. Control Flow Integrity (CFI) restricts indirect branches. These defenses work in layers to prevent exploitation.' },
            { type: 'attachment', name: 'Security Exercises' },
        ]},
        { title: 'Multiprocessor Systems', description: 'SMP, NUMA, and multiprocessor scheduling.', units: [
            { type: 'text', name: 'Symmetric Multiprocessing', content: 'SMP systems have multiple identical processors sharing memory. Each CPU has its own cache. Cache coherence protocols (MESI, MOESI) ensure consistency. The OS scheduler distributes processes across CPUs. Processor affinity keeps processes on the same CPU for cache warmth.' },
            { type: 'text', name: 'NUMA Architecture', content: 'Non-Uniform Memory Access has memory local to each processor. Local memory access is faster than remote. NUMA-aware allocators prefer local memory. Linux uses per-node memory zones. Poor NUMA placement degrades performance significantly.' },
            { type: 'online', name: 'Multiprocessor Scheduling Comparison', description: 'Compare scheduling strategies for multiprocessor systems: global queue, per-CPU queues, and work-stealing approaches.' },
            { type: 'text', name: 'Spinlocks and Lock-Free Programming', content: 'Spinlocks busy-wait, suitable for short critical sections on multiprocessors. Test-and-set, compare-and-swap (CAS) are atomic hardware primitives. Lock-free data structures use CAS for thread-safe updates without locks, avoiding deadlock and priority inversion.' },
            { type: 'attachment', name: 'Multiprocessor Systems Lab' },
        ]},
        { title: 'Linux Kernel Internals', description: 'Linux process scheduler, memory management, and kernel modules.', units: [
            { type: 'text', name: 'Completely Fair Scheduler', content: 'CFS uses a red-black tree ordered by virtual runtime. Processes with less CPU time have lower vruntime and higher priority. Nice values adjust weight. CFS targets proportional fairness. The scheduler tick rebalances periodically. Group scheduling enables per-user fairness.' },
            { type: 'text', name: 'Linux Memory Management', content: 'Linux uses a buddy system for physical page allocation. Slab allocator manages kernel object caches. Copy-on-write defers page duplication. OOM killer terminates processes when memory is exhausted. /proc/meminfo shows memory statistics.' },
            { type: 'online', name: 'Linux Kernel Source Tour', description: 'Guided tour of key Linux kernel source files covering scheduler, memory management, and system call handling.' },
            { type: 'text', name: 'Kernel Modules', content: 'Loadable kernel modules extend kernel functionality at runtime. insmod/modprobe load modules. rmmod removes them. Modules access kernel APIs for device drivers, file systems, and network protocols. Module parameters customize behavior at load time.' },
            { type: 'attachment', name: 'Linux Kernel Lab' },
        ]},
        { title: 'Storage Management', description: 'Disk structure, storage hierarchy, and storage area networks.', units: [
            { type: 'text', name: 'Disk Structure and Performance', content: 'HDD components: platters, tracks, sectors, cylinders. Seek time (arm movement) dominates latency. Rotational delay averages half a revolution. Transfer rate depends on data density. SSDs use NAND flash with no seek time, random access in ~100 microseconds.' },
            { type: 'text', name: 'Storage Hierarchy', content: 'Registers (1 cycle) -> L1 cache (4 cycles) -> L2 cache (10 cycles) -> L3 cache (40 cycles) -> RAM (100 cycles) -> SSD (10K cycles) -> HDD (10M cycles) -> Network storage. Each level trades capacity for speed. Caching exploits temporal and spatial locality.' },
            { type: 'online', name: 'Storage Technologies Comparison', description: 'Comparison of HDD, SSD, NVMe, and persistent memory technologies with performance benchmarks.' },
            { type: 'text', name: 'Logical Volume Management', content: 'LVM abstracts physical storage into logical volumes. Physical volumes (PV) are grouped into volume groups (VG). Logical volumes (LV) are carved from VGs. LVM supports resizing, snapshots, mirroring, and thin provisioning.' },
            { type: 'attachment', name: 'Storage Management Guide' },
        ]},
        { title: 'Networking in the OS', description: 'Network stack, sockets API, and network namespaces.', units: [
            { type: 'text', name: 'TCP/IP Stack in the Kernel', content: 'The kernel network stack processes packets through layers: NIC driver -> network layer (IP routing) -> transport layer (TCP/UDP) -> socket buffer. Packet processing uses softirqs. NAPI reduces interrupt overhead for high-speed networking. XDP processes packets before the stack.' },
            { type: 'text', name: 'Socket Programming', content: 'The socket API provides network communication: socket() creates an endpoint, bind() assigns address, listen() marks as server, accept() accepts connections, connect() initiates connection, send/recv exchange data, close() releases. Berkeley sockets are the standard.' },
            { type: 'online', name: 'Linux Networking Internals', description: 'Deep dive into Linux kernel networking: packet flow, netfilter hooks, routing tables, and network namespaces.' },
            { type: 'text', name: 'Network Namespaces', content: 'Network namespaces provide isolated network stacks with their own interfaces, routing tables, and firewall rules. Used by containers (Docker, Kubernetes). veth pairs connect namespaces. Bridge devices connect multiple namespaces to a shared network.' },
            { type: 'attachment', name: 'Networking Lab' },
        ]},
        { title: 'Embedded and Real-Time Operating Systems', description: 'RTOS concepts, scheduling guarantees, and embedded OS design.', units: [
            { type: 'text', name: 'Real-Time OS Requirements', content: 'RTOS must provide deterministic response times. Hard real-time guarantees deadline compliance. Interrupt latency must be bounded. Priority inversion is prevented by priority inheritance or priority ceiling protocols. FreeRTOS and VxWorks are popular RTOS.' },
            { type: 'text', name: 'Embedded OS Design', content: 'Embedded OS run on resource-constrained devices. Features: small memory footprint, fast boot, deterministic behavior, hardware abstraction layers. Zephyr RTOS supports multiple architectures. Linux is used for more capable embedded systems (Yocto, Buildroot).' },
            { type: 'online', name: 'RTOS Comparison', description: 'Feature comparison of FreeRTOS, Zephyr, VxWorks, and RT Linux for embedded and real-time applications.' },
            { type: 'text', name: 'Task Scheduling in RTOS', content: 'RTOS schedulers use fixed priority preemptive scheduling. Rate Monotonic Scheduling assigns higher priority to shorter periods. Earliest Deadline First dynamically prioritizes nearest deadlines. Schedulability analysis verifies all tasks meet deadlines.' },
            { type: 'attachment', name: 'RTOS Development Guide' },
        ]},
        { title: 'Distributed Operating Systems', description: 'Distributed file systems, distributed shared memory, and clock synchronization.', units: [
            { type: 'text', name: 'Distributed File Systems', content: 'NFS provides transparent remote file access using RPC. HDFS stores large files across clusters with replication. GFS (Google File System) uses append-only writes for large sequential workloads. Ceph provides object, block, and file storage in a unified system.' },
            { type: 'text', name: 'Clock Synchronization', content: 'Physical clocks drift and need synchronization. NTP synchronizes to time servers with millisecond accuracy. Logical clocks (Lamport) order events without physical time. Vector clocks detect causality. Hybrid logical clocks combine both approaches.' },
            { type: 'online', name: 'Distributed Systems Concepts', description: 'Overview of distributed operating system challenges: naming, consistency, fault tolerance, and coordination.' },
            { type: 'text', name: 'Distributed Shared Memory', content: 'DSM provides the illusion of shared memory across networked machines. Pages migrate or replicate between nodes on access. Consistency models range from strict to eventual. False sharing occurs when unrelated data shares a page, causing unnecessary transfers.' },
            { type: 'attachment', name: 'Distributed OS Case Study' },
        ]},
        { title: 'System Performance Analysis', description: 'Performance metrics, profiling tools, and bottleneck identification.', units: [
            { type: 'text', name: 'Performance Metrics', content: 'Key metrics: CPU utilization, throughput (tasks/second), response time (latency), turnaround time, waiting time, and context switch rate. Use percentiles (p50, p95, p99) for latency. Little\'s Law: L = lambda * W (queue length = arrival rate * wait time).' },
            { type: 'text', name: 'Linux Performance Tools', content: 'top/htop show real-time CPU and memory usage. perf profiles CPU usage with hardware counters. strace traces system calls. vmstat shows memory/CPU statistics. iostat monitors disk I/O. sar collects historical performance data. bpftrace enables custom tracing.' },
            { type: 'online', name: 'Performance Analysis Methodology', description: 'Brendan Gregg\'s USE Method (Utilization, Saturation, Errors) for systematic performance analysis.' },
            { type: 'text', name: 'Bottleneck Identification', content: 'CPU bottleneck: high utilization, long run queues. Memory bottleneck: high swap usage, page faults. I/O bottleneck: high disk utilization, long I/O wait. Network bottleneck: high bandwidth utilization, packet drops. Profile before optimizing.' },
            { type: 'attachment', name: 'Performance Lab' },
        ]},
        { title: 'Modern OS Topics', description: 'Unikernels, serverless computing, and OS research directions.', units: [
            { type: 'text', name: 'Unikernels and Library OS', content: 'Unikernels compile application and OS into a single binary running on a hypervisor. No unused OS code means smaller attack surface and faster boot (milliseconds). MirageOS, IncludeOS, and Unikraft are notable projects. Best for single-purpose cloud workloads.' },
            { type: 'text', name: 'Serverless and Function-as-a-Service', content: 'Serverless computing (AWS Lambda, Azure Functions) abstracts away OS management entirely. Functions execute in ephemeral containers. Cold start latency is a challenge. Firecracker microVMs provide fast, secure isolation for serverless workloads.' },
            { type: 'online', name: 'Future of Operating Systems', description: 'Research directions in operating systems: verified kernels, persistent memory integration, and heterogeneous computing support.' },
            { type: 'text', name: 'Hardware Security and TEEs', content: 'Trusted Execution Environments (Intel SGX, ARM TrustZone) provide hardware-isolated enclaves. Code and data inside enclaves are protected from the OS and other software. Used for secure key management, DRM, and confidential computing in the cloud.' },
            { type: 'attachment', name: 'Modern OS Research Papers' },
        ]},
        { title: 'OS Design and Implementation', description: 'Building an operating system kernel from scratch.', units: [
            { type: 'text', name: 'Bootloader and Kernel Initialization', content: 'BIOS/UEFI loads the bootloader (GRUB). The bootloader loads the kernel into memory, sets up protected mode, enables paging, and jumps to the kernel entry point. Kernel initialization sets up interrupt handlers, memory manager, and scheduler before starting init.' },
            { type: 'text', name: 'Interrupt and Exception Handling', content: 'The Interrupt Descriptor Table (IDT) maps interrupt numbers to handlers. Hardware interrupts come from devices. Software interrupts are triggered by the int instruction. Exceptions handle errors (page fault, division by zero). The handler saves state, processes, and returns.' },
            { type: 'online', name: 'OS Development Tutorial', description: 'Step-by-step tutorial for building a minimal operating system kernel in C and assembly targeting x86-64.' },
            { type: 'text', name: 'Device Driver Framework', content: 'Device drivers translate OS requests to hardware operations. Character devices (keyboard, serial) handle byte streams. Block devices (disk) handle fixed-size blocks. The device model provides registration, probing, and power management frameworks.' },
            { type: 'attachment', name: 'Kernel Development Kit' },
        ]},
    ],
    exercises: {
        programming: [
            { title: 'Process Scheduler Simulator', problemStatement: 'Implement a CPU scheduler simulator supporting FCFS, SJF, Round Robin, and Priority scheduling. Compute average waiting time, turnaround time, and generate Gantt charts.' },
            { title: 'Thread Pool Implementation', problemStatement: 'Implement a thread pool with configurable pool size, task queue, and worker threads. Support task submission, graceful shutdown, and timeout-based task cancellation.' },
            { title: 'Memory Allocator', problemStatement: 'Implement a memory allocator with malloc, free, and realloc using a free list. Support first-fit, best-fit, and worst-fit allocation with coalescing of adjacent free blocks.' },
            { title: 'Page Replacement Simulator', problemStatement: 'Simulate FIFO, LRU, and Clock page replacement algorithms. Compute page fault rates for different reference strings and frame counts. Show Belady\'s anomaly for FIFO.' },
            { title: 'Producer-Consumer Problem', problemStatement: 'Implement the producer-consumer problem using a bounded buffer with pthreads. Use mutexes and condition variables. Handle multiple producers and consumers concurrently.' },
            { title: 'Simple Shell Implementation', problemStatement: 'Build a Unix shell that parses commands, forks processes, handles pipes (|), input/output redirection (<, >), and background execution (&). Implement built-in commands: cd, exit, jobs.' },
            { title: 'File System Implementation', problemStatement: 'Implement a simple file system on a disk image file. Support create, read, write, delete, mkdir, ls, and tree operations. Use an inode-based structure with a block bitmap.' },
            { title: 'Virtual Memory Manager', problemStatement: 'Implement a virtual memory manager with a page table, TLB simulation, demand paging, and page replacement. Translate virtual addresses to physical addresses with statistics.' },
            { title: 'Deadlock Detection', problemStatement: 'Implement a deadlock detection algorithm using a resource allocation graph. Detect cycles in the wait-for graph and suggest which processes to terminate for recovery.' },
            { title: 'Readers-Writers Lock', problemStatement: 'Implement a readers-writers lock with two policies: reader-preference and writer-preference. Use pthreads synchronization. Demonstrate fairness differences with concurrent threads.' },
            { title: 'Disk Scheduler', problemStatement: 'Implement FCFS, SSTF, SCAN, C-SCAN, LOOK, and C-LOOK disk scheduling algorithms. Compute total seek distance and show head movement for each algorithm.' },
            { title: 'IPC Message Queue', problemStatement: 'Implement an inter-process communication system using shared memory and semaphores. Support multiple message types, priority-based delivery, and timeout on receive.' },
            { title: 'System Call Tracer', problemStatement: 'Build a system call tracer using ptrace that intercepts and logs system calls made by a child process. Display system call name, arguments, and return value.' },
            { title: 'Memory-Mapped File I/O', problemStatement: 'Implement a library for memory-mapped file I/O using mmap. Support reading, writing, and appending to files through memory mappings with proper synchronization.' },
            { title: 'Process Monitor', problemStatement: 'Build a process monitor that reads /proc to display process information: PID, command, state, CPU usage, memory usage, open files, and parent-child relationships.' },
            { title: 'Semaphore Implementation', problemStatement: 'Implement counting and binary semaphores using atomic operations and futex. Support wait (P), signal (V), and try_wait with timeout.' },
            { title: 'Buddy System Allocator', problemStatement: 'Implement a buddy system memory allocator that splits and coalesces power-of-two sized blocks. Track allocation state with a bitmap. Minimize internal fragmentation.' },
            { title: 'RAID Simulator', problemStatement: 'Simulate RAID 0, 1, 5, and 10 configurations. Model read/write operations, demonstrate failure recovery, and compare performance and capacity characteristics.' },
            { title: 'Dining Philosophers', problemStatement: 'Implement the Dining Philosophers problem with three solutions: resource ordering, arbitrator, and Chandy-Misra. Demonstrate that each prevents deadlock.' },
            { title: 'Copy-on-Write Fork', problemStatement: 'Implement a copy-on-write simulation for fork(). Pages are shared between parent and child until modified. Track page sharing state and copy statistics.' },
            { title: 'LRU Cache with Aging', problemStatement: 'Implement an LRU page replacement simulation using both a doubly linked list approach and a clock algorithm with aging bits. Compare fault rates.' },
            { title: 'Kernel Module: Character Device', problemStatement: 'Write a Linux kernel module that creates a character device. Implement open, read, write, and ioctl operations. Use a ring buffer for data storage.' },
            { title: 'Container Namespace Isolation', problemStatement: 'Use Linux namespaces (PID, mount, network, UTS) to create a minimal container. Implement basic resource isolation and a simple container runtime.' },
            { title: 'ext2 File System Reader', problemStatement: 'Implement a reader for the ext2 file system format. Parse the superblock, group descriptors, inode table, and directory entries to list files and read content.' },
            { title: 'Barrier Synchronization', problemStatement: 'Implement a reusable barrier for thread synchronization using pthreads. Support configurable thread count and demonstrate with a parallel computation example.' },
            { title: 'Priority Queue Scheduler', problemStatement: 'Implement a priority-based process scheduler with priority aging to prevent starvation. Support dynamic priority adjustment and preemption.' },
            { title: 'Memory Pool Allocator', problemStatement: 'Implement a fixed-size memory pool allocator for high-performance allocation. Pre-allocate blocks and use a free list. Compare performance with malloc/free.' },
            { title: 'Log-Structured File System', problemStatement: 'Implement a simplified log-structured file system that writes all modifications sequentially. Include a segment cleaner for garbage collection of obsolete data.' },
            { title: 'Device Driver Simulator', problemStatement: 'Simulate a block device driver with read, write, and ioctl operations. Implement an I/O request queue with scheduling and interrupt handling simulation.' },
            { title: 'Signal Handler Framework', problemStatement: 'Build a signal handling framework supporting registration, delivery, masking, and signal-safe operations. Handle SIGINT, SIGTERM, SIGCHLD, and SIGUSR1.' },
            { title: 'Slab Allocator', problemStatement: 'Implement a slab allocator for kernel object caching. Pre-allocate objects of specific sizes in slabs. Support construction and destruction callbacks.' },
            { title: 'cgroup Resource Controller', problemStatement: 'Build a resource controller using Linux cgroups v2. Limit CPU, memory, and I/O for process groups. Monitor resource usage and enforce limits.' },
            { title: 'Filesystem Journaling', problemStatement: 'Implement write-ahead journaling for a simple file system. Log metadata changes before applying them. Implement crash recovery by replaying the journal.' },
            { title: 'Multi-Level Page Table', problemStatement: 'Implement a multi-level page table simulator with configurable levels and page sizes. Demonstrate address translation and measure page table memory overhead.' },
            { title: 'Network Socket Server', problemStatement: 'Build a multi-threaded TCP server using sockets. Implement connection handling with a thread pool, graceful shutdown, and HTTP request parsing.' },
            { title: 'Process Scheduling Benchmark', problemStatement: 'Benchmark different scheduling algorithms under various workloads: CPU-bound, I/O-bound, mixed, and interactive. Generate comparison charts with statistics.' },
            { title: 'Virtual File System Layer', problemStatement: 'Implement a VFS layer that provides a uniform file interface over multiple backend storage systems (in-memory, disk file, network). Support mounting and path resolution.' },
            { title: 'Timer and Alarm System', problemStatement: 'Implement a timer subsystem supporting one-shot and periodic timers. Use a timer wheel data structure for efficient expiration management. Support callback functions.' },
            { title: 'Swap Space Manager', problemStatement: 'Implement a swap space manager that moves pages between RAM and disk. Track swap usage, implement eviction policies, and measure swap in/out rates.' },
            { title: 'Boot Sequence Simulator', problemStatement: 'Simulate the OS boot sequence: BIOS POST, bootloader, kernel loading, memory initialization, device detection, and init process startup. Log each stage.' },
        ],
        text: [
            { title: 'Monolithic vs Microkernel Debate', problemStatement: 'Compare monolithic and microkernel architectures. Discuss performance, reliability, security, and development complexity. Reference real systems (Linux, Minix, macOS).' },
            { title: 'Virtual Memory Benefits and Costs', problemStatement: 'Analyze the benefits of virtual memory (isolation, large address spaces, memory-mapped files) and its costs (page faults, TLB misses, memory overhead). When might you disable it?' },
            { title: 'Container vs VM Comparison', problemStatement: 'Compare containers and virtual machines across isolation, security, performance, density, and portability. When would you choose one over the other?' },
            { title: 'Linux Scheduler Evolution', problemStatement: 'Trace the evolution of the Linux process scheduler from O(n) to O(1) to CFS to EEVDF. What problems did each solve and what trade-offs were made?' },
            { title: 'Future of Operating Systems', problemStatement: 'Discuss how emerging hardware (persistent memory, heterogeneous computing, hardware enclaves) will change operating system design in the next decade.' },
        ],
        modeling: [
            { title: 'Process State Diagram', problemStatement: 'Create a class diagram showing Process, Thread, Scheduler, and ReadyQueue classes with their relationships and key methods.', diagramType: 'ClassDiagram' },
            { title: 'Memory Management Architecture', problemStatement: 'Design a class diagram for virtual memory management showing PageTable, TLB, Frame, Page, and SwapSpace classes.', diagramType: 'ClassDiagram' },
            { title: 'System Call Flow', problemStatement: 'Create an activity diagram showing the flow of a system call from user space through the kernel and back: trap, handler dispatch, execution, return.', diagramType: 'ActivityDiagram' },
            { title: 'File System Operations', problemStatement: 'Model an activity diagram for file creation: path resolution, inode allocation, block allocation, directory entry creation, and journal commit.', diagramType: 'ActivityDiagram' },
            { title: 'Boot Process', problemStatement: 'Create an activity diagram for the OS boot sequence from BIOS/UEFI through bootloader, kernel initialization, to user space init.', diagramType: 'ActivityDiagram' },
        ],
        quiz: [
            { title: 'Process Management Quiz', questions: [
                { type: 'multiple-choice', title: 'Process States', text: 'Which state does a process enter when waiting for I/O?', points: 5, singleChoice: true, answerOptions: [{ text: 'Waiting/Blocked', isCorrect: true }, { text: 'Ready', isCorrect: false }, { text: 'Running', isCorrect: false }, { text: 'Terminated', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Fork System Call', text: 'What does fork() return to the child process?', points: 5, singleChoice: true, answerOptions: [{ text: '0', isCorrect: true }, { text: 'Child PID', isCorrect: false }, { text: '-1', isCorrect: false }, { text: 'Parent PID', isCorrect: false }] },
            ]},
            { title: 'Memory Management Quiz', questions: [
                { type: 'multiple-choice', title: 'Page Size', text: 'What is the typical page size on x86-64 systems?', points: 5, singleChoice: true, answerOptions: [{ text: '4 KB', isCorrect: true }, { text: '1 KB', isCorrect: false }, { text: '64 KB', isCorrect: false }, { text: '1 MB', isCorrect: false }] },
                { type: 'multiple-choice', title: 'TLB', text: 'What does the TLB cache?', points: 5, singleChoice: true, answerOptions: [{ text: 'Page table entries', isCorrect: true }, { text: 'Disk blocks', isCorrect: false }, { text: 'CPU instructions', isCorrect: false }, { text: 'Process IDs', isCorrect: false }] },
            ]},
            { title: 'File Systems Quiz', questions: [
                { type: 'multiple-choice', title: 'Inode', text: 'What does an inode store?', points: 5, singleChoice: true, answerOptions: [{ text: 'File metadata and block pointers', isCorrect: true }, { text: 'File name only', isCorrect: false }, { text: 'File contents', isCorrect: false }, { text: 'Directory listing', isCorrect: false }] },
                { type: 'multiple-choice', title: 'Journaling', text: 'What is the primary purpose of file system journaling?', points: 5, singleChoice: true, answerOptions: [{ text: 'Crash recovery and consistency', isCorrect: true }, { text: 'Faster read performance', isCorrect: false }, { text: 'Data compression', isCorrect: false }, { text: 'File encryption', isCorrect: false }] },
            ]},
        ],
        fileUpload: [
            { title: 'Scheduling Algorithm Analysis', problemStatement: 'Upload a report comparing CPU scheduling algorithms on a realistic workload. Include simulation results, Gantt charts, and statistical analysis of waiting and turnaround times.' },
            { title: 'File System Performance Report', problemStatement: 'Upload a benchmarking report comparing ext4, XFS, and Btrfs file systems for different workloads: sequential writes, random reads, metadata operations, and small file creation.' },
        ],
    },
    faqs: [
        { title: 'What is the difference between a process and a thread?', answer: 'A process has its own address space, file descriptors, and resources. A thread shares the process address space and resources but has its own stack and registers. Thread creation is faster and threads communicate more easily through shared memory.' },
        { title: 'How does virtual memory work?', answer: 'Virtual memory maps virtual addresses to physical addresses using page tables. Each process has its own virtual address space. Pages are loaded on demand (demand paging). If a page is not in RAM, a page fault loads it from disk. The TLB caches translations.' },
        { title: 'What causes a deadlock?', answer: 'Deadlock requires four conditions simultaneously: mutual exclusion, hold and wait, no preemption, and circular wait. Breaking any one condition prevents deadlock. Common strategies: resource ordering (prevents circular wait), timeouts, and deadlock detection with recovery.' },
        { title: 'What is a context switch?', answer: 'A context switch saves the current process state (registers, PC, page table pointer) and loads the state of the next process. It occurs on timer interrupts, system calls, or I/O completions. Context switches cost 1-10 microseconds and flush pipeline/TLB state.' },
        { title: 'How does the Linux scheduler work?', answer: 'Linux CFS (Completely Fair Scheduler) uses a red-black tree sorted by virtual runtime. Processes that have used less CPU get scheduled first. Nice values adjust the weight. CFS provides proportional fairness rather than fixed time slices.' },
        { title: 'What is thrashing?', answer: 'Thrashing occurs when a process spends more time paging than executing because its working set exceeds available physical memory. The system constantly swaps pages in and out. Solution: increase memory, reduce process count, or use working set algorithms.' },
        { title: 'What is the difference between paging and segmentation?', answer: 'Paging divides memory into fixed-size pages (transparent to programs). Segmentation divides into variable-size logical segments (code, data, stack). Modern systems use paging. x86-64 effectively disables segmentation, relying on paging with 4-level page tables.' },
        { title: 'How do semaphores work?', answer: 'A semaphore is an integer with two atomic operations: wait (P/down) decrements and blocks if zero; signal (V/up) increments and wakes a waiting process. Binary semaphores (0 or 1) act as mutexes. Counting semaphores control access to a pool of resources.' },
        { title: 'What is DMA?', answer: 'Direct Memory Access allows devices to transfer data to/from memory without CPU involvement. The CPU programs the DMA controller with source, destination, and count, then is free for other work. An interrupt signals completion. Essential for high-speed I/O.' },
        { title: 'What are the differences between RAID levels?', answer: 'RAID 0: striping, no redundancy, max performance. RAID 1: mirroring, 50% capacity, fast reads. RAID 5: distributed parity, good read performance, one disk fault tolerance. RAID 6: double parity, two disk fault tolerance. RAID 10: mirrored stripes, best performance with redundancy.' },
        { title: 'How does copy-on-write work?', answer: 'Copy-on-write shares memory pages between parent and child after fork(). Pages are marked read-only. When either process writes, a page fault triggers copying just that page. This avoids copying the entire address space if the child calls exec() immediately.' },
        { title: 'What is a system call?', answer: 'A system call is the programmatic interface between user programs and the OS kernel. It transitions from user mode to kernel mode via a trap instruction. Examples: read(), write(), fork(), exec(), open(), close(). The C library wraps system calls for convenience.' },
        { title: 'How do containers differ from virtual machines?', answer: 'Containers share the host kernel, using namespaces for isolation and cgroups for resource limits. VMs run a full guest OS on virtualized hardware. Containers are lighter (MB vs GB), start faster (ms vs seconds), but provide weaker isolation than VMs.' },
        { title: 'What is the buddy system?', answer: 'The buddy system allocates memory in power-of-two blocks. When a block is freed, it merges with its buddy (adjacent same-size block) if both are free. This reduces external fragmentation. Linux uses the buddy system for physical page allocation.' },
        { title: 'What is a page fault?', answer: 'A page fault occurs when a process accesses a page not currently in physical memory. The OS handles it by: finding the page on disk, loading it into a free frame (possibly evicting another page), updating the page table, and restarting the instruction.' },
        { title: 'How does file system journaling prevent corruption?', answer: 'Journaling writes a description of metadata changes to a log before applying them to the file system. If a crash occurs, the journal is replayed during recovery. This ensures the file system remains consistent without a full fsck scan.' },
        { title: 'What is the difference between preemptive and non-preemptive scheduling?', answer: 'Preemptive scheduling can interrupt a running process (via timer interrupt) to schedule another. Non-preemptive (cooperative) scheduling requires the running process to voluntarily yield. Most modern OS use preemptive scheduling for responsiveness.' },
        { title: 'What is ASLR?', answer: 'Address Space Layout Randomization randomizes the positions of the stack, heap, libraries, and executable in the virtual address space. This makes it harder for attackers to predict target addresses for buffer overflow exploits. Most modern OS enable ASLR by default.' },
        { title: 'What is a spinlock and when should I use it?', answer: 'A spinlock busy-waits (spins) in a loop until the lock becomes available. Use spinlocks for very short critical sections on multiprocessor systems where sleeping would be more expensive than spinning. Never use spinlocks for long or I/O-blocking operations.' },
        { title: 'How does the OOM killer work in Linux?', answer: 'When the system runs out of memory, the OOM (Out-Of-Memory) killer selects a process to terminate based on a badness score. The score considers memory usage, CPU time, and oom_score_adj. Important processes can be protected by setting oom_score_adj to -1000.' },
    ],
    channelMessages: [
        'Can someone explain the difference between user mode and kernel mode? When does the transition happen?',
        'My producer-consumer implementation has a race condition. How do I debug threading issues?',
        'What is the advantage of multi-level page tables over a single-level page table?',
        'How does the Linux CFS scheduler decide which process to run next?',
        'I am confused about the difference between internal and external fragmentation. Can someone clarify?',
        'Why does fork() return different values in the parent and child process?',
        'How do I choose between a mutex and a semaphore for synchronization?',
        'What happens when a process accesses memory that has been swapped to disk?',
        'Can someone explain how the buddy system allocator handles memory requests that are not powers of two?',
        'How does RAID 5 recover data when a single disk fails?',
        'What is the difference between a hard link and a soft link in Unix file systems?',
        'How do cgroups limit CPU and memory usage for containers?',
        'My disk scheduler simulation gives different results for SCAN and C-SCAN. Is that expected?',
        'What is the purpose of the idle process (PID 0) in Linux?',
        'How does the TLB interact with context switches? Does it need to be flushed?',
    ],
};
